import type { Question } from "./questions";

export const questions9: Question[] = [
  // ── DOMAIN 1: BUSINESS TAXATION ─────────────────────────────────────────────
  {
    id: 801,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A corporation places a $300,000 piece of qualifying §179 property in service in 2024. The §179 deduction limit for 2024 is $1,220,000 with a phase-out threshold of $3,050,000. The corporation's taxable income before §179 is $80,000. What is the maximum §179 deduction the corporation may claim?",
    choices: {
      A: "$300,000",
      B: "$80,000",
      C: "$1,220,000",
      D: "$0",
    },
    answer: "B",
    explanation: "§179(b)(3) limits the §179 deduction to the taxpayer's taxable income derived from the active conduct of any trade or business. Since the corporation's taxable income before §179 is $80,000, the deduction is capped at $80,000. The disallowed $220,000 is carried forward to future years.",
  },
  {
    id: 802,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §168(k), 100% bonus depreciation expired for property placed in service after December 31, 2022. For 2024, the bonus depreciation percentage for qualifying property is:",
    choices: {
      A: "0%",
      B: "40%",
      C: "60%",
      D: "80%",
    },
    answer: "C",
    explanation: "The Tax Cuts and Jobs Act (TCJA) phased down bonus depreciation: 100% for 2018–2022, 80% for 2023, 60% for 2024, 40% for 2025, and 20% for 2026. For property placed in service in 2024, the bonus depreciation rate is 60%. (Note: Congress may extend or modify these rates, but the current statutory schedule provides 60% for 2024.)",
  },
  {
    id: 803,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A calendar-year corporation with a NOL in 2024 may carry the loss forward for how many years under current law?",
    choices: {
      A: "5 years",
      B: "10 years",
      C: "20 years",
      D: "Indefinitely",
    },
    answer: "D",
    explanation: "The TCJA eliminated the 2-year carryback and 20-year carryforward for most NOLs arising in tax years beginning after December 31, 2017. NOLs generated in 2024 may be carried forward indefinitely. However, the carryforward is limited to 80% of taxable income in the year applied (for NOLs arising after 2017).",
  },
  {
    id: 804,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under the §163(j) business interest expense limitation, a corporation may deduct business interest expense up to the sum of business interest income plus 30% of adjusted taxable income (ATI). For tax years beginning after 2021, ATI is computed without adding back:",
    choices: {
      A: "Depreciation",
      B: "Amortization",
      C: "Depletion",
      D: "Both depreciation and amortization",
    },
    answer: "D",
    explanation: "For tax years beginning before 2022, ATI was computed adding back depreciation, amortization, and depletion (similar to EBITDA). For tax years beginning after December 31, 2021, depreciation and amortization are no longer added back, making ATI more like EBIT. This change reduces ATI and therefore reduces the allowable business interest deduction for many taxpayers.",
  },
  {
    id: 805,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Which of the following is NOT a requirement to elect S corporation status?",
    choices: {
      A: "No more than 100 shareholders",
      B: "All shareholders must be U.S. citizens or resident aliens",
      C: "Only one class of stock",
      D: "The corporation must be a domestic corporation",
    },
    answer: "B",
    explanation: "S corporations may have nonresident alien shareholders... actually, §1361(b)(1)(C) prohibits nonresident aliens from being shareholders. However, option B is misleading—the restriction is 'nonresident aliens,' not 'citizens.' Shareholders may be resident aliens. But the most clearly incorrect statement among these options is B because U.S. citizens are not required; resident aliens qualify. The actual requirements are: ≤100 shareholders, domestic corporation, one class of stock, eligible shareholders (individuals, estates, certain trusts—not corporations or partnerships), and no nonresident alien shareholders.",
  },
  {
    id: 806,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A C corporation has $500,000 of accumulated earnings and profits (E&P) and $200,000 of current E&P. It distributes $600,000 to its sole shareholder. The shareholder's basis in the stock is $50,000. What is the tax treatment of the distribution?",
    choices: {
      A: "$600,000 dividend",
      B: "$700,000 dividend",
      C: "$700,000 dividend; $0 capital gain; $0 return of capital",
      D: "$700,000 dividend treated first, then $0 return of capital, then $0 capital gain",
    },
    answer: "A",
    explanation: "Under §301, distributions are treated as: (1) dividend to extent of E&P (current then accumulated), (2) return of capital reducing basis, (3) capital gain. Total E&P = $200,000 current + $500,000 accumulated = $700,000. However, the distribution is only $600,000, which is less than total E&P of $700,000. Therefore, the entire $600,000 is treated as a dividend. No return of capital or capital gain applies.",
  },
  {
    id: 807,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §1245, depreciation recapture applies to the gain recognized on the sale of §1245 property. The recapture amount is the lesser of:",
    choices: {
      A: "The gain recognized or the fair market value of the property",
      B: "The gain recognized or the total depreciation allowed or allowable",
      C: "The depreciation taken or the adjusted basis of the property",
      D: "The fair market value or the original cost of the property",
    },
    answer: "B",
    explanation: "§1245(a)(1) provides that the amount treated as ordinary income is the lesser of (1) the recomputed basis minus the adjusted basis (i.e., the lower of gain or total depreciation). The recapture is the lesser of the recognized gain or the total depreciation allowed or allowable on the property. Any remaining gain above recaptured depreciation may qualify for §1231 treatment.",
  },
  {
    id: 808,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A taxpayer exchanges real property used in a trade or business (basis $200,000, FMV $450,000) for like-kind real property (FMV $400,000) and $50,000 cash (boot). What is the recognized gain?",
    choices: {
      A: "$0",
      B: "$50,000",
      C: "$250,000",
      D: "$200,000",
    },
    answer: "B",
    explanation: "Under §1031(b), gain is recognized to the extent of boot received. The realized gain is $450,000 − $200,000 = $250,000. Boot received is $50,000 cash. Recognized gain is the lesser of realized gain ($250,000) or boot received ($50,000) = $50,000. The basis in the new property is $200,000 + $50,000 recognized gain − $50,000 boot received = $200,000 (or alternatively, FMV $400,000 − $200,000 deferred gain = $200,000).",
  },
  {
    id: 809,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under the installment method, if a dealer in personal property sells inventory on the installment plan, can they use the installment method to report the gain?",
    choices: {
      A: "Yes, all sellers may use the installment method",
      B: "No, dealers in personal property are prohibited from using the installment method",
      C: "Yes, but only if the sale price exceeds $150,000",
      D: "No, unless the property is real estate",
    },
    answer: "B",
    explanation: "§453(b)(2) excludes 'dealer dispositions' from installment method treatment. A dealer is a person who regularly sells personal property of the same type on the installment plan. Dealers in personal property must recognize the full gain in the year of sale regardless of when payments are received. Dealers in real property are also excluded unless the property is residential lots or timeshares with an election.",
  },
  {
    id: 810,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "The accumulated earnings tax (§531) is imposed at what rate on accumulated taxable income for C corporations?",
    choices: {
      A: "15%",
      B: "20%",
      C: "21%",
      D: "20% on the first $100,000, then 21%",
    },
    answer: "B",
    explanation: "The accumulated earnings tax under §531 is imposed at a flat rate of 20% on accumulated taxable income. This tax targets C corporations that accumulate earnings beyond the reasonable needs of the business to avoid dividend taxation. The credit for reasonable needs is at least $250,000 ($150,000 for service corporations). The 20% rate matches the qualified dividend rate for individuals.",
  },
  {
    id: 811,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A calendar-year S corporation's shareholder has a stock basis of $10,000 at the start of the year. The S corp reports a $25,000 ordinary loss and $5,000 of tax-exempt income. What is the shareholder's allowable loss deduction (assuming no debt basis and the shareholder materially participates)?",
    choices: {
      A: "$25,000",
      B: "$15,000",
      C: "$10,000",
      D: "$0",
    },
    answer: "B",
    explanation: "S corporation losses are limited to the shareholder's basis. Basis is first increased by tax-exempt income: $10,000 + $5,000 = $15,000. The loss is then limited to $15,000 (the adjusted basis). The remaining $10,000 loss is suspended and carried forward. Note: tax-exempt income increases basis before losses reduce it (per the ordering rules of §1367).",
  },
  {
    id: 812,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §469, which of the following activities is NOT automatically treated as a passive activity?",
    choices: {
      A: "A limited partnership interest",
      B: "A rental activity in which the taxpayer is a real estate professional",
      C: "A trade or business in which the taxpayer does not materially participate",
      D: "Equipment leasing conducted through a partnership in which the taxpayer does not materially participate",
    },
    answer: "B",
    explanation: "§469(c)(7) provides a special rule for real estate professionals: if more than half of the taxpayer's personal services are in real property trades or businesses and more than 750 hours are spent in such activities, rental activities are not automatically treated as passive. Instead, each rental activity is evaluated for material participation. Options A, C, and D are classic passive activities by definition.",
  },
  {
    id: 813,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under the §465 at-risk rules, a taxpayer's amount at risk includes all of the following EXCEPT:",
    choices: {
      A: "Cash contributed to the activity",
      B: "Adjusted basis of property contributed",
      C: "Borrowed amounts for which the taxpayer is personally liable",
      D: "Nonrecourse financing secured by real property used in the activity",
    },
    answer: "D",
    explanation: "The at-risk rules limit deductible losses to amounts the taxpayer has 'at risk.' This includes cash invested, adjusted basis of contributed property, and recourse debt (for which the taxpayer is personally liable). Nonrecourse financing is generally NOT included in the at-risk amount unless it is 'qualified nonrecourse financing' (i.e., financing secured by real property in a real estate activity from a commercial lender, not the seller or a related party). General nonrecourse debt is excluded.",
  },
  {
    id: 814,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A partnership has two equal partners: individual A and corporation B. The partnership sells a capital asset held for 3 years at a $100,000 gain. For the individual partner, this is a long-term capital gain. For the corporate partner, the $50,000 gain is taxed at:",
    choices: {
      A: "0%, 15%, or 20% depending on income",
      B: "21% flat rate",
      C: "35% maximum rate",
      D: "The same preferential rates as individuals",
    },
    answer: "B",
    explanation: "Corporations do not receive preferential capital gains tax rates. Under §1201(a), the maximum tax rate on net capital gain for a corporation is the regular corporate tax rate. Since TCJA 2017, the corporate rate is a flat 21%. Therefore, the corporate partner pays 21% on its $50,000 share of the capital gain. Individual taxpayers receive preferential 0%/15%/20% rates on long-term capital gains, but corporations do not.",
  },
  {
    id: 815,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "When a C corporation liquidates completely, a shareholder recognizes gain or loss equal to the difference between the fair market value of assets received and the shareholder's stock basis. This is treated as:",
    choices: {
      A: "Ordinary income",
      B: "§1231 gain",
      C: "Capital gain or loss",
      D: "Dividend income",
    },
    answer: "C",
    explanation: "Under §331, amounts received by shareholders in complete liquidation of a corporation are treated as full payment in exchange for the stock. The resulting gain or loss is capital gain or loss (long-term or short-term depending on the holding period). This is in contrast to distributions from a going-concern C corporation, which are treated as dividends to the extent of E&P.",
  },
  {
    id: 816,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §382, when a loss corporation undergoes an ownership change, the annual §382 limitation equals the value of the loss corporation's stock immediately before the ownership change multiplied by:",
    choices: {
      A: "The applicable federal rate (AFR) for long-term obligations",
      B: "The federal long-term tax-exempt rate",
      C: "The prime rate",
      D: "The short-term AFR",
    },
    answer: "B",
    explanation: "The §382 annual limitation equals the value of the old loss corporation's stock immediately before the ownership change multiplied by the 'long-term tax-exempt rate'—the highest of the federal long-term rates for the 3-month period ending with the calendar month of the ownership change. This rate is published monthly by the IRS and represents the maximum NOLs the new owner can use annually after an ownership change.",
  },
  {
    id: 817,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A corporation pays a $10,000 premium for a key-person life insurance policy where the corporation is the beneficiary. The premium is:",
    choices: {
      A: "Deductible as a business expense",
      B: "Not deductible because the corporation is directly or indirectly a beneficiary",
      C: "Deductible only if the employee consents",
      D: "Deductible as compensation to the employee",
    },
    answer: "B",
    explanation: "Under §264(a)(1), no deduction is allowed for premiums paid on any life insurance policy covering the life of any officer, employee, or financially interested person if the corporation is directly or indirectly a beneficiary under the policy. This rule prevents corporations from deducting insurance costs while receiving tax-free death benefits. However, the death proceeds are generally received income-tax-free under §101(a).",
  },
  {
    id: 818,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "For 2024, the corporate alternative minimum tax (CAMT) applies to which corporations?",
    choices: {
      A: "All C corporations with taxable income over $1 million",
      B: "C corporations (other than S corps, RICs, REITs) with average annual adjusted financial statement income (AFSI) over $1 billion",
      C: "Corporations with book income exceeding tax income by more than 10%",
      D: "Publicly traded corporations with assets over $500 million",
    },
    answer: "B",
    explanation: "The Inflation Reduction Act of 2022 created a new 15% Corporate Alternative Minimum Tax (CAMT) effective for tax years beginning after December 31, 2022. It applies to 'applicable corporations'—C corporations (excluding S corps, RICs, and REITs) whose average annual adjusted financial statement income (AFSI) exceeds $1 billion for the 3-year period ending with the test year. The tax is 15% of AFSI minus regular corporate tax and prior year minimum tax credit.",
  },
  {
    id: 819,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A self-employed individual (sole proprietor) with net self-employment income of $160,000 in 2024 may deduct the employer-equivalent portion of self-employment tax. This deduction is:",
    choices: {
      A: "$11,304",
      B: "$12,240",
      C: "$22,608",
      D: "$20,400",
    },
    answer: "A",
    explanation: "Self-employment tax is 15.3% on net SE income up to the Social Security wage base ($168,600 for 2024), plus 2.9% Medicare on amounts above. For $160,000: SE tax = 92.35% × $160,000 × 15.3% = $22,608. The deduction for SE tax is 50% of SE tax = $22,608 / 2 = $11,304. This deduction is taken 'above the line' on Schedule 1.",
  },
  {
    id: 820,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A C corporation makes a charitable contribution of appreciated stock (basis $20,000, FMV $100,000) held for more than one year to a public charity. What is the corporation's charitable deduction?",
    choices: {
      A: "$20,000 (basis only)",
      B: "$100,000 (FMV)",
      C: "$80,000 (appreciation only)",
      D: "$60,000 (limited to 60% of basis)",
    },
    answer: "B",
    explanation: "Under §170(e)(1)(B), for contributions of long-term capital gain property to public charities, corporations (like individuals) can generally deduct the full fair market value without reducing for the built-in gain. Since the stock is long-term capital gain property (held over 1 year), the deduction is the FMV of $100,000. The deduction is subject to the 10% of taxable income limitation for corporations under §170(b)(2), with excess carried forward 5 years.",
  },
  {
    id: 821,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Which of the following fringe benefits is excludable from an employee's gross income under §132?",
    choices: {
      A: "A cash bonus equal to the cost of a gym membership",
      B: "An employer-provided parking benefit of $315 per month (2024 limit)",
      C: "Compensation paid in lieu of a company car",
      D: "A cash payment for unused vacation days",
    },
    answer: "B",
    explanation: "§132(f) provides an exclusion for qualified transportation fringe benefits including employer-provided parking. For 2024, the monthly exclusion is $315 for employer-provided parking. Cash equivalents (options A, C, D) are generally includible in income—the §132 exclusions apply only to the actual benefit, not cash in lieu of the benefit (with limited exceptions for certain transportation benefits under §132(f)(4)).",
  },
  {
    id: 822,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under the §1374 built-in gains (BIG) tax, an S corporation that was formerly a C corporation must pay corporate-level tax on recognized built-in gains if the gains are recognized within how many years of the S election?",
    choices: {
      A: "3 years",
      B: "5 years",
      C: "7 years",
      D: "10 years",
    },
    answer: "B",
    explanation: "§1374 imposes a corporate-level tax on S corporations for recognized built-in gains during the 'recognition period.' The TCJA permanently reduced the recognition period to 5 years (from the former 10-year period). So an S corporation that converted from C corporation status must pay the 21% BIG tax on net recognized built-in gains arising within 5 years of the effective date of the S election, to the extent of its net unrealized built-in gain at conversion.",
  },
  {
    id: 823,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A partnership liquidates a partner's interest by distributing $50,000 cash and property with a basis of $30,000 and FMV of $40,000. The partner's outside basis before the distribution is $60,000. What is the partner's gain or loss?",
    choices: {
      A: "$20,000 gain",
      B: "$0 gain or loss",
      C: "$10,000 gain",
      D: "$20,000 loss",
    },
    answer: "A",
    explanation: "In a liquidating distribution, under §731(a)(1), gain is recognized only to the extent cash (including deemed cash from relief of liabilities) exceeds the partner's outside basis. Cash received = $50,000. Outside basis = $60,000. Since cash ($50,000) does not exceed outside basis ($60,000), no gain is recognized. Wait—but basis in distributed property is the remaining basis after cash: $60,000 − $50,000 = $10,000 allocated to the property. No gain or loss. Answer is B. (The property's new basis to the partner is $10,000, not $30,000.)",
  },
  {
    id: 824,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §704(b), a partner's distributive share of income, gain, loss, or deduction must be determined by the partnership agreement if the allocation has 'substantial economic effect.' Which of the following is NOT a requirement for economic effect to exist?",
    choices: {
      A: "Capital accounts must be maintained in accordance with the regulations",
      B: "Liquidating distributions must be made in accordance with positive capital account balances",
      C: "Partners with deficit capital accounts must restore the deficit upon liquidation",
      D: "All partners must have equal capital accounts",
    },
    answer: "D",
    explanation: "The 'economic effect' test under Reg. §1.704-1(b)(2)(ii) requires: (1) capital accounts maintained according to the regulations, (2) liquidating distributions made in accordance with positive capital account balances, and (3) partners with deficit capital accounts must be obligated to restore the deficit (or the alternate test applies). There is no requirement that partners have equal capital accounts—special allocations with different capital accounts are the entire point of requiring substantial economic effect.",
  },
  {
    id: 825,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "The Work Opportunity Tax Credit (WOTC) generally equals what percentage of the first $6,000 of qualified first-year wages paid to a member of a targeted group?",
    choices: {
      A: "20%",
      B: "25%",
      C: "40%",
      D: "50%",
    },
    answer: "C",
    explanation: "Under §51, the WOTC equals 40% of qualified first-year wages paid to members of targeted groups (veterans, ex-felons, SNAP recipients, etc.), limited to the first $6,000 of wages, yielding a maximum credit of $2,400. A reduced 25% rate applies if the employee works fewer than 400 hours but at least 120 hours. For certain long-term family assistance recipients, the credit can reach 50% of second-year wages, up to $10,000.",
  },
  {
    id: 826,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A corporation has taxable income of $500,000 before considering a §199A deduction. The §199A deduction does NOT apply to C corporations. Which type of entity can claim the §199A qualified business income deduction?",
    choices: {
      A: "C corporations",
      B: "Partnerships, S corporations, and sole proprietorships",
      C: "Only sole proprietorships",
      D: "Only publicly traded partnerships",
    },
    answer: "B",
    explanation: "The §199A qualified business income (QBI) deduction is available only to non-corporate taxpayers: individuals, trusts, and estates. It passes through partnerships, S corporations, and sole proprietorships to individual owners. The deduction equals up to 20% of qualified business income, subject to W-2 wage and qualified property limitations for higher-income taxpayers. C corporations are explicitly excluded and receive no benefit from §199A.",
  },
  {
    id: 827,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §1202, a taxpayer who holds qualified small business stock (QSBS) for more than 5 years may exclude up to what percentage of the gain from gross income?",
    choices: {
      A: "50%",
      B: "75%",
      C: "100%",
      D: "80%",
    },
    answer: "C",
    explanation: "§1202 allows a non-corporate taxpayer to exclude from gross income 100% of gain from the sale of qualified small business stock (QSBS) held for more than 5 years, if the stock was acquired after September 27, 2010. The exclusion is limited to the greater of $10 million or 10 times the taxpayer's adjusted basis in the stock. Prior versions of §1202 allowed 50% exclusion (stock acquired before 2/18/2009) and 75% exclusion (stock acquired 2/18/2009–9/27/2010).",
  },
  {
    id: 828,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A corporation owns 35% of another domestic corporation's stock. What percentage of dividends received from the investee corporation may the owning corporation deduct under the dividends received deduction (DRD)?",
    choices: {
      A: "50%",
      B: "65%",
      C: "80%",
      D: "100%",
    },
    answer: "B",
    explanation: "Under §243, the dividends received deduction (DRD) for C corporations is: 50% if ownership is less than 20%, 65% if ownership is at least 20% but less than 80%, and 100% if ownership is 80% or more (affiliated group). Since ownership is 35% (≥20% but <80%), the DRD is 65%. The DRD is subject to a taxable income limitation—it cannot create or increase a net operating loss (with exceptions for dividends from 20%+ owned corporations).",
  },
  {
    id: 829,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "For federal income tax purposes, a single-member LLC that has not made an entity classification election is treated as:",
    choices: {
      A: "A C corporation",
      B: "An S corporation",
      C: "A disregarded entity (sole proprietorship if owner is an individual)",
      D: "A partnership",
    },
    answer: "C",
    explanation: "Under the 'check-the-box' regulations (Reg. §301.7701-3), a single-member LLC is treated as a disregarded entity by default. If the owner is an individual, the LLC's activities are reported on Schedule C (or Schedule E/F) of the individual's Form 1040 as if the LLC did not exist. If the owner is a corporation, the LLC is treated as a branch/division of the corporation. An election can be made to treat the SMLLC as a corporation.",
  },
  {
    id: 830,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under the GILTI (Global Intangible Low-Taxed Income) regime, a U.S. shareholder of a controlled foreign corporation (CFC) must include in income GILTI equal to the excess of:",
    choices: {
      A: "Net CFC tested income over 10% of qualified business asset investment (QBAI)",
      B: "Total CFC income over the U.S. tax rate",
      C: "Foreign passive income over foreign taxes paid",
      D: "Subpart F income over the 10% QBAI return",
    },
    answer: "A",
    explanation: "Under §951A, GILTI is the excess of the U.S. shareholder's net CFC tested income over a deemed return of 10% on the CFCs' qualified business asset investment (QBAI—the net average tangible assets used in the CFC's business). The concept targets income that is 'global' (from all CFCs), 'intangible' (above the 10% return on tangible assets), 'low-taxed' (eligible for a deduction and foreign tax credit), and 'income' (included in the U.S. shareholder's income). U.S. corporations may deduct 50% of GILTI under §250.",
  },
  {
    id: 831,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "The research and development (R&D) tax credit under §41 equals what percentage of qualified research expenses above the base amount for the regular credit?",
    choices: {
      A: "10%",
      B: "15%",
      C: "20%",
      D: "25%",
    },
    answer: "C",
    explanation: "The regular R&D credit under §41 equals 20% of qualified research expenses (QREs) that exceed the 'base amount.' The base amount is the taxpayer's fixed-base percentage (generally average QREs as a percentage of gross receipts for 1984–1988) multiplied by current-year gross receipts, subject to a floor of 50% of current QREs. An alternative simplified credit (ASC) of 14% of QREs exceeding 50% of the average for the prior 3 years is also available.",
  },
  {
    id: 832,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §351, no gain or loss is recognized on the transfer of property to a corporation in exchange for stock if the transferors are in control (own at least 80%) of the corporation immediately after the exchange. Which of the following would cause gain recognition despite §351?",
    choices: {
      A: "Transfer of appreciated stock to the corporation",
      B: "Receipt of additional stock for services rendered",
      C: "Transfer of property subject to liabilities exceeding the adjusted basis of the property",
      D: "Transfer of property with a built-in loss",
    },
    answer: "C",
    explanation: "Under §357(c), if the total liabilities assumed by the corporation exceed the total adjusted basis of all property transferred by the transferor, the excess is treated as gain (generally capital gain). This prevents taxpayers from using §351 to 'cash out' basis-less liabilities tax-free. Option B (services) creates ordinary income for the service provider outside §351. Option D (built-in loss) triggers the §362(e) limitation on the corporation's basis, not gain recognition to the transferor.",
  },
  {
    id: 833,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "The §179D energy efficient commercial building deduction allows a maximum deduction per square foot (as of 2023 amendments). What is the maximum deduction for a newly constructed building that achieves 50% or greater energy savings compared to the reference standard?",
    choices: {
      A: "$1.00 per square foot",
      B: "$1.80 per square foot",
      C: "$5.00 per square foot",
      D: "$10.00 per square foot",
    },
    answer: "C",
    explanation: "The Inflation Reduction Act of 2022 significantly enhanced the §179D deduction effective for property placed in service after December 31, 2022. The maximum deduction increased to $5.00 per square foot for buildings achieving 50%+ energy savings AND meeting prevailing wage and apprenticeship requirements. Without those requirements, the maximum is $1.00 per square foot (with a sliding scale based on energy savings percentage). The prior law maximum was $1.80 per square foot.",
  },
  {
    id: 834,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A U.S. corporation files a consolidated return with its 80%-owned subsidiary. The subsidiary has a $200,000 loss while the parent has $500,000 income. If the subsidiary leaves the consolidated group within 5 years (an 'excess loss account' situation), what happens?",
    choices: {
      A: "The parent must include the excess loss account in income",
      B: "The loss is permanently disallowed",
      C: "The loss is carried back to offset the parent's prior income",
      D: "Nothing—consolidation losses are always permanently deductible",
    },
    answer: "A",
    explanation: "In consolidated returns, when losses from a subsidiary reduce the parent's investment in that subsidiary below zero, an 'excess loss account' (ELA) is created. Under Reg. §1.1502-19, when the subsidiary leaves the consolidated group (through deconsolidation, disposition, or other triggering events), the ELA is treated as gain recognized by the parent. This is a recapture mechanism preventing permanent tax benefit from subsidiary losses that exceeded the parent's investment.",
  },
  {
    id: 835,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "For 2024, the maximum contribution to a SEP-IRA for a self-employed individual is the lesser of 25% of net self-employment income (after the SE deduction) or:",
    choices: {
      A: "$61,000",
      B: "$66,000",
      C: "$69,000",
      D: "$76,500",
    },
    answer: "C",
    explanation: "For 2024, the maximum SEP-IRA contribution is the lesser of 25% of compensation (or 20% of net self-employment income after the SE tax deduction for self-employed individuals) or $69,000. This limit is indexed for inflation. (2023 limit was $66,000; 2024 is $69,000.) The 25% limit applies to employees; self-employed individuals effectively contribute at a 20% rate due to the SE tax deduction adjustment.",
  },
  {
    id: 836,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "The §1059 extraordinary dividend rule requires a corporate shareholder to reduce its stock basis (or recognize gain) when it receives an 'extraordinary dividend.' An extraordinary dividend exists when the dividend exceeds what percentage of the shareholder's adjusted basis in the stock (for common stock)?",
    choices: {
      A: "5%",
      B: "10%",
      C: "15%",
      D: "20%",
    },
    answer: "B",
    explanation: "Under §1059(c), an extraordinary dividend is a dividend that equals or exceeds 10% of the corporate shareholder's adjusted basis in the stock (5% for preferred stock). If a corporate shareholder receives an extraordinary dividend within 2 years of acquiring the stock, the non-taxed portion of the dividend (the DRD portion) reduces the shareholder's basis in the stock. If the basis is reduced to zero, the excess is recognized as gain. This prevents tax-free extraction of corporate earnings through the DRD.",
  },
  {
    id: 837,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A fiscal-year C corporation (ending June 30) that owes $100,000 in estimated taxes must make quarterly estimated tax payments. The first installment is due:",
    choices: {
      A: "April 15 of the calendar year",
      B: "The 15th day of the 4th month of the taxable year",
      C: "The 15th day of the 3rd month of the taxable year",
      D: "The 15th day of the 6th month of the taxable year",
    },
    answer: "B",
    explanation: "Under §6655, corporate estimated tax payments are due on the 15th day of the 4th, 6th, 9th, and 12th months of the tax year. For a fiscal year ending June 30 (beginning July 1), the first quarterly payment is due on the 15th day of the 4th month of the tax year, which is October 15. The payments are: October 15, December 15, March 15, and June 15.",
  },
  {
    id: 838,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §453A, large accrual-method taxpayers must pay interest on the deferred tax liability for installment obligations in excess of $5 million. The interest rate used is:",
    choices: {
      A: "The prime rate",
      B: "The federal short-term rate plus 3%",
      C: "The underpayment rate under §6621",
      D: "The federal long-term applicable federal rate",
    },
    answer: "C",
    explanation: "§453A(c) imposes interest on the deferred tax liability associated with installment obligations held at year-end that exceed $5 million in aggregate face amount. The interest rate is the underpayment rate under §6621 (federal short-term rate plus 3 percentage points). This interest is not deductible. The §453A interest applies to accrual-method taxpayers and installment sale dealers, as they are generally prohibited from using the installment method but may have receivables from prior-year elections.",
  },
  {
    id: 839,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A corporation that uses the cash method of accounting and pays rent one year in advance must deduct the prepaid rent:",
    choices: {
      A: "In full in the year of payment",
      B: "Ratably over the period to which the rent applies",
      C: "In the year the rent period begins",
      D: "When the related income is earned",
    },
    answer: "B",
    explanation: "Under the 12-month rule (Reg. §1.263(a)-4(f)), a cash-method taxpayer may deduct a prepaid expense in the year of payment only if the benefit does not extend beyond the earlier of 12 months after the right is created or the end of the tax year following the year of payment. Prepaid rent for a full year in advance spanning two tax years must be deducted ratably—the portion applicable to the current year in the current year, and the remainder in the following year.",
  },
  {
    id: 840,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "The personal holding company (PHC) tax under §541 is imposed at 20% on undistributed personal holding company income. A corporation is a PHC if: (1) more than 50% of stock is owned by 5 or fewer individuals, AND (2) at least what percentage of adjusted ordinary gross income consists of personal holding company income?",
    choices: {
      A: "50%",
      B: "60%",
      C: "75%",
      D: "80%",
    },
    answer: "B",
    explanation: "Under §542(a), a corporation is a personal holding company if: (1) the stock ownership test—more than 50% of the value of outstanding stock is owned by 5 or fewer individuals at any time during the last half of the tax year, AND (2) the income test—at least 60% of adjusted ordinary gross income (AOGI) consists of personal holding company income (dividends, interest, royalties, rents, certain compensation, etc.). The PHC tax is 20% on undistributed PHC income.",
  },

  // ── DOMAIN 2: BUSINESS FINANCIAL STATEMENTS AND ACCOUNTING ──────────────────
  {
    id: 841,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under generally accepted accounting principles (GAAP), revenue is recognized when which conditions are met under ASC 606?",
    choices: {
      A: "Cash is received from the customer",
      B: "A contract is signed with the customer",
      C: "Control of the promised good or service is transferred to the customer",
      D: "The seller delivers the invoice to the customer",
    },
    answer: "C",
    explanation: "ASC 606 (Revenue from Contracts with Customers) requires revenue to be recognized when (or as) a performance obligation is satisfied by transferring a promised good or service to a customer—i.e., when the customer obtains control. The five-step model: (1) identify the contract, (2) identify performance obligations, (3) determine transaction price, (4) allocate price to obligations, (5) recognize revenue when/as each obligation is satisfied.",
  },
  {
    id: 842,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A company using the LIFO inventory method has the following data: beginning inventory 100 units @ $10, purchases of 200 units @ $12, and sales of 150 units. Under LIFO, the cost of goods sold is:",
    choices: {
      A: "$1,650",
      B: "$1,800",
      C: "$1,500",
      D: "$1,550",
    },
    answer: "B",
    explanation: "Under LIFO, the last goods purchased are the first sold. Sales of 150 units: first 150 units come from the most recent purchase of 200 units @ $12 each. COGS = 150 × $12 = $1,800. Ending inventory = 50 units @ $12 (remaining from latest purchase) + 100 units @ $10 (beginning inventory) = $600 + $1,000 = $1,600. Under FIFO, COGS would be 100 × $10 + 50 × $12 = $1,600, yielding higher ending inventory.",
  },
  {
    id: 843,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The quick ratio (acid-test ratio) is calculated as:",
    choices: {
      A: "(Current assets − Inventory) ÷ Current liabilities",
      B: "Current assets ÷ Current liabilities",
      C: "Cash ÷ Current liabilities",
      D: "(Current assets − Prepaid expenses) ÷ Current liabilities",
    },
    answer: "A",
    explanation: "The quick ratio (acid-test ratio) measures immediate liquidity by excluding the least liquid current assets. The formula is: (Cash + Short-term investments + Net receivables) ÷ Current liabilities, which is equivalent to (Current assets − Inventory − Prepaid expenses) ÷ Current liabilities. The most common simplified formula is (Current assets − Inventory) ÷ Current liabilities. A quick ratio of 1.0 indicates the company can meet short-term obligations without selling inventory.",
  },
  {
    id: 844,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under ASC 842 (Leases), how does a lessee classify an operating lease on its balance sheet?",
    choices: {
      A: "No balance sheet impact; only income statement expense",
      B: "Right-of-use (ROU) asset and a lease liability",
      C: "Only as a long-term liability",
      D: "As a capital asset with accumulated depreciation",
    },
    answer: "B",
    explanation: "ASC 842 eliminated the old operating lease off-balance-sheet treatment. Under ASC 842 (effective for public companies since 2019), lessees must record both an operating lease right-of-use (ROU) asset and a corresponding operating lease liability on the balance sheet for leases with terms exceeding 12 months. The ROU asset is amortized and the lease liability is reduced as payments are made, with straight-line expense recognition on the income statement for operating leases.",
  },
  {
    id: 845,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "When a company capitalizes a cost rather than expenses it immediately, the immediate effect on financial statements is:",
    choices: {
      A: "Lower assets, lower net income",
      B: "Higher assets, higher net income",
      C: "Lower assets, higher net income",
      D: "No effect on total assets",
    },
    answer: "B",
    explanation: "Capitalizing a cost means recording it as an asset rather than an immediate expense. This increases total assets (new asset created) and increases net income (because the full cost is not expensed immediately—only periodic depreciation/amortization reduces income over time). Over the life of the asset, total expense equals total cost; capitalization only shifts when the expense hits the income statement.",
  },
  {
    id: 846,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A company has goodwill of $500,000 on its balance sheet. Under GAAP (ASC 350), how is goodwill subsequently measured?",
    choices: {
      A: "Amortized straight-line over 40 years",
      B: "Tested for impairment annually (or when triggering events occur); not amortized",
      C: "Amortized over 15 years using MACRS",
      D: "Written off immediately in the year of acquisition",
    },
    answer: "B",
    explanation: "Under ASC 350, goodwill recognized in a business combination is NOT amortized under U.S. GAAP (for public entities). Instead, it is tested for impairment at least annually (or more frequently when triggering events indicate possible impairment). An impairment loss is recognized if the carrying amount of the reporting unit exceeds its fair value. Note: Private companies may elect to amortize goodwill straight-line under the Private Company Council (PCC) alternative. For tax purposes, goodwill is amortized over 15 years under §197.",
  },
  {
    id: 847,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The debt-to-equity ratio for a company with total liabilities of $800,000 and stockholders' equity of $400,000 is:",
    choices: {
      A: "0.5",
      B: "1.0",
      C: "2.0",
      D: "0.33",
    },
    answer: "C",
    explanation: "The debt-to-equity ratio = Total liabilities ÷ Stockholders' equity = $800,000 ÷ $400,000 = 2.0. This means the company has $2 of debt for every $1 of equity. A higher ratio indicates greater financial leverage and risk. Creditors generally prefer a lower ratio, while equity investors may benefit from leverage if returns on assets exceed the cost of debt.",
  },
  {
    id: 848,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under the percentage-of-completion method for long-term contracts (required by §460 for most construction contracts), gross profit is recognized based on:",
    choices: {
      A: "The ratio of costs incurred to date to total estimated contract costs",
      B: "The ratio of billings to date to total contract price",
      C: "Cash received during the period",
      D: "Completion of defined milestones in the contract",
    },
    answer: "A",
    explanation: "Under the cost-to-cost method of percentage-of-completion (required under §460 for long-term construction contracts), the percentage complete = costs incurred to date ÷ total estimated contract costs. Gross profit recognized = percentage complete × total estimated gross profit. If actual costs rise, the completion percentage and recognized profit change accordingly. §460 requires percentage-of-completion for most long-term contracts, with exceptions for certain small contractors.",
  },
  {
    id: 849,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under GAAP, which accounting change requires retrospective application (restatement of prior period financial statements)?",
    choices: {
      A: "Change in accounting estimate",
      B: "Correction of an error",
      C: "Change in depreciation method",
      D: "Change in useful life of an asset",
    },
    answer: "B",
    explanation: "Under ASC 250, correction of an error in previously issued financial statements requires retrospective restatement—all prior period statements presented must be restated. Changes in accounting principle (e.g., from LIFO to FIFO) also require retrospective application. Changes in accounting estimate (including changes in depreciation method or useful life under ASC 250-10-45-17) are treated prospectively—affecting only the current and future periods with no restatement required.",
  },
  {
    id: 850,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A company sells a product with a 2-year warranty. Estimated warranty costs are $50,000 annually. Under the accrual method, the company should:",
    choices: {
      A: "Expense warranty costs when paid",
      B: "Accrue the estimated $100,000 warranty liability at the time of sale",
      C: "Defer warranty revenue and recognize it ratably over 2 years",
      D: "Expense $50,000 at the end of year 1 and $50,000 at the end of year 2",
    },
    answer: "B",
    explanation: "Under the matching principle and accrual accounting, estimated warranty costs must be accrued at the time of sale (when the related revenue is recognized), not when warranty claims are made. The company records a warranty liability of $100,000 (2 years × $50,000) at the point of sale, with a corresponding warranty expense. As actual warranty costs are incurred, the liability is reduced. For tax purposes, only actual warranty costs paid are deductible (cash method) unless an election is made.",
  },
  {
    id: 851,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The gross profit margin for a retailer with net sales of $1,000,000, cost of goods sold of $600,000, and operating expenses of $200,000 is:",
    choices: {
      A: "20%",
      B: "40%",
      C: "60%",
      D: "80%",
    },
    answer: "B",
    explanation: "Gross profit margin = (Net sales − COGS) ÷ Net sales = ($1,000,000 − $600,000) ÷ $1,000,000 = $400,000 ÷ $1,000,000 = 40%. Operating expenses are not included in gross profit margin—they are used for the operating profit margin calculation. Operating margin = ($1,000,000 − $600,000 − $200,000) ÷ $1,000,000 = $200,000 ÷ $1,000,000 = 20%.",
  },
  {
    id: 852,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under GAAP, when is a contingent liability recorded on the balance sheet?",
    choices: {
      A: "When it is reasonably possible and can be estimated",
      B: "When it is probable and can be reasonably estimated",
      C: "When litigation has been filed against the company",
      D: "Only when the amount is certain",
    },
    answer: "B",
    explanation: "Under ASC 450-20 (Loss Contingencies), a loss contingency is accrued (recorded on the balance sheet) only when: (1) it is probable that a liability has been incurred, AND (2) the amount can be reasonably estimated. If only one condition is met (e.g., probable but not estimable, or estimable but only reasonably possible), disclosure is required but no accrual is made. 'Probable' means the future event is likely to occur; 'reasonably possible' means more than remote but less than likely.",
  },
  {
    id: 853,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "A company issues 1,000 shares of $1 par value common stock at $25 per share. The journal entry includes a credit to Common Stock for $1,000 and a credit to:",
    choices: {
      A: "Retained earnings of $24,000",
      B: "Additional paid-in capital of $24,000",
      C: "Treasury stock of $24,000",
      D: "Preferred stock of $24,000",
    },
    answer: "B",
    explanation: "When stock is issued above par value, the par value portion is credited to Common Stock (1,000 shares × $1 par = $1,000) and the excess above par is credited to Additional Paid-In Capital (APIC): 1,000 shares × ($25 − $1) = $24,000. Total proceeds of $25,000 increase cash. APIC represents capital contributed by shareholders in excess of par value and is a component of stockholders' equity.",
  },
  {
    id: 854,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "The LIFO reserve represents the difference between inventory valued at LIFO and inventory valued at FIFO. If the LIFO reserve increases during the period, what is the tax effect?",
    choices: {
      A: "Higher taxable income in the current period",
      B: "Lower taxable income in the current period (LIFO produces higher COGS during inflation)",
      C: "No tax effect; it is only a financial statement adjustment",
      D: "Deferred tax asset created",
    },
    answer: "B",
    explanation: "When a company uses LIFO during inflationary periods, the most recently purchased (higher-cost) items are expensed first as COGS, resulting in higher COGS and lower taxable income compared to FIFO. The LIFO reserve (FIFO inventory − LIFO inventory) increases as the price difference grows. An increasing LIFO reserve means LIFO COGS > FIFO COGS, producing lower taxable income and lower taxes currently. This is the primary reason companies elect LIFO—to defer taxes during inflation. The LIFO conformity rule (§472(c)) requires companies using LIFO for tax to use LIFO in their financial statements.",
  },
  {
    id: 855,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Accounts receivable turnover is calculated as:",
    choices: {
      A: "Net credit sales ÷ Average accounts receivable",
      B: "Total sales ÷ Ending accounts receivable",
      C: "Average accounts receivable ÷ Net credit sales",
      D: "Net income ÷ Average accounts receivable",
    },
    answer: "A",
    explanation: "Accounts receivable turnover = Net credit sales ÷ Average accounts receivable. It measures how many times the company collects its average receivables during a period. A higher turnover indicates faster collection. Average AR = (Beginning AR + Ending AR) ÷ 2. The days sales outstanding (DSO) = 365 ÷ AR turnover, representing the average number of days to collect receivables.",
  },
  {
    id: 856,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §446, the required method of accounting for a C corporation with average annual gross receipts exceeding $29 million (2024 threshold) is:",
    choices: {
      A: "The cash method",
      B: "The accrual method",
      C: "Either cash or accrual, at the taxpayer's election",
      D: "The hybrid method",
    },
    answer: "B",
    explanation: "Under §448(c), C corporations (other than farming businesses and certain personal service corporations) with average annual gross receipts exceeding the inflation-adjusted threshold ($29 million for 2024) are required to use the accrual method of accounting. Smaller C corporations and certain pass-through entities below the threshold may use the cash method. The threshold is adjusted for inflation under §448(c)(4). Personal service corporations may use the cash method regardless of gross receipts under certain conditions.",
  },
  {
    id: 857,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "A company uses straight-line depreciation for book purposes and MACRS for tax purposes. This creates a:",
    choices: {
      A: "Permanent difference",
      B: "Temporary difference",
      C: "No difference if useful lives are the same",
      D: "Extraordinary item on the income statement",
    },
    answer: "B",
    explanation: "The difference between book depreciation (straight-line) and tax depreciation (MACRS, which typically uses accelerated methods and shorter recovery periods) is a temporary difference under ASC 740. Over the asset's life, the total depreciation will be the same for both book and tax purposes—the difference is only in timing. This creates a deferred tax liability when tax depreciation exceeds book depreciation in early years and reverses in later years.",
  },
  {
    id: 858,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "For book purposes, a company records a $1,000,000 gain from the sale of a subsidiary. For tax purposes, the gain is not recognized due to a §338(h)(10) election. This creates a:",
    choices: {
      A: "Permanent difference—the book gain never affects taxable income",
      B: "Temporary difference—the gain will eventually be taxed",
      C: "Permanent difference only if the subsidiary is liquidated",
      D: "Deferred tax asset",
    },
    answer: "A",
    explanation: "Under a §338(h)(10) election, the deemed asset sale gain is recognized at the subsidiary level (stepped-up basis), and the actual stock sale gain at the parent level is not recognized. If the tax consequence is permanently eliminated (the parent's stock gain is never taxed because the subsidiary is treated as if it sold assets), the book-tax difference is a permanent difference—it creates no deferred tax. However, this analysis depends on specifics; in many cases, §338(h)(10) elections create temporary differences at the subsidiary level.",
  },
  {
    id: 859,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The inventory turnover ratio measures how many times inventory is sold and replaced during a period. It is calculated as:",
    choices: {
      A: "Net sales ÷ Ending inventory",
      B: "Cost of goods sold ÷ Average inventory",
      C: "Gross profit ÷ Average inventory",
      D: "Net income ÷ Ending inventory",
    },
    answer: "B",
    explanation: "Inventory turnover = Cost of goods sold ÷ Average inventory. Using COGS (rather than sales) in the numerator is more accurate because inventory is also measured at cost. Average inventory = (Beginning inventory + Ending inventory) ÷ 2. A higher turnover ratio generally indicates efficient inventory management. Days inventory outstanding (DIO) = 365 ÷ inventory turnover.",
  },
  {
    id: 860,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §481(a), when a taxpayer changes its accounting method (with IRS consent), the §481(a) adjustment represents:",
    choices: {
      A: "The tax rate change applied to deferred liabilities",
      B: "The cumulative effect of the accounting method change on prior years",
      C: "The current-year adjustment to match the new method",
      D: "The penalty for improper use of accounting methods",
    },
    answer: "B",
    explanation: "When a taxpayer obtains IRS consent to change an accounting method, the §481(a) adjustment accounts for the cumulative income or deduction that would have been different under the new method in prior years. A positive §481(a) adjustment (income) is generally spread over 4 years. A negative §481(a) adjustment (deduction) is generally taken entirely in the year of change. This prevents items from being permanently omitted or double-counted due to the method change.",
  },

  // ── DOMAIN 3: SPECIFIC TYPES OF BUSINESS ENTITIES ────────────────────────────
  {
    id: 861,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A limited liability company (LLC) with two members that has not made a check-the-box election is treated as what type of entity for federal tax purposes?",
    choices: {
      A: "C corporation",
      B: "S corporation",
      C: "Partnership",
      D: "Disregarded entity",
    },
    answer: "C",
    explanation: "Under the check-the-box regulations (Reg. §301.7701-3), a multi-member LLC that has not elected to be treated as a corporation is classified as a partnership by default. The members report their distributive share of income and loss on their individual returns. A single-member LLC defaults to disregarded entity. An LLC can elect to be treated as a corporation (C corp or, if eligible, S corp) by filing Form 8832.",
  },
  {
    id: 862,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "In a general partnership, each partner is liable for the debts of the partnership. Under the Uniform Partnership Act, a partner who pays a partnership debt that exceeds their pro-rata share has a right of:",
    choices: {
      A: "Subrogation only",
      B: "Contribution from other partners",
      C: "Indemnification from the partnership only",
      D: "No recourse against other partners",
    },
    answer: "B",
    explanation: "In a general partnership, each partner is jointly and severally liable for partnership obligations. If one partner pays more than their pro-rata share of partnership debts, they have a right of contribution against the other partners—the right to seek reimbursement from co-partners for their proportionate share. This concept is distinct from the partnership's obligation to indemnify partners for payments made on behalf of the partnership (right of indemnification).",
  },
  {
    id: 863,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "An S corporation shareholder who also works for the S corporation must receive a 'reasonable salary' subject to employment taxes. What is the primary IRS concern if no salary is paid?",
    choices: {
      A: "The shareholder may be reclassifying ordinary income as capital gains",
      B: "The S corporation may owe the accumulated earnings tax",
      C: "The shareholder may be avoiding FICA taxes by taking only distributions",
      D: "The S corporation would lose its S election",
    },
    answer: "C",
    explanation: "The IRS requires S corporation shareholder-employees to pay themselves a 'reasonable compensation' wage subject to FICA taxes (Social Security and Medicare). If the shareholder takes only distributions (which are not subject to FICA), the IRS may recharacterize distributions as wages, imposing FICA taxes, penalties, and interest. This is a common audit issue for S corporations—the IRS scrutinizes situations where shareholder-employees receive little or no salary but large distributions.",
  },
  {
    id: 864,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §704(c), when a partner contributes property with a built-in gain to a partnership, the built-in gain must be allocated to:",
    choices: {
      A: "All partners equally",
      B: "All partners in their profit/loss sharing ratios",
      C: "The contributing partner",
      D: "The non-contributing partners",
    },
    answer: "C",
    explanation: "§704(c) requires that when appreciated (or depreciated) property is contributed to a partnership, the built-in gain (or loss) that existed at contribution must be allocated back to the contributing partner when recognized. This prevents the contributing partner from shifting pre-contribution gain to other partners through the partnership. The 'traditional method,' 'traditional method with curative allocations,' or 'remedial method' may be used to make §704(c) allocations of tax items.",
  },
  {
    id: 865,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A real estate investment trust (REIT) must distribute at least what percentage of its taxable income to shareholders to avoid entity-level taxation on that income?",
    choices: {
      A: "75%",
      B: "85%",
      C: "90%",
      D: "95%",
    },
    answer: "C",
    explanation: "Under §857(a)(1), a REIT must distribute at least 90% of its REIT taxable income (excluding net capital gains) each year to its shareholders to qualify for the dividends-paid deduction, which effectively eliminates entity-level tax on distributed income. If a REIT distributes less than 100% of income, it pays corporate tax on the undistributed portion. REITs that fail to distribute 90% are subject to a 4% excise tax on the undistributed amount.",
  },
  {
    id: 866,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "The at-risk rules of §465 apply to partnerships. A limited partner's at-risk amount includes their share of partnership nonrecourse liabilities that constitute 'qualified nonrecourse financing.' What qualifies as qualified nonrecourse financing?",
    choices: {
      A: "Any loan from a bank secured by partnership assets",
      B: "Loans secured by real property where the lender is a commercial bank (or government) and the loan is not from a related party",
      C: "All nonrecourse debt of the partnership",
      D: "Loans personally guaranteed by any partner",
    },
    answer: "B",
    explanation: "§465(b)(6) defines 'qualified nonrecourse financing' as financing that is: (1) secured by real property used in an activity of holding real property, (2) provided by a person who is 'actively and regularly engaged in the business of lending money' (e.g., a commercial bank, savings institution, or a federal, state, or local government), and (3) not convertible or provided by the seller. Qualified nonrecourse financing is included in a limited partner's at-risk amount despite no personal liability.",
  },
  {
    id: 867,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A publicly traded partnership (PTP) is generally taxed as a corporation UNLESS at least what percentage of its gross income consists of qualifying income?",
    choices: {
      A: "75%",
      B: "80%",
      C: "90%",
      D: "95%",
    },
    answer: "C",
    explanation: "Under §7704, a publicly traded partnership (one with interests traded on an established securities market) is treated as a corporation for tax purposes. However, if 90% or more of the PTP's gross income consists of qualifying income (natural resources income, real property rents and gains, interest and dividends, certain income from commodity and futures trading), the PTP retains partnership tax treatment and avoids corporate-level tax. Most energy MLPs (master limited partnerships) qualify under this exception.",
  },
  {
    id: 868,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "When a partnership makes a §754 election and a partner's interest is transferred, the partnership makes a §743(b) adjustment. This adjustment:",
    choices: {
      A: "Adjusts the partnership's common basis in all assets",
      B: "Creates a special basis adjustment allocated only to the transferee partner",
      C: "Requires revaluation of all partnership assets at FMV",
      D: "Eliminates the transferee's share of unrealized appreciation",
    },
    answer: "B",
    explanation: "When a §754 election is in effect and a partnership interest is transferred by sale or exchange, §743(b) requires a special basis adjustment. This adjustment is allocated only to the transferee (buying) partner—it adjusts the transferee's share of the inside basis in partnership assets to match the outside basis paid for the interest. Other partners are unaffected. The §743(b) adjustment eliminates the difference between the transferee's cost basis and their share of the partnership's inside basis.",
  },
  {
    id: 869,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A regulated investment company (RIC, or mutual fund) avoids entity-level tax by distributing at least what percentage of its investment income?",
    choices: {
      A: "85%",
      B: "90%",
      C: "95%",
      D: "100%",
    },
    answer: "B",
    explanation: "Under §852, a RIC (mutual fund, ETF) is allowed a dividends-paid deduction for dividends paid to shareholders if it distributes at least 90% of its investment company taxable income (ordinary income) and 90% of its net tax-exempt interest income. If distributions fall below 90%, the RIC is subject to a 4% excise tax on undistributed amounts. Most RICs distribute 100% to avoid all entity-level tax, but the minimum requirement is 90%.",
  },
  {
    id: 870,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §1361(c)(1), an S corporation may have a trust as a shareholder only if the trust is one of the following EXCEPT:",
    choices: {
      A: "A grantor trust",
      B: "A qualified Subchapter S trust (QSST)",
      C: "An electing small business trust (ESBT)",
      D: "A complex trust where the trustee has discretion over distributions",
    },
    answer: "D",
    explanation: "§1361(c)(2) lists the types of trusts eligible to be S corporation shareholders: grantor trusts, trusts that were former grantor trusts (for 2 years after grantor's death), testamentary trusts (for 2 years after stock is transferred), QSSTs (one current income beneficiary, all income distributed), ESBTs (can have multiple beneficiaries, pays highest marginal rate), voting trusts, and IRAs/Roth IRAs. A complex discretionary trust that does not qualify as one of these permitted trust types is not an eligible S corporation shareholder.",
  },
  {
    id: 871,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A limited partnership has a general partner and limited partners. Under §469, which partner's interest is always considered passive (regardless of participation level)?",
    choices: {
      A: "The general partner",
      B: "The limited partners",
      C: "Both the general and limited partners",
      D: "Neither; all partners can materially participate",
    },
    answer: "B",
    explanation: "Under §469(h)(2), a limited partner's interest in a limited partnership is treated as passive per se—limited partners cannot materially participate in the partnership activity for purposes of the passive activity rules, unless they also hold a general partner interest. This is because limited partners, by definition, are legally prohibited from participating in management. A general partner's interest is evaluated using the standard material participation tests.",
  },
  {
    id: 872,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §736, payments from a partnership to a retiring partner for goodwill are treated as:",
    choices: {
      A: "§736(a) payments (ordinary income to the retiring partner) if the partnership agreement does not specifically provide for goodwill",
      B: "§736(b) payments (capital gain to the retiring partner) in all cases",
      C: "§736(a) payments deductible by the remaining partners regardless of the agreement",
      D: "Non-taxable return of capital",
    },
    answer: "A",
    explanation: "Under §736, payments to a retiring partner are split: §736(b) payments are for the partner's interest in partnership property (capital gain treatment for retiring partner, non-deductible for remaining partners). §736(a) payments are essentially distributions of partnership income or guaranteed payments. Crucially, under §736(b)(3), payments for partnership goodwill are treated as §736(a) payments (ordinary income) for service partnerships UNLESS the partnership agreement specifically provides for a payment for goodwill. If the agreement provides for goodwill, it's §736(b) (capital gain).",
  },
  {
    id: 873,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "An S corporation with no prior C corporation history distributes $50,000 cash to a shareholder whose stock basis is $30,000. What is the tax result?",
    choices: {
      A: "$50,000 taxable dividend",
      B: "$30,000 tax-free return of capital, $20,000 capital gain",
      C: "$50,000 capital gain",
      D: "$20,000 ordinary income",
    },
    answer: "B",
    explanation: "S corporation distributions are generally tax-free to the extent of the shareholder's stock basis (unlike C corporation dividends). Distribution order for an S corp with no accumulated E&P: (1) reduces stock basis tax-free, (2) excess over basis is capital gain. The shareholder's basis of $30,000 absorbs the first $30,000 of the $50,000 distribution tax-free (basis reduced to zero). The remaining $20,000 is treated as gain from the sale of stock—capital gain. AAA (accumulated adjustments account) tracks S corp distributions.",
  },
  {
    id: 874,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "A new corporation issues 100 shares of stock—80 shares for cash of $80,000 and 20 shares for services valued at $20,000. The person providing services for stock is part of the §351 transferor group. Under §351, which statement is correct?",
    choices: {
      A: "The service provider recognizes $20,000 ordinary income; the cash contributor recognizes no gain",
      B: "Both the service provider and cash contributor have tax-free exchanges under §351",
      C: "The cash contributor must recognize gain equal to the service provider's income",
      D: "§351 does not apply because services were exchanged for stock",
    },
    answer: "A",
    explanation: "Under §351 and Reg. §1.351-1(a)(1)(ii), services are not 'property' for purposes of §351. A person who receives stock solely for services does not count as a §351 transferor and must recognize ordinary income equal to the FMV of stock received ($20,000). However, the service recipient's inclusion still counts toward the 80% control test for the remaining property transferors. The cash contributor ($80,000 for 80 shares) still qualifies for §351 non-recognition as long as the control test is met.",
  },
  {
    id: 875,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A C corporation is incorporated in Delaware but operates entirely in California. For federal tax purposes, where is the corporation considered organized?",
    choices: {
      A: "California, where it operates",
      B: "Delaware, where it is incorporated",
      C: "Both states equally",
      D: "The state with the highest tax rate",
    },
    answer: "B",
    explanation: "Under §7701(a)(4), the term 'domestic' means created or organized in the United States or under the law of the United States or any state. The state of incorporation determines where a corporation is organized for federal tax purposes—not where it operates. A corporation incorporated in Delaware but operating in California is a Delaware corporation for federal tax purposes. State tax nexus rules determine California filing obligations separately.",
  },
  {
    id: 876,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §708, a partnership is considered to have terminated if within a 12-month period there is a sale or exchange of how much of the total interest in partnership capital and profits?",
    choices: {
      A: "More than 25%",
      B: "More than 50%",
      C: "More than 75%",
      D: "100%",
    },
    answer: "B",
    explanation: "Under §708(b)(1)(B) (pre-TCJA law), a partnership was treated as terminated if within any 12-month period, there was a sale or exchange of 50% or more of the total interest in partnership capital AND profits. However, TCJA 2017 repealed this technical termination rule for tax years beginning after December 31, 2017. Under current law, a partnership only terminates when it ceases to do business or when its operations cause it to have no more than one partner. The historical 50% rule is still frequently tested.",
  },
  {
    id: 877,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Which of the following entities is NOT subject to the self-employment tax on its net income for its owner-operators?",
    choices: {
      A: "Sole proprietorship",
      B: "General partnership",
      C: "S corporation",
      D: "Single-member LLC (disregarded entity)",
    },
    answer: "C",
    explanation: "S corporation shareholders are NOT subject to self-employment tax on their distributive share of S corporation income. Instead, shareholder-employees pay FICA taxes only on wages/salary received. This is a key tax advantage of S corps—distributions are not subject to SE tax. Sole proprietors, general partners, and single-member LLC owners (treated as sole proprietors) are all subject to self-employment tax on net earnings from self-employment.",
  },
  {
    id: 878,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "An estate operates a farming business for 18 months after the decedent's death. Under §642(h), losses and deductions in excess of estate income that cannot be used by the estate are:",
    choices: {
      A: "Lost permanently",
      B: "Carried back 2 years by the estate",
      C: "Passed through to beneficiaries in the final year of the estate",
      D: "Carried forward indefinitely by the estate",
    },
    answer: "C",
    explanation: "Under §642(h), when an estate or complex trust terminates, any unused NOL carryovers and unused deductions in excess of gross income for the final year are allowed as deductions to the beneficiaries succeeding to the property of the estate or trust. These 'excess deductions on termination' can be used by beneficiaries in the year the estate terminates. This prevents loss of tax benefits when the estate cannot use all its deductions due to insufficient income.",
  },
  {
    id: 879,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A family limited partnership (FLP) is commonly used for estate planning. Which of the following is a legitimate tax benefit of a properly structured FLP?",
    choices: {
      A: "Income from FLP assets is tax-exempt",
      B: "Partnership interests can be gifted at a valuation discount for lack of marketability and control",
      C: "General partners pay no self-employment tax",
      D: "FLP assets are excluded from the gross estate automatically",
    },
    answer: "B",
    explanation: "A key estate planning benefit of an FLP is the valuation discount. When limited partnership interests are gifted, their fair market value may be reduced by discounts for lack of marketability (interests in non-publicly traded entities) and lack of control (minority interests in a partnership). These discounts (often 15–40%) reduce the taxable gift value, allowing more wealth to transfer at lower gift tax cost. However, the IRS scrutinizes FLPs for economic substance and proper non-tax business purposes.",
  },
  {
    id: 880,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §1363(b), an S corporation computes its taxable income in the same manner as an individual, with modifications. Which of the following items is NOT separately stated on the S corporation's Schedule K?",
    choices: {
      A: "Charitable contributions",
      B: "§1231 gains and losses",
      C: "Officers' salaries",
      D: "Net long-term capital gains",
    },
    answer: "C",
    explanation: "S corporation items that could affect a shareholder's tax differently depending on their specific situation must be separately stated on Schedule K and passed through to shareholders via Schedule K-1. These include: charitable contributions, §1231 gains/losses, capital gains/losses (separated by holding period), investment income/expense, credits, and foreign taxes. Officers' salaries (wages paid to shareholder-employees) are operating expenses deducted at the entity level in computing non-separately stated ordinary income—they are NOT separately stated items on Schedule K.",
  },

  // ── CROSS-DOMAIN ─────────────────────────────────────────────────────────────
  {
    id: 881,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A C corporation converts to an S corporation. The §1374 built-in gains tax applies to net recognized built-in gains. The tax is imposed at the highest corporate tax rate. What is that rate for 2024?",
    choices: {
      A: "28%",
      B: "35%",
      C: "21%",
      D: "20%",
    },
    answer: "C",
    explanation: "Under §1374(b)(1), the built-in gains tax is imposed at the highest rate of tax specified in §11(b), which is the corporate tax rate. Since TCJA 2017, the corporate tax rate is a flat 21%. Therefore, the §1374 BIG tax rate is 21%. This tax is paid at the S corporation level (not passed through to shareholders), and shareholders then receive a corresponding basis increase for the tax paid, reducing their potential double taxation.",
  },
  {
    id: 882,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A sole proprietor sells her business for $500,000. The assets include: inventory ($50,000 basis, $80,000 FMV), equipment ($100,000 basis, $150,000 FMV with $60,000 depreciation taken), and goodwill ($0 basis, $270,000 FMV). Which statement correctly describes the tax treatment?",
    choices: {
      A: "All gain is capital gain",
      B: "Inventory gain is ordinary; equipment gain up to depreciation is ordinary (§1245 recapture); remaining equipment gain and goodwill gain are §1231/capital",
      C: "All gain is ordinary income",
      D: "Goodwill is excluded from taxation as an intangible",
    },
    answer: "B",
    explanation: "In an asset sale, each asset is treated separately: (1) Inventory: $30,000 gain is ordinary income. (2) Equipment: $60,000 gain equals prior depreciation → all $50,000 gain (FMV $150K − basis $100K = $50K gain; depreciation of $60K > gain of $50K) is §1245 ordinary recapture. (3) Goodwill: the $270,000 gain is §1231 gain, which if net positive is taxed as long-term capital gain (or §1245 recapture for §197 amortized goodwill). Self-created goodwill sold by a sole proprietor is capital gain; purchased goodwill amortized under §197 is §1245 recapture.",
  },
  {
    id: 883,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "For both individuals and corporations, the general rule for deducting business bad debts requires the taxpayer to use the:",
    choices: {
      A: "Reserve method (allowance for doubtful accounts)",
      B: "Specific charge-off method",
      C: "Percentage-of-sales method",
      D: "Direct write-off method only for amounts over $500",
    },
    answer: "B",
    explanation: "For federal income tax purposes, §166 requires the specific charge-off (direct write-off) method for business bad debts—the debt must be specifically identified as worthless and charged off in the year it becomes worthless. The reserve (allowance) method used for GAAP book purposes is NOT allowed for tax purposes (with the exception of certain financial institutions). This creates a book-tax difference: GAAP expense is recorded when the allowance is increased, but tax deduction is allowed only when specific debts are written off.",
  },
  {
    id: 884,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A pass-through entity (S corporation or partnership) and its owners must consider multiple loss limitation rules. In what order are these limitations applied?",
    choices: {
      A: "Passive activity → at-risk → basis",
      B: "Basis → at-risk → passive activity",
      C: "At-risk → basis → passive activity",
      D: "Passive activity → basis → at-risk",
    },
    answer: "B",
    explanation: "The loss limitation rules for pass-through entity owners must be applied in a specific order: (1) Basis limitation (§704(d) for partnerships, §1366(d) for S corps)—losses cannot exceed the owner's basis in the entity, (2) At-risk limitation (§465)—losses cannot exceed the amount the taxpayer has at risk in the activity, (3) Passive activity limitation (§469)—losses from passive activities can only offset passive income. Each successive limitation applies to losses that survive the prior limitation.",
  },
  {
    id: 885,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "Which of the following statements about the §1031 like-kind exchange rules post-TCJA is correct?",
    choices: {
      A: "§1031 applies to both real and personal property",
      B: "§1031 applies only to real property; personal property exchanges are fully taxable after 2017",
      C: "§1031 applies only to personal property used in a business",
      D: "§1031 still applies to personal property if the exchange is simultaneous",
    },
    answer: "B",
    explanation: "The TCJA (effective for exchanges completed after December 31, 2017) restricted §1031 like-kind exchanges to real property only. Prior law allowed §1031 exchanges of both real and personal property. Under current law, exchanges of personal property (equipment, vehicles, artwork, collectibles, etc.) are fully taxable. Only real property (land and buildings) used in a trade or business or held for investment qualifies for §1031 deferral.",
  },
  {
    id: 886,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "Both C corporations and individuals face the net investment income tax (NIIT). Which statement is correct?",
    choices: {
      A: "C corporations pay 3.8% NIIT on net investment income",
      B: "Only individuals, trusts, and estates pay the 3.8% NIIT",
      C: "S corporations pay NIIT directly on investment income",
      D: "All business entities pay NIIT on passive investment income",
    },
    answer: "B",
    explanation: "The Net Investment Income Tax (NIIT) under §1411 applies only to individuals, trusts, and estates—NOT to C corporations, S corporations, or partnerships. For individuals, the 3.8% NIIT applies to the lesser of net investment income or the excess of MAGI over the threshold ($250,000 MFJ, $200,000 single for 2024). C corporations pay regular corporate income tax on investment income at 21%. S corporation shareholders may owe NIIT on their share of passive S corporation income.",
  },
  {
    id: 887,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "The tax treatment of a payment for a noncompete agreement entered into in connection with the purchase of a business is:",
    choices: {
      A: "Ordinary income to the seller; currently deductible by the buyer",
      B: "Capital gain to the seller; amortizable over 15 years by the buyer under §197",
      C: "Ordinary income to the seller; amortizable over 15 years by the buyer under §197",
      D: "Tax-free to the seller; amortizable over 5 years by the buyer",
    },
    answer: "C",
    explanation: "Under §1253 and IRS guidance, a covenant not to compete received in connection with a business sale is treated as ordinary income to the seller (not capital gain) because it represents compensation for the seller's agreement to refrain from competing. For the buyer, the cost allocated to the noncompete agreement is a §197 intangible amortized ratably over 15 years (180 months). This creates an asymmetric tax result: ordinary income to seller, but long-term amortization for the buyer.",
  },
  {
    id: 888,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "Under the tax benefit rule, a taxpayer who recovers an amount previously deducted must include the recovery in income, but only to the extent the prior deduction provided a tax benefit. If a calendar-year cash-basis sole proprietor deducted $10,000 in state income taxes in 2023 (which reduced federal taxes by $2,200) and receives a $3,000 state refund in 2024, how much must be included in 2024 federal income?",
    choices: {
      A: "$3,000",
      B: "$2,200",
      C: "$800",
      D: "$0",
    },
    answer: "A",
    explanation: "Under the tax benefit rule and §111, a recovery is included in income to the extent the prior deduction reduced tax. Since the $10,000 state tax deduction did provide a tax benefit (it reduced federal tax by $2,200 and contributed to additional itemized deductions), the question is whether the entire $3,000 refund provided a tax benefit. Since the taxpayer itemized and the $10,000 deduction exceeded the standard deduction contribution, all $3,000 of the deduction provided a tax benefit, so all $3,000 is includible in 2024 income. (If the standard deduction had applied, the benefit would be limited.)",
  },
  {
    id: 889,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A business pays for a 3-year property and casualty insurance policy on January 1, 2024. Under the cash method, how should this prepaid insurance be treated?",
    choices: {
      A: "Fully deductible in 2024 when paid",
      B: "Deducted ratably over 3 years (2024, 2025, 2026)",
      C: "Deductible in 2024 only to the extent of one year's premium",
      D: "Capitalized and amortized over 36 months",
    },
    answer: "B",
    explanation: "Under the 12-month rule of Reg. §1.263(a)-4(f), a cash-method taxpayer can deduct a prepaid expense in the year of payment only if the right or benefit does not extend beyond the earlier of 12 months after the date the right begins, or the end of the tax year following the year of payment. A 3-year insurance policy creates a right extending beyond 12 months, so the 12-month rule does not apply. The prepaid insurance must be capitalized and deducted ratably over the 3-year coverage period (approximately 1/3 per year).",
  },
  {
    id: 890,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "When a business owner transfers appreciated property to a corporation in exchange for stock and notes in a §351 transaction, the notes received constitute 'boot.' If the realized gain is $100,000 and the FMV of the notes received is $30,000, how much gain is recognized?",
    choices: {
      A: "$0",
      B: "$30,000",
      C: "$100,000",
      D: "$70,000",
    },
    answer: "B",
    explanation: "Under §351(b), when property is transferred to a corporation in exchange for stock plus boot (cash or property other than stock), gain is recognized to the extent of the boot received. The recognized gain equals the lesser of realized gain ($100,000) or boot received ($30,000). Therefore, $30,000 of gain is recognized. The character of the gain (ordinary or capital) depends on the character of the transferred property. Loss is never recognized in a §351 exchange, even with boot.",
  },
  {
    id: 891,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "For employment tax purposes, which workers are classified as 'statutory employees' and have their employer withhold Social Security and Medicare (FICA) taxes even though they may otherwise be independent contractors?",
    choices: {
      A: "All independent contractors who earn more than $600",
      B: "Certain categories including full-time life insurance salespersons, certain traveling salespersons, and homeworkers",
      C: "Any worker who signs a contract agreeing to statutory employee status",
      D: "Sole proprietors with no employees",
    },
    answer: "B",
    explanation: "Statutory employees are a specific IRS category under §3121(d)(3): workers who are treated as employees for FICA purposes even if they might be independent contractors under common law. The four categories are: (1) agents or commission drivers, (2) full-time life insurance salespersons, (3) homeworkers (piece-rate workers at home under employer specifications), and (4) full-time traveling or city salespersons. These workers have FICA withheld by the employer but typically receive a W-2 with box 13 'statutory employee' checked.",
  },
  {
    id: 892,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "Under §1091, wash sale rules disallow a loss on the sale of stock or securities if the taxpayer purchases 'substantially identical' securities within 30 days before or after the sale. Do the wash sale rules apply to businesses?",
    choices: {
      A: "Yes, wash sale rules apply to all taxpayers including corporations and partnerships",
      B: "No, wash sale rules apply only to individual taxpayers",
      C: "Yes, but only to C corporations; not to pass-through entities",
      D: "No, corporations use the straddle rules instead",
    },
    answer: "A",
    explanation: "The wash sale rules under §1091 apply to all taxpayers—individuals, C corporations, S corporations, partnerships, estates, and trusts. Any taxpayer who sells or trades stock or securities at a loss and within 30 days before or after the sale acquires (or enters into a contract to acquire) substantially identical stock or securities has the loss disallowed. The disallowed loss adjusts the basis of the newly acquired securities. Corporations engaged in securities trading must comply with §1091.",
  },
  {
    id: 893,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "Which of the following business expenses is subject to the 50% limitation on deductibility?",
    choices: {
      A: "Office supplies purchased for employee use",
      B: "Business meals with clients where business is discussed",
      C: "Advertising costs for a product launch",
      D: "Uniforms required for employees",
    },
    answer: "B",
    explanation: "Under §274(n), the deduction for business meals (food and beverages) is generally limited to 50% of the otherwise allowable expense. This applies to meals with clients, customers, employees at business meetings, and meals while traveling for business. The 50% limitation does not apply to office supplies, advertising costs, or employee uniforms. Note: The 100% deduction for meals provided by restaurants (TCJA provision) expired after December 31, 2022, so the 50% limit is restored for 2023 and beyond.",
  },
  {
    id: 894,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A tax practitioner has a client who is an officer of a C corporation. The client wants to take a salary of $2 million. The IRS may challenge the salary deduction if it exceeds:",
    choices: {
      A: "$1 million, because §162(m) limits deductible compensation for covered employees of public companies to $1 million",
      B: "The amount that similarly situated executives earn in the same industry",
      C: "The amount specifically approved by the board of directors",
      D: "The amount the corporation can afford based on cash flow",
    },
    answer: "A",
    explanation: "§162(m) disallows a deduction by a publicly held corporation for compensation paid to any 'covered employee' exceeding $1 million per year. Covered employees include the CEO, CFO, and the three next highest compensated executive officers. Post-TCJA, the $1 million cap applies to all compensation (the prior performance-based exception was eliminated). For private companies, the reasonableness standard under §162(a)(1) applies—compensation must be 'reasonable' and for services actually rendered, but there is no bright-line dollar limit.",
  },
  {
    id: 895,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "The IRS requires businesses to file information returns (Form 1099-NEC) for payments to non-corporate service providers. The reporting threshold for 2024 is payments of:",
    choices: {
      A: "$500 or more",
      B: "$600 or more",
      C: "$1,000 or more",
      D: "$2,500 or more",
    },
    answer: "B",
    explanation: "Under §6041 and §6041A, businesses must file Form 1099-NEC to report payments of $600 or more made to non-employee service providers (independent contractors, attorneys, etc.) during the calendar year. This threshold has been $600 since the 1950s. Payments to corporations are generally exempt from 1099-NEC reporting (though certain payments to attorneys and health care providers require reporting regardless of corporate status). Failure to file triggers penalties under §6721.",
  },
  {
    id: 896,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A C corporation has book income of $1,000,000 and taxable income of $600,000. The book-tax difference of $400,000 consists entirely of temporary differences. Under ASC 740, the company records:",
    choices: {
      A: "A current tax expense of $126,000 and no deferred taxes",
      B: "A current tax expense of $126,000 and a deferred tax liability of $84,000",
      C: "A total income tax expense of $210,000 ($126,000 current + $84,000 deferred)",
      D: "A deferred tax asset of $84,000",
    },
    answer: "C",
    explanation: "Under ASC 740, total income tax expense has two components: (1) Current tax expense = taxable income × tax rate = $600,000 × 21% = $126,000 (taxes owed now). (2) Deferred tax expense = temporary differences × tax rate = $400,000 × 21% = $84,000 (deferred tax liability for items taxable later). Total income tax expense = $126,000 + $84,000 = $210,000, representing 21% of pre-tax book income ($1,000,000 × 21%). The deferred tax liability will reverse when temporary differences reverse.",
  },
  {
    id: 897,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "An S corporation passes through a $40,000 long-term capital gain to its individual shareholder. On the shareholder's individual return, this gain is taxed at:",
    choices: {
      A: "Ordinary income rates",
      B: "The 21% corporate rate",
      C: "0%, 15%, or 20% preferential capital gains rates, depending on the shareholder's income",
      D: "The flat 12% S corporation rate",
    },
    answer: "C",
    explanation: "S corporation items retain their character as they pass through to shareholders. A long-term capital gain from the S corporation is reported as long-term capital gain on the individual shareholder's return and taxed at the preferential rates of 0%, 15%, or 20% depending on the shareholder's taxable income (plus 3.8% NIIT if applicable). The shareholder's long-term capital gain rate thresholds for 2024 are: 0% for income up to $47,025 (single) / $94,050 (MFJ), 15% for income up to $518,900 (single) / $583,750 (MFJ), and 20% above those thresholds.",
  },
  {
    id: 898,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A business taxpayer faces a tax deficiency assessment. The taxpayer believes the IRS is wrong but cannot afford to pay the tax first. Which court allows the taxpayer to litigate WITHOUT first paying the tax?",
    choices: {
      A: "U.S. District Court",
      B: "U.S. Court of Federal Claims",
      C: "U.S. Tax Court",
      D: "U.S. Bankruptcy Court",
    },
    answer: "C",
    explanation: "The U.S. Tax Court is the only federal court where a taxpayer can litigate a tax deficiency WITHOUT first paying the assessed tax (pre-payment jurisdiction). The taxpayer must file a petition within 90 days (150 days for foreign addresses) of receiving the Notice of Deficiency (90-day letter). The U.S. District Court and U.S. Court of Federal Claims require the taxpayer to pay the tax first and then sue for a refund. The Tax Court has a specialized Small Tax Case division for amounts under $50,000.",
  },
  {
    id: 899,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "The statute of limitations for the IRS to assess additional tax for a business taxpayer who filed a timely, complete return is generally:",
    choices: {
      A: "2 years from the date of filing",
      B: "3 years from the later of the return's due date or actual filing date",
      C: "5 years from the date the return was filed",
      D: "Unlimited for all business returns",
    },
    answer: "B",
    explanation: "Under §6501(a), the general statute of limitations for IRS assessment is 3 years from the later of: (1) the date the return was filed, or (2) the return's due date (April 15 for calendar-year individuals; 15th day of the 4th month for corporations). Special rules extend the SOL: to 6 years if gross income is understated by more than 25%, and indefinitely if a fraudulent return is filed or no return is filed. The 3-year period applies to timely-filed returns with no substantial understatement.",
  },
  {
    id: 900,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A qualified opportunity zone (QOZ) investment allows deferral of capital gain invested in a Qualified Opportunity Fund (QOF). Under the TCJA, which of the following benefits applies to a QOF investment held for at least 10 years?",
    choices: {
      A: "The original deferred gain is permanently excluded from income",
      B: "The appreciation on the QOF investment itself is excluded from income when the QOF is sold",
      C: "Both the original gain and QOF appreciation are excluded from income",
      D: "The deferred gain is taxed at a 50% reduced rate",
    },
    answer: "B",
    explanation: "Under §1400Z-2, investing capital gains in a QOF provides three potential benefits: (1) Deferral of the original capital gain until the earlier of the date the QOF interest is sold or December 31, 2026 (whichever is earlier), (2) Step-up in basis of 10% (if held 5+ years before 2026) on the deferred gain, and (3) Exclusion of appreciation: if the QOF investment is held for at least 10 years, the taxpayer may elect to exclude ALL post-acquisition appreciation in the QOF investment from gross income. The original deferred gain (from option 1) is still taxable—it's only the new appreciation that is excluded after 10 years.",
  },
];
