import type { Question } from "./questions";

export const questions3: Question[] = [
  // ── DOMAIN 1: Business Entities (Q201–Q230) ──────────────────────────────
  {
    id: 201,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "For a §351 tax-free transfer to a corporation to qualify, the transferors must control the corporation immediately after the exchange. 'Control' means owning at least what percentage of both voting stock and all other classes of stock?",
    choices: { A: "50%", B: "66⅔%", C: "80%", D: "90%" },
    answer: "C",
    explanation: "§368(c) defines control as ownership of stock possessing at least 80% of the total combined voting power and at least 80% of all other classes of stock. This 80% threshold must be met immediately after the §351 exchange.",
  },
  {
    id: 202,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under the check-the-box regulations, a single-member LLC owned by a corporation is classified as what by default?",
    choices: { A: "A C corporation", B: "An S corporation", C: "A disregarded entity (branch)", D: "A partnership" },
    answer: "C",
    explanation: "Under Reg. §301.7701-3, a single-member LLC is a disregarded entity by default, treated as a branch of its owner. This applies regardless of whether the owner is an individual or a corporation. It may elect to be taxed as a corporation.",
  },
  {
    id: 203,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A partnership distributes property with a §704(b) book value of $60,000 and an adjusted basis to the partnership of $30,000 to a partner whose outside basis is $50,000. What is the partner's basis in the distributed property (non-liquidating distribution)?",
    choices: { A: "$30,000", B: "$50,000", C: "$60,000", D: "$20,000" },
    answer: "A",
    explanation: "Under §732(a), in a non-liquidating distribution, the partner takes the lesser of (1) the partnership's adjusted basis in the property ($30,000) or (2) the partner's outside basis reduced by any cash received. No cash was received, so the basis is $30,000. The book value is irrelevant for tax basis purposes.",
  },
  {
    id: 204,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under the §708 partnership termination rules (post-2018 TCJA), a partnership terminates when:",
    choices: {
      A: "50% or more of total interest in capital and profits is sold within 12 months",
      B: "No part of any business is carried on by any of its partners",
      C: "The partnership has only one partner remaining",
      D: "Both B and C",
    },
    answer: "D",
    explanation: "Post-TCJA (2018), §708 was simplified. A partnership terminates only when (1) no part of any business continues, or (2) only one partner remains (which converts it to a sole proprietorship). The old 50%-in-12-months technical termination rule was repealed.",
  },
  {
    id: 205,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "§737 requires a partner to recognize gain when the partner receives a distribution of property within 7 years of contributing appreciated property. The gain recognized equals:",
    choices: {
      A: "The FMV of distributed property minus the partner's outside basis",
      B: "The lesser of the partner's 'net precontribution gain' or the excess of FMV of distributed property over outside basis",
      C: "The excess of FMV distributed over the partnership's inside basis",
      D: "100% of the precontribution gain on the original contributed property",
    },
    answer: "B",
    explanation: "§737 gain equals the lesser of (1) the partner's net precontribution gain (unrealized appreciation on contributed property still held by the partnership) or (2) the excess of FMV of the distributed property over the partner's outside basis before the distribution. This prevents avoidance of §704(c) through distribution.",
  },
  {
    id: 206,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §736, liquidating payments to a retiring general partner of a service partnership are classified as §736(a) income payments (not capital) for amounts attributable to:",
    choices: {
      A: "Unrealized receivables and goodwill (if not stated in the agreement)",
      B: "Capital assets and §1231 property only",
      C: "The partner's share of cash and marketable securities",
      D: "Depreciation recapture under §1245",
    },
    answer: "A",
    explanation: "§736(a) applies to payments for unrealized receivables and, for service partnerships (capital not a material income-producing factor), goodwill not provided for in the agreement. These are ordinary income to the retiring partner and deductible by the partnership. §736(b) covers all other payments (capital gain/loss to the retiring partner, not deductible by the partnership).",
  },
  {
    id: 207,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A brother-sister controlled group requires common ownership of two or more corporations by five or fewer persons (individuals, trusts, or estates). The ownership threshold for the group is:",
    choices: {
      A: "More than 50% of total combined voting power and more than 50% of total value",
      B: "At least 80% of total combined voting power",
      C: "More than 50% of total combined voting power or total value, counting only identical ownership",
      D: "100% common ownership by one owner",
    },
    answer: "C",
    explanation: "Under §1563(a)(2), a brother-sister controlled group exists when five or fewer persons own more than 50% of total combined voting power or total value of each corporation, counting only the smallest ownership interest each person holds in any member corporation (the 'identical ownership' test). An 80% common-parent test applies to parent-subsidiary groups under §1563(a)(1).",
  },
  {
    id: 208,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "An S corporation shareholder lends the corporation $20,000. The corporation passes through a $25,000 loss. The shareholder has $10,000 stock basis and $20,000 debt basis. How much loss can the shareholder deduct?",
    choices: { A: "$10,000", B: "$20,000", C: "$25,000", D: "$30,000" },
    answer: "C",
    explanation: "S corp losses are limited by the shareholder's stock basis plus debt basis under §1366(d). Stock basis ($10,000) + debt basis ($20,000) = $30,000 combined basis. Since the total loss of $25,000 is less than the $30,000 combined basis, the shareholder can deduct the full $25,000. The remaining $5,000 of combined basis ($30,000 − $25,000) carries forward.",
  },
  {
    id: 209,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §382, when a corporation with NOLs undergoes an ownership change, the annual §382 limitation equals:",
    choices: {
      A: "The value of the loss corporation's stock before the ownership change multiplied by the long-term tax-exempt rate",
      B: "The amount of NOLs carried forward divided by 20 years",
      C: "Taxable income for the year after the ownership change",
      D: "The fair market value of loss corporation assets times 5%",
    },
    answer: "A",
    explanation: "The §382 annual limitation = FMV of the loss corporation's stock immediately before the ownership change × the applicable long-term tax-exempt rate (published monthly by the IRS). This caps how much NOL can be used per year to prevent trafficking in loss corporations.",
  },
  {
    id: 210,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "The accumulated earnings tax (AET) under §531 applies to C corporations that accumulate earnings beyond the reasonable needs of the business. The AET rate is:",
    choices: { A: "15%", B: "20%", C: "21%", D: "15% on first $100,000 and 20% above" },
    answer: "B",
    explanation: "The accumulated earnings tax rate under §531 is 20% of the accumulated taxable income (the undistributed earnings in excess of the reasonable needs of the business and the $250,000 minimum credit). The 21% flat rate is the corporate income tax rate, not the AET rate.",
  },
  {
    id: 211,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "The personal holding company (PHC) tax under §541 applies when a corporation meets both an ownership test and an income test. The income test requires that PHC income is at least what percentage of adjusted ordinary gross income?",
    choices: { A: "50%", B: "60%", C: "70%", D: "80%" },
    answer: "B",
    explanation: "§542(a)(1) requires that at least 60% of adjusted ordinary gross income (AOGI) consist of PHC income (dividends, interest, rents, royalties, etc.) AND §542(a)(2) requires that more than 50% of the outstanding stock is owned by five or fewer individuals at some point during the last half of the year. The PHC tax rate is 20%.",
  },
  {
    id: 212,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A Type B reorganization (stock-for-stock exchange) under §368(a)(1)(B) requires that the acquiring corporation use solely:",
    choices: {
      A: "Cash and voting stock",
      B: "Voting stock only (no boot allowed)",
      C: "Any stock of the acquiring corporation",
      D: "Stock plus assumed liabilities up to 20%",
    },
    answer: "B",
    explanation: "A Type B reorganization is a 'solely for voting stock' acquisition. The acquiring corporation must use only its voting stock (or voting stock of its parent in a triangular B reorg). Any cash or other property (boot) disqualifies the exchange from Type B status. This is the most restrictive consideration requirement of all §368 reorganization types.",
  },
  {
    id: 213,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under the §338(h)(10) election, which of the following is true?",
    choices: {
      A: "The purchasing corporation can elect to treat the stock purchase as an asset purchase; the target's selling shareholders recognize no gain or loss",
      B: "Both the selling parent and purchasing corporation must jointly elect; the target is treated as selling its assets and then liquidating",
      C: "Only the purchasing corporation makes the election unilaterally",
      D: "The election applies only when the target is a C corporation",
    },
    answer: "B",
    explanation: "A §338(h)(10) election requires a joint election by both the selling consolidated group (or S corp shareholders) and the purchaser. The target is treated as selling all its assets at fair market value (generating gain taxed at the selling entity level) and then liquidating tax-free under §332. This gives the buyer a stepped-up basis in assets.",
  },
  {
    id: 214,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §1504, an affiliated group eligible to file a consolidated return requires the common parent to own directly at least what percentage of stock in each includible subsidiary?",
    choices: { A: "50% of voting + 50% of value", B: "80% of voting + 80% of value", C: "80% of voting only", D: "100% of all stock" },
    answer: "B",
    explanation: "§1504(a)(2) defines an affiliated group as corporations connected through stock ownership with the common parent owning at least 80% of total voting power AND at least 80% of total value of stock of at least one includible corporation. The 80/80 test applies at each tier of the chain.",
  },
  {
    id: 215,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A controlled foreign corporation (CFC) under §957 is a foreign corporation in which U.S. shareholders own more than 50% of the total combined voting power or value. 'U.S. shareholder' means a U.S. person owning at least:",
    choices: { A: "5% of the total combined voting power", B: "10% of the total combined voting power or value", C: "25% of total value", D: "50% of any class of stock" },
    answer: "B",
    explanation: "§951(b) defines a U.S. shareholder as a U.S. person who owns 10% or more of the total combined voting power or total value of shares of all classes of stock of the foreign corporation. Only U.S. shareholders (10%+ owners) must include Subpart F income and GILTI in income.",
  },
  {
    id: 216,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under the PFIC rules (§1291–1298), a foreign corporation is a Passive Foreign Investment Company if it meets either the income test or asset test. The income test requires that at least what percent of gross income is passive income?",
    choices: { A: "50%", B: "60%", C: "75%", D: "80%" },
    answer: "C",
    explanation: "§1297(a) defines a PFIC using two tests: (1) the income test — 75% or more of gross income is passive income, OR (2) the asset test — 50% or more of average assets produce (or are held for the production of) passive income. PFIC status triggers punitive interest charges and tax treatment under §1291.",
  },
  {
    id: 217,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §469 passive activity grouping rules, a taxpayer may group activities together as a single activity if they constitute an 'appropriate economic unit.' Which factor is MOST important in the grouping determination?",
    choices: {
      A: "The activities are in the same geographic location",
      B: "The activities are interdependent and share management and employees",
      C: "The taxpayer's original intent when acquiring the activities",
      D: "The activities have the same NAICS code",
    },
    answer: "B",
    explanation: "Reg. §1.469-4 lists five factors for grouping: (1) similarities in types of business, (2) common control, (3) common ownership, (4) geographic location, and (5) interdependencies. The most significant factors are common management, interdependencies (shared employees, customers, facilities), and common control. There is no single required factor, but interdependency and common ownership/management are paramount.",
  },
  {
    id: 218,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §704(d), a partner's distributive share of partnership loss is limited to the partner's adjusted outside basis at year-end. Disallowed losses are:",
    choices: {
      A: "Permanently disallowed",
      B: "Carried forward indefinitely and allowed when the partner's outside basis increases",
      C: "Carried back 2 years and forward 20 years",
      D: "Allocated to other partners with positive basis",
    },
    answer: "B",
    explanation: "Under §704(d), losses exceeding outside basis are suspended (not permanently disallowed) and carried forward to future years. They become deductible when the partner's outside basis increases (through contributions, income allocations, or increased share of partnership liabilities under §752). The §704(d) limitation is separate from the at-risk (§465) and passive activity (§469) rules, which also apply.",
  },
  {
    id: 219,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §706(b), a partnership must use the required taxable year unless it establishes a business purpose or makes a §444 election. The required taxable year is the taxable year of:",
    choices: {
      A: "The majority partners (partners owning more than 50% of profits and capital)",
      B: "The principal partners (5%+ interest), if they all have the same year",
      C: "The year that results in the least aggregate deferral of income to partners",
      D: "A, then B, then C, in priority order",
    },
    answer: "D",
    explanation: "§706(b) imposes a required tax year hierarchy: (1) the majority partners' year if partners with the same tax year own more than 50% of profits/capital; (2) if no majority, the year common to principal partners (≥5%); (3) if neither applies, the year with least aggregate deferral. A §444 election allows up to a 3-month deferral from the required year.",
  },
  {
    id: 220,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "§1244 stock allows ordinary loss treatment (instead of capital loss) on stock of a domestic small business corporation. The annual ordinary loss limit is:",
    choices: {
      A: "$25,000 ($50,000 MFJ)",
      B: "$50,000 ($100,000 MFJ)",
      C: "$100,000 ($200,000 MFJ)",
      D: "$250,000 for any taxpayer",
    },
    answer: "B",
    explanation: "§1244 allows up to $50,000 per year ($100,000 on a joint return) of ordinary loss on the sale or worthlessness of §1244 stock. The corporation must have received $1 million or less in capital contributions when the stock was issued, and the loss must be sustained by the original issuee. Excess losses are capital losses.",
  },
  {
    id: 221,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "The §1202 exclusion for qualified small business stock (QSBS) allows a non-corporate taxpayer to exclude gain from sale of QSBS held more than 5 years. The exclusion percentage for stock acquired after September 27, 2010 is:",
    choices: { A: "50%", B: "75%", C: "100%", D: "60%" },
    answer: "C",
    explanation: "§1202(a)(4) provides a 100% exclusion for QSBS acquired after September 27, 2010. The exclusion is limited to the greater of $10 million or 10× the taxpayer's adjusted basis in the stock. For stock acquired before September 28, 2010, the exclusion is 50% (before February 18, 2009) or 75% (February 18, 2009 – September 27, 2010).",
  },
  {
    id: 222,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A §332 complete liquidation of a subsidiary into its parent corporation is tax-free to both parties if the parent owns at least 80% of the subsidiary's stock. The parent's basis in the received assets equals:",
    choices: {
      A: "Fair market value of assets received",
      B: "The subsidiary's adjusted basis in the assets (carry-over basis)",
      C: "The parent's basis in the subsidiary's stock",
      D: "Zero — all basis is wiped out",
    },
    answer: "B",
    explanation: "Under §334(b), in a §332 liquidation, the parent corporation takes a carryover basis in the assets received from the subsidiary (the subsidiary's adjusted basis). The subsidiary's tax attributes (NOLs, E&P, etc.) also carry over to the parent under §381. The parent does not recognize gain or loss under §332.",
  },
  {
    id: 223,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under the §707(a)(2)(B) disguised sale rules, a contribution of property to a partnership followed by a distribution to the contributing partner within how many years is presumed to be a disguised sale?",
    choices: { A: "2 years", B: "5 years", C: "7 years", D: "10 years" },
    answer: "A",
    explanation: "Reg. §1.707-3(c) creates a rebuttable presumption: if a partner contributes property and receives a distribution within 2 years, the transactions are presumed to be a sale of the property to the partnership. Transfers more than 2 years apart are presumed NOT to be a sale. The 2-year window is critical for disguised sale analysis.",
  },
  {
    id: 224,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "An S corporation that was previously a C corporation is subject to the built-in gains (BIG) tax under §1374 on dispositions of appreciated assets during the recognition period. Post-TCJA, the recognition period is:",
    choices: { A: "5 years", B: "7 years", C: "10 years", D: "Permanently" },
    answer: "A",
    explanation: "Post-TCJA (2018), the recognition period for §1374 BIG tax is permanently set at 5 years (down from 10 years). If the S corporation disposes of an asset within 5 years of electing S status, gain attributable to the built-in appreciation at the time of S election is taxed at the highest corporate rate (21% currently).",
  },
  {
    id: 225,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A §269 acquisition disallows deductions when the principal purpose of acquiring control of a corporation is tax evasion or avoidance. 'Control' for §269 means:",
    choices: {
      A: "Owning more than 50% of voting stock",
      B: "Owning 80% or more of voting or nonvoting stock",
      C: "Any acquisition of stock that shifts tax losses to the acquirer",
      D: "Owning more than 50% of total value of all classes of stock",
    },
    answer: "B",
    explanation: "§269(a) applies when a person acquires control, defined as ownership of stock possessing at least 80% of total combined voting power or at least 80% of total value of shares of all classes of stock. This mirrors the §368(c) control definition. The IRS must prove the principal purpose was tax avoidance.",
  },
  {
    id: 226,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §761(a), certain partnerships may elect out of Subchapter K (partnership tax rules) entirely if the participants' intent is merely to share property investments. Which of the following is a requirement for a valid §761 election?",
    choices: {
      A: "The organization must have fewer than 10 members",
      B: "The participants must own the property as co-owners, reserves the right to separately take in kind or sell their shares",
      C: "The organization must be formed in a state that recognizes it as a partnership",
      D: "All partners must be U.S. citizens",
    },
    answer: "B",
    explanation: "Under §761(a) and Reg. §1.761-2, an unincorporated organization may elect out of Subchapter K if it is formed for investment purposes only, participants own undivided interests in property, each participant can take their share in kind or sell it, and the organization does not actively conduct a business. This treats members as co-owners rather than partners.",
  },
  {
    id: 227,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "In a §351 exchange, if a transferor receives boot (cash or property other than stock), the recognized gain is:",
    choices: {
      A: "The total realized gain on all property transferred",
      B: "The lesser of the realized gain or the FMV of boot received",
      C: "The FMV of boot minus the transferor's basis in the boot",
      D: "Zero — §351 always provides full nonrecognition",
    },
    answer: "B",
    explanation: "Under §351(b), if a transferor receives boot in addition to qualifying stock, gain is recognized equal to the lesser of (1) realized gain or (2) the FMV of the boot received. Loss is never recognized in a §351 exchange even if boot is received (§351(b)(2)). Boot includes cash, notes, and short-term debt assumed in excess of basis.",
  },
  {
    id: 228,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §197, which of the following is NOT amortizable as a §197 intangible over 15 years?",
    choices: {
      A: "Customer lists acquired in a business acquisition",
      B: "Self-created patents developed by the taxpayer's own R&D",
      C: "Goodwill acquired in a business purchase",
      D: "Covenants not to compete acquired in connection with a business acquisition",
    },
    answer: "B",
    explanation: "§197 amortization (15 years, straight-line) applies to intangibles acquired in connection with the acquisition of a trade or business. Self-created intangibles (patents, trademarks developed in-house) are generally not §197 intangibles and are not amortized under §197. They may qualify for capitalization and amortization under other Code sections (e.g., §174 for R&D post-2022).",
  },
  {
    id: 229,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §1368 S corporation distribution ordering rules, when an S corporation has accumulated E&P from C corporation years, distributions are sourced from:",
    choices: {
      A: "E&P first, then AAA",
      B: "AAA first, then E&P, then OAA, then return of basis",
      C: "Return of stock basis first, then AAA, then E&P",
      D: "Proportionally from all accounts simultaneously",
    },
    answer: "B",
    explanation: "When an S corporation has C corporation accumulated E&P, the §1368(c) ordering is: (1) AAA (tax-free to shareholders), (2) accumulated E&P (taxed as dividend), (3) other adjustments account (OAA — tax-free), (4) remaining basis (tax-free return of capital), (5) gain (capital gain). Without C corp E&P, distributions are from AAA only.",
  },
  {
    id: 230,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "The §1059 'extraordinary dividend' rule requires a corporate shareholder to reduce its stock basis (but not below zero) by the nontaxed portion of an extraordinary dividend received. A dividend is 'extraordinary' if it equals or exceeds what percentage of the corporation's adjusted basis in the stock?",
    choices: { A: "5% for preferred, 10% for common", B: "10% for preferred, 5% for common", C: "5% for both common and preferred", D: "10% for both" },
    answer: "A",
    explanation: "§1059(c) defines an extraordinary dividend as one equaling or exceeding 5% of the shareholder's adjusted basis in the stock for preferred stock, or 10% of adjusted basis for common stock (or any stock held 2 years or less). §1059 prevents corporations from using the DRD to receive nontaxed dividends that artificially reduce stock basis and increase gain on subsequent sale.",
  },

  // ── DOMAIN 2: Business Tax (Q231–Q267) ───────────────────────────────────
  {
    id: 231,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §263A (UNICAP), which of the following taxpayers is NOT required to capitalize indirect costs to inventory?",
    choices: {
      A: "A manufacturer with $30 million average annual gross receipts",
      B: "A publisher that prints and sells books",
      C: "A small reseller with $25 million or less in average annual gross receipts (small business exception)",
      D: "A farming corporation that grows and sells produce",
    },
    answer: "C",
    explanation: "§263A(b)(2) provides an exemption for taxpayers whose average annual gross receipts for the prior 3 years do not exceed $30 million (inflation-adjusted; was $25 million under TCJA, now $30 million). These small businesses are exempt from UNICAP uniform capitalization rules. Manufacturers, publishers, and large resellers must capitalize direct and indirect production costs.",
  },
  {
    id: 232,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "§195 allows a taxpayer to elect to deduct start-up expenditures. The maximum first-year deduction is $5,000, reduced dollar-for-dollar when cumulative start-up costs exceed:",
    choices: { A: "$25,000", B: "$50,000", C: "$75,000", D: "$100,000" },
    answer: "B",
    explanation: "Under §195(b)(1), a taxpayer may deduct up to $5,000 of start-up costs in the year business begins, reduced dollar-for-dollar when total start-up costs exceed $50,000. If costs exceed $55,000, the entire $5,000 deduction is eliminated. Remaining costs are amortized over 180 months (15 years). §248 applies the same rules to corporate organizational costs.",
  },
  {
    id: 233,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "§163(j) limits the business interest expense deduction to 30% of adjusted taxable income (ATI). For tax years beginning after December 31, 2021, ATI is computed:",
    choices: {
      A: "Before deducting depreciation, amortization, and depletion (EBITDA-like)",
      B: "After deducting depreciation, amortization, and depletion (EBIT-like)",
      C: "Using book income rather than taxable income",
      D: "Including floor plan financing interest which is always excluded",
    },
    answer: "B",
    explanation: "For tax years beginning after 2021, the TCJA phase-out of the EBITDA-based ATI took effect, switching to EBIT-based ATI (after depreciation, amortization, and depletion). This makes the §163(j) limitation more restrictive for capital-intensive businesses. Floor plan financing interest is excluded from the §163(j) limitation entirely.",
  },
  {
    id: 234,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The Net Investment Income Tax (NIIT) under §1411 imposes a 3.8% tax on the lesser of NII or the excess of modified AGI over the threshold. For a married filing jointly taxpayer, the MAGI threshold is:",
    choices: { A: "$200,000", B: "$250,000", C: "$300,000", D: "$500,000" },
    answer: "B",
    explanation: "§1411(b) sets the MAGI thresholds at $250,000 for MFJ and qualifying widower, $200,000 for single and head of household, and $125,000 for MFS. These thresholds are NOT indexed for inflation. NII includes interest, dividends, capital gains, rents, royalties, and passive activity income.",
  },
  {
    id: 235,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The §1231 lookback rule requires a taxpayer to recharacterize §1231 gains as ordinary income to the extent of non-recaptured §1231 losses from the prior how many years?",
    choices: { A: "3 years", B: "5 years", C: "7 years", D: "10 years" },
    answer: "B",
    explanation: "Under §1231(c), §1231 gains are recharacterized as ordinary income to the extent of unrecaptured §1231 net losses from the preceding 5 years. This lookback rule prevents taxpayers from bunching ordinary §1231 losses in one year and capital §1231 gains in a later year. Only non-recaptured losses remain as capital gains.",
  },
  {
    id: 236,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A calendar-year C corporation sells equipment for $500,000. The equipment cost $400,000, has $200,000 of accumulated MACRS depreciation, and has an adjusted basis of $200,000. What type of gain does the corporation recognize?",
    choices: {
      A: "$200,000 ordinary (§1245 recapture) + $100,000 §1231 gain",
      B: "$200,000 §1231 gain + $100,000 long-term capital gain",
      C: "$300,000 all ordinary income",
      D: "$200,000 §1245 recapture + $100,000 ordinary §1231 converted by lookback",
    },
    answer: "A",
    explanation: "Amount realized $500,000 − adjusted basis $200,000 = $300,000 total gain. Under §1245, the $200,000 of accumulated depreciation is all recaptured as ordinary income. The remaining $100,000 is §1231 gain (potentially treated as capital gain absent the lookback rule). Answer: $200,000 §1245 ordinary + $100,000 §1231.",
  },
  {
    id: 237,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "For an installment sale, the gross profit percentage (GP%) is used to determine how much of each payment is gain. GP% is calculated as:",
    choices: {
      A: "Contract price divided by gross profit",
      B: "Gross profit divided by contract price",
      C: "Adjusted basis divided by selling price",
      D: "Total gain divided by total payments received",
    },
    answer: "B",
    explanation: "Under §453, GP% = Gross Profit ÷ Contract Price. Gross profit = selling price − adjusted basis (reduced for §1245 recapture recognized in year of sale). Contract price = selling price − qualified assumed liabilities. Each installment payment × GP% = recognized gain in that year (the rest is return of basis and interest income).",
  },
  {
    id: 238,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §461 economic performance, a cash-method taxpayer can generally deduct expenses when paid. But for accrual-method taxpayers, when does economic performance occur for services provided TO the taxpayer?",
    choices: {
      A: "When the taxpayer pays for the services",
      B: "When the services are provided (performed) to the taxpayer",
      C: "When the taxpayer accrues the liability on its books",
      D: "At year-end if the services will be completed within 8.5 months",
    },
    answer: "B",
    explanation: "Under §461(h) and Reg. §1.461-4(d), for services provided to the taxpayer, economic performance occurs when the services are actually performed. For services provided by the taxpayer (liabilities arising from tortious activity, workers' compensation, etc.), economic performance occurs when payment is made. The 8.5-month recurring item exception allows deduction in the prior year if the liability recurs and is paid within 8.5 months after year-end.",
  },
  {
    id: 239,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §7872, a below-market loan between an employer and employee for $100,000 results in what tax consequences?",
    choices: {
      A: "The employer deducts interest; the employee reports nothing",
      B: "Imputed interest is treated as compensation to the employee and interest income to the employer, with offsetting interest deduction for the employee",
      C: "No tax consequences if the loan is repaid within one year",
      D: "The entire loan principal is treated as income to the employee",
    },
    answer: "B",
    explanation: "§7872 imputes interest on below-market loans. For employer-employee loans, the foregone interest is treated as: (1) compensation income to the employee (deductible by employer as wages subject to payroll taxes), and (2) interest income to the employer. The employee has corresponding deemed interest expense (deductible if interest is deductible — e.g., business purpose). The AFR is used as the imputed rate.",
  },
  {
    id: 240,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "§83(b) allows a recipient of restricted property to elect to include the property's FMV in income at the time of receipt (rather than vesting). The election must be made within:",
    choices: { A: "30 days of receipt of the property", B: "60 days of receipt of the property", C: "90 days of receipt", D: "The due date of the tax return for the year of receipt" },
    answer: "A",
    explanation: "A §83(b) election must be filed with the IRS within 30 days of the date the property was transferred (received), regardless of when the vesting conditions lapse. This is a strict deadline with no extensions. The election causes immediate income recognition at FMV − amount paid, but any subsequent appreciation is capital gain. The election is irrevocable.",
  },
  {
    id: 241,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "An incentive stock option (ISO) under §422 results in no regular income tax at grant or exercise. However, the spread at exercise (FMV − exercise price) is an adjustment for:",
    choices: {
      A: "The Net Investment Income Tax",
      B: "The Alternative Minimum Tax (AMT)",
      C: "The Additional Medicare Tax",
      D: "Passive activity income",
    },
    answer: "B",
    explanation: "§56(b)(3) makes the ISO spread at exercise an AMT preference item. Even though no regular income tax is owed at exercise of a qualifying ISO, the excess of FMV over exercise price is included in AMTI. This frequently triggers AMT for employees who exercise large numbers of ISOs. Disqualifying dispositions (selling within 1 year of exercise or 2 years of grant) result in ordinary income.",
  },
  {
    id: 242,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "§162(m) limits the deductibility of compensation paid to covered employees of publicly held corporations. The annual deduction limit per covered employee is:",
    choices: { A: "$500,000", B: "$750,000", C: "$1,000,000", D: "$2,000,000" },
    answer: "C",
    explanation: "§162(m) disallows a deduction for compensation exceeding $1 million per year paid to any 'covered employee' (CEO, CFO, and the 3 other highest-compensated officers). Post-TCJA (2018), the performance-based compensation exception was eliminated for most companies. Once an employee is a covered employee, they remain covered for all future years (including after separation).",
  },
  {
    id: 243,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "The §280G golden parachute rules impose a 20% excise tax on the recipient and deny the payor a deduction for 'excess parachute payments.' An excess parachute payment is the amount by which the payment exceeds:",
    choices: {
      A: "The disqualified individual's average annual W-2 compensation",
      B: "Three times the disqualified individual's base amount (average W-2 compensation for the 5 preceding years)",
      C: "The present value of total payments exceeding the base amount",
      D: "The disqualified individual's base salary for the current year",
    },
    answer: "B",
    explanation: "Under §280G, a parachute payment is any payment contingent on a change of control that equals or exceeds 3× the recipient's 'base amount' (average annual W-5 compensation for the 5 preceding years). The 'excess parachute payment' is the amount in excess of 1× the base amount (the portion above the safe harbor). Both the 20% excise tax (§4999) and the deduction disallowance (§280G) apply.",
  },
  {
    id: 244,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §132, which of the following fringe benefits is excluded from employee gross income WITHOUT a dollar limit?",
    choices: {
      A: "Employer-provided parking",
      B: "Working condition fringe (property/services the employee could deduct if paid for themselves)",
      C: "De minimis fringe benefits",
      D: "Qualified moving expense reimbursements",
    },
    answer: "B",
    explanation: "§132(d) excludes working condition fringes from income with no dollar limit, as long as the employee could have deducted the expense under §162 or §167 if they had paid it themselves. Examples: business use of company car, subscriptions, tools. Parking ($325/month in 2024) and transit passes ($325/month) have dollar limits. Qualified moving expenses are no longer excludable post-TCJA (except military).",
  },
  {
    id: 245,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "For 2024, the maximum employee elective deferral to a 401(k) plan is $23,000. The additional catch-up contribution allowed for participants age 50 and older is:",
    choices: { A: "$3,500", B: "$6,500", C: "$7,500", D: "$10,000" },
    answer: "C",
    explanation: "For 2024, the 401(k) catch-up contribution limit for participants age 50+ is $7,500, for a total of $30,500. SECURE 2.0 Act also introduced a special catch-up for ages 60–63 of the greater of $10,000 or 150% of the regular catch-up, effective in 2025. The SIMPLE IRA catch-up for 50+ is $3,500 (2024).",
  },
  {
    id: 246,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §72(t), the 10% early distribution penalty from an IRA does not apply to distributions for 'substantially equal periodic payments' under §72(t)(2)(A)(iv). The payments must continue for at least:",
    choices: {
      A: "5 years or until age 59½, whichever comes first",
      B: "5 years or until age 59½, whichever is LATER",
      C: "10 years regardless of age",
      D: "Until the account is depleted",
    },
    answer: "B",
    explanation: "Under §72(t)(4), if substantially equal periodic payments (SEPP / 72(t) payments) are modified before the later of (1) 5 years or (2) age 59½, the 10% penalty applies retroactively to all prior distributions plus interest. For example, if payments begin at age 56, they must continue until at least age 61 (5 years is later). Beginning at age 57, they must continue to 62.",
  },
  {
    id: 247,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "§1341 (claim of right) provides relief when a taxpayer must repay amounts previously included in income. Which method does §1341 allow?",
    choices: {
      A: "Deduct the repayment in the year of repayment only",
      B: "Amend the prior year return to remove the income",
      C: "The better of: (1) deduct in year of repayment, or (2) credit equal to the tax saved if the income had been excluded in the prior year",
      D: "Spread the deduction over 5 years",
    },
    answer: "C",
    explanation: "§1341 applies when (1) an item was included in a prior year because it appeared the taxpayer had an unrestricted right to it, and (2) it becomes clear in the current year that the right did not exist, and (3) the repayment exceeds $3,000. The taxpayer may use the method that produces the greater tax benefit: (a) current-year deduction, or (b) credit for the tax saved if the income had never been included.",
  },
  {
    id: 248,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The §121 home sale exclusion allows single filers to exclude up to $250,000 of gain ($500,000 MFJ). To qualify, the taxpayer must have owned AND used the home as a principal residence for at least 2 of the last 5 years. How frequently can this exclusion be used?",
    choices: {
      A: "Once per lifetime",
      B: "Once every 2 years",
      C: "Once every 3 years",
      D: "Unlimited times, as long as each sale qualifies",
    },
    answer: "B",
    explanation: "§121(b)(3) provides that the exclusion can only be used once in any 2-year period. A taxpayer who used the exclusion on a prior sale cannot use it again until 2 years have elapsed. This prevents serial home flippers from using §121 on rapid successive sales. There is no lifetime limit — the exclusion can be used multiple times as long as each qualifies and the 2-year waiting period is observed.",
  },
  {
    id: 249,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §951A, GILTI (Global Intangible Low-Taxed Income) equals a U.S. shareholder's net CFC tested income MINUS a routine return on tangible assets (QBAI). The routine return is:",
    choices: { A: "5% of QBAI", B: "10% of QBAI", C: "15% of QBAI", D: "20% of QBAI" },
    answer: "B",
    explanation: "§951A(b)(1) computes GILTI as net tested income minus 10% of QBAI (Qualified Business Asset Investment — the adjusted basis of tangible depreciable property used in the CFC's tested income production). The 10% deemed return represents the expected normal return on tangible assets; income above this is presumed to be intangible income subject to GILTI.",
  },
  {
    id: 250,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "§250 allows C corporations to deduct 37.5% of FDII (Foreign-Derived Intangible Income) and 50% of GILTI. Post-2025, these percentages decrease. What are the post-2025 §250 deduction percentages?",
    choices: {
      A: "FDII 21.875% and GILTI 37.5%",
      B: "FDII 37.5% and GILTI 50% (unchanged)",
      C: "FDII 21.875% and GILTI 28.571% (after 2025 reduction)",
      D: "FDII 15% and GILTI 35%",
    },
    answer: "A",
    explanation: "Under §250, for tax years beginning after December 31, 2025, the deduction percentages are reduced: FDII deduction drops from 37.5% to 21.875%, and GILTI deduction drops from 50% to 37.5%. At a 21% corporate rate, this results in an effective rate of 13.125% on FDII (vs. 10.5% pre-2026) and 13.125% on GILTI (vs. 10.5% pre-2026).",
  },
  {
    id: 251,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "The Base Erosion and Anti-Abuse Tax (§59A BEAT) applies to large corporations that make deductible payments to foreign related parties. The minimum tax rate for the BEAT is:",
    choices: { A: "5% initially, rising to 10%", B: "10% (2019 and after)", C: "15% after 2025", D: "Both B and C are correct for different tax years" },
    answer: "D",
    explanation: "§59A imposes BEAT at 5% for 2018, 10% for 2019–2025, and 12.5% beginning in 2026. The BEAT = the excess of modified taxable income (adding back base erosion payments) over regular tax liability. Banks and securities dealers have a 1 percentage point addition for each phase (6%, 11%, 13.5%). BEAT applies to corporations with average gross receipts ≥ $500M and a base erosion percentage ≥ 3% (2% for banks).",
  },
  {
    id: 252,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §311(b), when a C corporation distributes appreciated property (FMV > basis) to shareholders, the corporation recognizes gain as if:",
    choices: {
      A: "No gain is recognized by the corporation",
      B: "The property was sold at FMV on the date of distribution",
      C: "The property was sold at adjusted basis (no gain)",
      D: "The property was sold at the lower of FMV or adjusted basis",
    },
    answer: "B",
    explanation: "§311(b) requires a corporation to recognize gain when distributing appreciated property to shareholders, as if the corporation sold the property for its fair market value. The corporation's recognized gain = FMV − adjusted basis. The shareholder's dividend income = FMV of property received. Note: §311(a) provides that no loss is recognized on distributions of depreciated property.",
  },
  {
    id: 253,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The §245A deduction allows U.S. C corporations that own at least 10% of a foreign corporation to exclude what percentage of dividends received from that foreign corporation?",
    choices: { A: "50%", B: "65%", C: "80%", D: "100%" },
    answer: "D",
    explanation: "§245A provides a 100% dividends-received deduction (participation exemption) for dividends received by a domestic C corporation from a specified 10%-owned foreign corporation (SFC) out of the SFC's foreign earnings. This moved the U.S. to a territorial tax system for C corporations. The SFC must have been held for at least 1 year before the dividend is paid.",
  },
  {
    id: 254,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "§409A governs nonqualified deferred compensation (NQDC) plans. If a plan fails to comply with §409A, the deferred amount is:",
    choices: {
      A: "Taxed at ordinary rates in the year of failure, plus 20% penalty tax, plus interest at underpayment rate + 1%",
      B: "Forfeited to the employer as a penalty",
      C: "Taxed as a capital gain with a 10% penalty",
      D: "Deferred until the actual payment date with no penalty",
    },
    answer: "A",
    explanation: "A §409A failure causes immediate income inclusion of all deferred amounts (even if not yet received), a 20% additional excise tax on top of ordinary income tax, PLUS interest at the underpayment rate plus 1% from the date the compensation was deferred. §409A requires fixed payment schedules tied to specific trigger events (separation, disability, death, change of control, unforeseeable emergency, or specified date).",
  },
  {
    id: 255,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §1033, when involuntary conversion proceeds are received (e.g., insurance for destroyed property), the taxpayer must reinvest in similar-or-related-use property within what time period to defer gain?",
    choices: {
      A: "1 year from the end of the tax year in which the gain is realized",
      B: "2 years from the end of the tax year in which the gain is realized",
      C: "3 years (5 years for real property condemned for public use)",
      D: "180 days from the date of conversion",
    },
    answer: "B",
    explanation: "§1033(a)(2)(B) generally requires that replacement property be acquired within 2 years after the close of the first tax year in which gain is realized. For condemnation of real property used in business or held for investment, the period is extended to 3 years. For Presidentially-declared disaster areas, the IRS may extend the period further. Failure to timely replace means all realized gain is recognized.",
  },
  {
    id: 256,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "§461(l) limits excess business losses for non-corporate taxpayers. For 2024, an excess business loss exists when aggregate business deductions exceed aggregate business gross income plus:",
    choices: { A: "$250,000 ($500,000 MFJ)", B: "$289,000 ($578,000 MFJ) — inflation-adjusted for 2024", C: "$500,000 for any taxpayer", D: "$1,000,000 for any taxpayer" },
    answer: "B",
    explanation: "§461(l) (TCJA, made permanent by ARPA) disallows excess business losses — defined as aggregate business deductions exceeding aggregate business income plus the threshold. The base threshold is $250,000 ($500,000 MFJ) adjusted for inflation. For 2024, the inflation-adjusted amounts are approximately $289,000 ($578,000 MFJ). Disallowed excess business losses become an NOL carryforward.",
  },
  {
    id: 257,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A self-employed taxpayer (sole proprietor) pays $12,000 in health insurance premiums for herself, her spouse, and dependents. Her net self-employment income is $80,000. How much of the premium is deductible?",
    choices: {
      A: "$6,000 — limited to 50% of SE income",
      B: "$12,000 — full amount deductible as an above-the-line deduction under §162(l)",
      C: "$9,000 — limited to 75% of SE income",
      D: "$7,200 — limited by 7.5% of AGI floor",
    },
    answer: "B",
    explanation: "§162(l) allows self-employed individuals to deduct 100% of health insurance premiums paid for themselves, spouses, and dependents as an above-the-line deduction. The deduction is limited to net self-employment income (it cannot exceed net SE income, and it cannot be taken if the taxpayer was eligible to participate in an employer-subsidized plan for any month). No 7.5% AGI floor applies to §162(l).",
  },
  {
    id: 258,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "For 2024, the maximum annual addition to a SEP-IRA (employer contribution) is the lesser of 25% of compensation or:",
    choices: { A: "$61,000", B: "$66,000", C: "$69,000", D: "$75,000" },
    answer: "C",
    explanation: "For 2024, the §415(c) annual additions limit for defined contribution plans is $69,000 (up from $66,000 in 2023). SEP-IRA contributions are capped at the lesser of $69,000 or 25% of compensation ($345,000 compensation cap × 25% = $86,250, so the $69,000 absolute limit controls for high earners). Self-employed individuals use a special formula (effectively ~20% of net SE income).",
  },
  {
    id: 259,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "The §199A QBI deduction for a specified service trade or business (SSTB) is completely phased out when taxable income exceeds the upper threshold. For 2024 MFJ filers, the complete phase-out threshold is approximately:",
    choices: { A: "$383,900", B: "$433,550", C: "$483,900", D: "$533,900" },
    answer: "C",
    explanation: "For 2024, the §199A phase-in range for SSTBs is $383,900 (lower threshold) to $483,900 (upper threshold) for MFJ filers ($191,950 to $241,950 for single filers). These are indexed for inflation. Within the phase-in range, the SSTB deduction is reduced proportionally. Above the upper threshold, SSTBs are completely excluded from the §199A deduction.",
  },
  {
    id: 260,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §166, business bad debts are deductible when a debt becomes wholly or partially worthless. How is a business bad debt deducted?",
    choices: {
      A: "As a capital loss subject to the $3,000 annual deduction limit",
      B: "As an ordinary deduction in the year the debt becomes worthless",
      C: "Over 5 years on straight-line basis",
      D: "Only when final judgment against debtor is obtained",
    },
    answer: "B",
    explanation: "§166(a) allows an ordinary deduction for business bad debts (debts created or acquired in connection with a trade or business) when they become wholly or partially worthless. By contrast, nonbusiness bad debts under §166(d) are treated as short-term capital losses, subject to the $3,000 deduction limit. There is no requirement to obtain a judgment; facts-and-circumstances evidence of worthlessness suffices.",
  },
  {
    id: 261,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §453(i), §1245 or §1250 recapture income on an installment sale must be recognized:",
    choices: {
      A: "Ratably over the installment period",
      B: "In full in the year of the sale, regardless of payments received",
      C: "When the installment contract is paid in full",
      D: "In the year elected by the taxpayer (up to 5-year spread)",
    },
    answer: "B",
    explanation: "§453(i) requires that all depreciation recapture under §1245 and §1250 be recognized in the year of the installment sale, even if no or little cash is received in that year. This prevents taxpayers from deferring ordinary recapture income through installment reporting. Only the non-recapture portion of the gain can be reported on the installment method under §453.",
  },
  {
    id: 262,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The failure-to-deposit (FTD) penalty under §6656 for payroll taxes is tiered based on how late the deposit is. A deposit made 16 or more days late incurs a penalty of:",
    choices: { A: "2%", B: "5%", C: "10%", D: "15%" },
    answer: "C",
    explanation: "§6656 FTD penalty tiers: 2% if 1–5 days late; 5% if 6–15 days late; 10% if 16+ days late; 15% if the IRS sends notice and demand (the 10-day notice). The penalty applies to the amount of the underpayment. For new employers and small businesses that inadvertently fail to deposit, first-time penalty abatement (FTA) may be available.",
  },
  {
    id: 263,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §4980H(a), an 'applicable large employer' (ALE) that fails to offer minimum essential coverage (MEC) to at least 95% of full-time employees faces a monthly penalty per full-time employee (minus 30) equal to (for 2024):",
    choices: { A: "$2,970 annualized per employee", B: "$4,460 annualized per employee", C: "$14,100 annualized per employee", D: "$240/month per employee" },
    answer: "B",
    explanation: "For 2024, the §4980H(a) 'A' penalty is $4,460 annualized ($371.67/month) × (number of full-time employees − 30). The §4980H(b) 'B' penalty (offering unaffordable or non-minimum value coverage) is $6,700 per employee who receives a premium tax credit. ALEs are employers with 50+ full-time equivalent employees. These amounts are indexed for inflation annually.",
  },
  {
    id: 264,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "The percentage depletion method for oil and gas wells for independent producers is 15%. However, the percentage depletion deduction is limited to what percentage of the property's net income from the property?",
    choices: { A: "50%", B: "65% of taxable income from all sources", C: "100% of the property's net income", D: "Both A and B apply as separate limitations" },
    answer: "C",
    explanation: "Under §613A, percentage depletion for independent oil and gas producers is 15% of gross income from the property, but limited to 100% of the net income from the property (§613(a)). Additionally, §613A(d)(1) limits percentage depletion to 65% of the taxpayer's taxable income (before the deduction). The more restrictive of applicable limits applies. Integrated oil companies generally cannot use percentage depletion.",
  },
  {
    id: 265,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Post-2017, C corporations may deduct NOL carryforwards, but only up to what percentage of taxable income in the carryforward year?",
    choices: { A: "50%", B: "60%", C: "80%", D: "100%" },
    answer: "C",
    explanation: "Under §172(a)(2) as amended by TCJA, for NOLs arising in tax years beginning after December 31, 2017, the NOL deduction is limited to 80% of taxable income (computed before the NOL deduction). Pre-2018 NOLs can still offset 100% of taxable income and are subject to the old 20-year carryforward (no carryback). Post-2017 NOLs carry forward indefinitely with the 80% limitation.",
  },
  {
    id: 266,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "§4980B requires group health plans to offer COBRA continuation coverage. The maximum COBRA premium that can be charged to a qualified beneficiary is:",
    choices: {
      A: "The employee's share only (employer portion is free)",
      B: "102% of the applicable cost (100% + 2% administrative fee)",
      C: "150% of the applicable cost after 18 months",
      D: "110% of the applicable cost",
    },
    answer: "B",
    explanation: "Under §4980B(f)(4), qualified beneficiaries may be charged up to 102% of the applicable premium (the full cost including the employer's share, plus a 2% administrative fee). For disability extensions (months 19–29), the maximum is 150% of the applicable premium. COBRA coverage generally lasts 18 months (36 months for certain qualifying events like death, divorce, or Medicare entitlement).",
  },
  {
    id: 267,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "§179D provides a deduction for energy-efficient commercial building property. Post-IRA (Inflation Reduction Act, 2022), the maximum deduction per square foot for achieving the highest efficiency level is:",
    choices: { A: "$1.80 per sq ft", B: "$5.00 per sq ft", C: "$10.00 per sq ft", D: "Unlimited — 100% of cost" },
    answer: "B",
    explanation: "Post-IRA (2023+), §179D provides a base deduction of $0.50/sq ft, up to $1.00/sq ft for 25–50% energy savings, with a maximum of $5.00/sq ft when prevailing wage and apprenticeship requirements are met and the property achieves at least 25% energy cost reduction. The pre-IRA maximum was $1.80/sq ft. Government-owned buildings can allocate the deduction to the designer.",
  },

  // ── DOMAIN 3: Specialized Returns (Q268–Q285) ─────────────────────────────
  {
    id: 268,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under §663(b), a trustee may elect to treat distributions made within the first 65 days of a tax year as having been made on the last day of the preceding tax year. This election applies to:",
    choices: {
      A: "Simple trusts and complex trusts",
      B: "Complex trusts and estates only",
      C: "Simple trusts only",
      D: "All trusts including grantor trusts",
    },
    answer: "B",
    explanation: "The §663(b) 65-day rule election is available only for complex trusts and estates (not simple trusts, grantor trusts, or pooled income funds). The election allows a trustee to time distributions made in the first 65 days of a new tax year back to the prior year, reducing the trust's/estate's DNI for the prior year and avoiding excess accumulation income for the beneficiary.",
  },
  {
    id: 269,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §642(c), a trust or estate may claim a charitable deduction for amounts permanently set aside for charitable purposes under a specific provision of the governing instrument. What is the AGI floor for this deduction?",
    choices: {
      A: "50% of adjusted gross income",
      B: "30% of adjusted gross income",
      C: "No AGI percentage limitation applies to trust charitable deductions",
      D: "60% of modified AGI",
    },
    answer: "C",
    explanation: "Unlike the individual charitable deduction (§170), the trust and estate charitable deduction under §642(c) is not subject to AGI percentage limitations. The trust can deduct the full amount paid (or permanently set aside) for charitable purposes to the extent it is paid from gross income and pursuant to the governing instrument. However, the deduction cannot exceed the trust's gross income for the year.",
  },
  {
    id: 270,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §664, a Charitable Remainder Annuity Trust (CRAT) pays a fixed annuity to income beneficiaries. The income character of CRAT distributions to beneficiaries is determined by the 'tier system.' The correct order of income character under §664(b) is:",
    choices: {
      A: "Capital gains first, then ordinary income, then tax-exempt income, then return of corpus",
      B: "Ordinary income first, then capital gains, then tax-exempt income, then return of corpus",
      C: "Tax-exempt income first, then ordinary income, then capital gains, then return of corpus",
      D: "Return of corpus first (since the annuity represents the donor's investment)",
    },
    answer: "B",
    explanation: "The §664(b) four-tier ordering rule requires CRAT/CRUT distributions to be characterized as: (1) ordinary income to the extent of current and accumulated ordinary income, (2) capital gains (net short-term first, then net long-term), (3) tax-exempt income, and (4) return of corpus. This ordering is unfavorable to the beneficiary because ordinary income is always distributed first.",
  },
  {
    id: 271,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "The §4947(a)(1) non-exempt charitable trust (split-interest trust that devotes all assets to charitable purposes) is treated as a private foundation for most purposes. Under §4942, a private foundation must distribute what minimum percentage of net investment assets annually?",
    choices: { A: "3%", B: "5%", C: "7%", D: "10%" },
    answer: "B",
    explanation: "§4942 imposes a 30% excise tax on undistributed income of private foundations that fail to distribute at least 5% of the fair market value of net investment assets annually. 'Qualifying distributions' include grants to public charities, reasonable administrative expenses, and certain program-related investments. Private operating foundations have different distribution requirements.",
  },
  {
    id: 272,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §2056, the marital deduction for federal estate tax purposes is unlimited for property passing to a surviving spouse. Which of the following CANNOT qualify for the unlimited marital deduction?",
    choices: {
      A: "A bequest of cash to the surviving spouse outright",
      B: "A QTIP trust (Qualified Terminable Interest Property) where the surviving spouse receives all income annually",
      C: "A bypass trust where the surviving spouse has a general power of appointment",
      D: "A terminable interest passing to the surviving spouse that does not meet QTIP requirements",
    },
    answer: "D",
    explanation: "§2056(b)(1) disallows the marital deduction for 'terminable interests' — property that will terminate or fail upon the happening of an event or condition, passing to someone other than the surviving spouse. Exceptions include QTIP trusts (§2056(b)(7)) where the spouse receives all income annually and no one can appoint the property to others during the spouse's lifetime, and trusts where the spouse has a general power of appointment (§2056(b)(5)).",
  },
  {
    id: 273,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "The §2503(c) trust for minors qualifies for the annual gift tax exclusion even though the gift is to a trust (normally a future interest). The property must be distributable to the beneficiary at what age?",
    choices: { A: "18", B: "21", C: "25", D: "30" },
    answer: "B",
    explanation: "§2503(c) provides that gifts to a trust qualify as present interests (eligible for the annual exclusion) if (1) the property and income may be expended for the benefit of the minor before age 21, and (2) any remaining property passes to the minor at age 21 (or to the minor's estate if they die before 21). This allows grandparents to fund 529-like trusts while claiming the gift tax annual exclusion.",
  },
  {
    id: 274,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §2514, a general power of appointment created after October 21, 1942, is taxable when the power is exercised, released, or lapses (if lapse exceeds the '5 and 5' exception). The 5 and 5 exception allows a non-taxable lapse up to:",
    choices: {
      A: "The greater of $5,000 or 5% of the trust corpus",
      B: "The lesser of $5,000 or 5% of the trust corpus",
      C: "5% of the trust income for the year",
      D: "$5,000 flat regardless of trust size",
    },
    answer: "A",
    explanation: "§2514(e) provides that a lapse of a power of appointment is treated as a release (and thus a taxable gift) only to the extent that the value of the property that could be appointed exceeds the greater of (1) $5,000 or (2) 5% of the aggregate value of the assets subject to the power. This '5 and 5 power' is often used in bypass trusts to give the surviving spouse limited withdrawal rights without triggering estate tax.",
  },
  {
    id: 275,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Form 709 (Gift Tax Return) allows gift splitting between spouses under §2513. When spouses elect to split gifts, each is treated as making one-half of all gifts made by either spouse during the year. The election requires:",
    choices: {
      A: "Only the donor spouse to sign Form 709",
      B: "Both spouses to be U.S. citizens or residents and both to consent on Form 709",
      C: "The couple to be married for the entire calendar year",
      D: "The gifts to exceed the annual exclusion amount",
    },
    answer: "B",
    explanation: "§2513 requires both spouses to consent to gift splitting on Form 709, and both must be U.S. citizens or resident aliens at the time of the gift. The consent is irrevocable for that year and covers all gifts made during the calendar year. Couples do NOT need to be married the entire year — they only need to be married at the time of the gift and not remarried to another person by year-end.",
  },
  {
    id: 276,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §4958 (intermediate sanctions), what excise tax is imposed on a disqualified person who receives an excess benefit transaction from a §501(c)(3) or §501(c)(4) organization?",
    choices: {
      A: "10% of the excess benefit",
      B: "25% of the excess benefit (200% if not corrected)",
      C: "50% of the excess benefit",
      D: "100% of the excess benefit",
    },
    answer: "B",
    explanation: "§4958 imposes a two-tier excise tax: (1) an initial 25% tax on the disqualified person on the amount of the excess benefit, and (2) if not corrected before the IRS mails a deficiency notice (or 90 days after), an additional 200% tax on the disqualified person. Organization managers who approved the transaction knowingly face a 10% tax (capped at $20,000 per transaction). The disqualified person must also correct the excess benefit (repay with interest).",
  },
  {
    id: 277,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "The Form 5500 (Annual Return/Report of Employee Benefit Plan) must be filed by what date for a calendar-year plan?",
    choices: { A: "March 15", B: "April 15", C: "July 31 (extended to October 15)", D: "October 15" },
    answer: "C",
    explanation: "Form 5500 for calendar-year employee benefit plans is due by July 31 of the following year. A 2.5-month extension (to October 15) may be obtained by filing Form 5558 before the original July 31 due date. PBGC-insured defined benefit plans also file Schedule SB. Plans with fewer than 100 participants may file Form 5500-SF (short form). One-participant plans use Form 5500-EZ.",
  },
  {
    id: 278,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "FIRPTA (§897) treats gain from the sale of a U.S. real property interest (USRPI) by a foreign person as effectively connected income. The withholding rate on FIRPTA dispositions under §1445 is generally:",
    choices: { A: "10%", B: "15%", C: "21%", D: "30%" },
    answer: "B",
    explanation: "The §1445 withholding rate on FIRPTA dispositions is generally 15% of the amount realized. For dispositions of residences where the buyer intends to use it as a primary residence and the amount realized is $300,000–$1,000,000, the rate is 10%. If the amount realized is $300,000 or less and the buyer intends it as a primary residence, no FIRPTA withholding is required. The 15% rate applies to most commercial USRPI sales.",
  },
  {
    id: 279,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under the §1446 withholding rules for partnerships with foreign partners, a partnership must withhold on the foreign partner's allocable share of effectively connected income (ECI). The required annual withholding forms filed with the IRS are:",
    choices: {
      A: "Forms 8804, 8805, and 8813",
      B: "Forms 1042 and 1042-S only",
      C: "Form 1065 with Schedule K-1 attachment",
      D: "Form 8288 and 8288-A",
    },
    answer: "A",
    explanation: "§1446 withholding on ECI allocated to foreign partners uses: Form 8804 (Annual Return for Partnership Withholding Tax — filed by March 15, with 6-month extension), Form 8805 (Foreign Partner's Information Statement of Section 1446 Withholding Tax — given to each foreign partner and filed with 8804), and Form 8813 (Partnership Withholding Tax Payment Voucher — quarterly installments due March 15, June 15, September 15, December 15).",
  },
  {
    id: 280,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "The §2032A special-use valuation election allows qualifying real property used in farming or a closely held business to be valued at its actual-use value rather than FMV. The maximum reduction in value that may be achieved through §2032A is:",
    choices: { A: "$750,000", B: "$1,160,000 (2024 inflation-adjusted)", C: "$2,000,000", D: "No limit — full actual use value applies" },
    answer: "B",
    explanation: "§2032A(a)(2) caps the reduction in value at $750,000 base, adjusted for inflation. For 2024, the inflation-adjusted amount is $1,160,000. The property must be used in farming or a closely held business, pass to a qualified heir, and meet 50% and 25% tests based on the value of the qualified real property relative to the gross estate. If the heir disposes of the property within 10 years, recapture applies.",
  },
  {
    id: 281,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under the §4942 minimum distribution requirement for private foundations, qualifying distributions must be made by when to count toward the current year's distribution requirement?",
    choices: {
      A: "By December 31 of the taxable year",
      B: "By the end of the taxable year following the distribution year",
      C: "Within 12 months of the end of the taxable year",
      D: "By the due date of Form 990-PF including extensions",
    },
    answer: "C",
    explanation: "Under §4942, qualifying distributions made within 12 months after the end of the taxable year can be treated as made in the current year (at the foundation's election). This 'carryover' period provides flexibility in timing grants. If the foundation has undistributed income from a prior year, it must distribute that amount plus the current year's minimum within the same 12-month window to avoid the 30% excise tax.",
  },
  {
    id: 282,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Form 8027 requires large food/beverage establishments to report aggregate tips. An employer must allocate additional tips to employees when reported tips are less than what percentage of gross receipts?",
    choices: { A: "6%", B: "8%", C: "10%", D: "12%" },
    answer: "B",
    explanation: "§6053(c) and Reg. §31.6053-3 require large food/beverage establishments (more than 10 employees) to report on Form 8027 when tipped employee tips are below 8% of gross receipts. If reported tips are less than 8%, the employer must allocate the shortfall among employees as 'allocated tips' (reported on W-2 Box 8), but these are NOT subject to FICA withholding at the employer level. Employees report allocated tips on their individual returns.",
  },
  {
    id: 283,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under §6721 and §6722, penalties apply for failure to file correct information returns (e.g., 1099s, W-2s) or failure to furnish correct payee statements. For 2024, the penalty per failure for intentional disregard is:",
    choices: { A: "$100", B: "$290", C: "$630", D: "The greater of $630 or 10% of aggregate amount of items required to be reported" },
    answer: "D",
    explanation: "For intentional disregard, §6721(e) imposes a penalty of the greater of $630 per failure (2024 inflation-adjusted) or 10% of the aggregate amount of items required to be reported. The penalty for non-intentional failures is tiered: $60/failure (within 30 days), $120/failure (31 days through August 1), $310/failure (after August 1), with annual caps based on employer size. Intentional disregard has no annual cap.",
  },
  {
    id: 284,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "§6694(a) imposes a penalty on a tax return preparer who takes an unreasonable position on a return and there is a substantial understatement. The §6694(a) penalty amount is:",
    choices: {
      A: "The greater of $1,000 or 50% of the income derived by the preparer from the return",
      B: "The greater of $1,000 or 15% of the income derived by the preparer from the return",
      C: "The greater of $5,000 or 50% of the income derived by the preparer from the return",
      D: "A flat $250 per return",
    },
    answer: "B",
    explanation: "§6694(a) imposes a penalty of the greater of $1,000 or 15% of the income derived (or to be derived) from the return or claim for the position that was unreasonable. The §6694(b) willful/reckless understatement penalty is the greater of $5,000 or 75% of income derived. 'Unreasonable position' means the preparer failed to meet the substantial authority standard (or reasonable basis for disclosed positions).",
  },
  {
    id: 285,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "§7525 provides a limited privilege for communications between a taxpayer and a federally authorized tax practitioner (FATP). This privilege applies in:",
    choices: {
      A: "All civil and criminal tax matters",
      B: "Non-criminal federal tax matters before the IRS and federal courts",
      C: "Only IRS administrative proceedings, not federal court proceedings",
      D: "Criminal tax investigations and tax court proceedings only",
    },
    answer: "B",
    explanation: "§7525 extends an attorney-client-like privilege to communications with federally authorized tax practitioners (CPAs, EAs, attorneys in §7525 contexts) regarding tax advice. The privilege applies to non-criminal tax matters before the IRS and in federal court proceedings in connection with those matters. It does NOT apply to written communications in corporate tax shelters or criminal tax matters. The privilege is narrower than attorney-client privilege.",
  },

  // ── CROSS-DOMAIN (Q286–Q300) ──────────────────────────────────────────────
  {
    id: 286,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A C corporation with $2 million in pre-TCJA NOL carryforwards and $500,000 in post-2017 NOL carryforwards has $1,000,000 of taxable income in 2024 (before NOL deduction). What is the maximum NOL deduction?",
    choices: {
      A: "$1,000,000 (all income fully offset)",
      B: "$800,000 (80% of taxable income for all NOLs)",
      C: "$1,000,000 for pre-2018 NOLs (up to taxable income) plus $0 remaining for post-2017 NOLs",
      D: "Pre-2018: $1,000,000 (no 80% limit); post-2017: limited to 80% of remaining taxable income (zero remaining)",
    },
    answer: "D",
    explanation: "Pre-2018 NOLs are not subject to the 80% limitation and can offset up to 100% of taxable income. The $2M pre-2018 NOL can offset the full $1M of income. Since all income is offset by the pre-2018 NOL, there is no remaining taxable income for the post-2017 NOL to offset. The post-2017 NOL ($500,000) carries forward indefinitely for future years.",
  },
  {
    id: 287,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A §382 ownership change occurs when the percentage of stock owned by one or more 5-percent shareholders increases by more than 50 percentage points over the lowest percentage held by those shareholders during the 3-year testing period. If the §382 limitation is $300,000 per year and the corporation has $2,000,000 of NOLs, how many years of income does the corporation need to fully use the NOLs?",
    choices: { A: "5 years", B: "6.67 years", C: "7 years — the 20-year carryforward ensures full use", D: "20 years (statutory limit) — amount may not be fully used" },
    answer: "D",
    explanation: "At $300,000/year, $2,000,000 would require 6.67 years mathematically. However, pre-2018 NOLs have a 20-year carryforward limit, and post-2017 NOLs have no time limit. If the corporation cannot generate enough income (or the §382 limitation is reduced by recognized built-in losses), the NOLs could expire. At $300,000/year for 20 years = $6M maximum use — enough for $2M. But if income is insufficient to absorb the $300,000 limit each year, some NOLs may expire unused after the carryforward period ends.",
  },
  {
    id: 288,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A U.S. C corporation has a CFC subsidiary with $1,000,000 of tested income and $400,000 of QBAI. The corporation's GILTI inclusion is:",
    choices: { A: "$600,000", B: "$960,000", C: "$1,000,000", D: "$1,040,000" },
    answer: "B",
    explanation: "GILTI = net tested income − 10% of QBAI = $1,000,000 − (10% × $400,000) = $1,000,000 − $40,000 = $960,000. The routine return on tangible assets (10% of QBAI = $40,000) is subtracted from tested income to isolate the presumed intangible income. The U.S. corporation then gets a 50% §250 deduction on the $960,000 GILTI inclusion, reducing the effective rate to 10.5% (21% × 50%).",
  },
  {
    id: 289,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A partnership has §751 'hot assets' (unrealized receivables and inventory with value substantially in excess of basis). When a partner sells their interest, the §751 hot assets trigger:",
    choices: {
      A: "Capital gain treatment on the entire sale proceeds",
      B: "Ordinary income treatment for the portion of gain attributable to §751 assets",
      C: "§1245 recapture only, not ordinary income",
      D: "No special treatment — partnership interest sale is always capital",
    },
    answer: "B",
    explanation: "§741 provides capital gain/loss treatment on the sale of a partnership interest, but §751(a) overrides this for the gain attributable to unrealized receivables and substantially appreciated inventory. The selling partner must allocate the amount realized between §751 assets (ordinary income) and non-§751 assets (capital gain/loss). This prevents partners from converting ordinary income into capital gain by selling their interest.",
  },
  {
    id: 290,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "Under the Pillar Two global minimum tax framework (enacted by 130+ countries), the minimum effective tax rate is 15%. For a U.S. multinational subject to GILTI at a blended effective rate of 13%, Pillar Two's Income Inclusion Rule (IIR) would allow the parent country to impose a top-up tax of approximately:",
    choices: { A: "2% on the CFC's income", B: "2% on net tested income after the QBAI return", C: "15% flat", D: "No additional tax since GILTI already applies" },
    answer: "A",
    explanation: "Pillar Two's IIR allows the parent jurisdiction to impose a top-up tax to bring the effective tax rate to 15%. If U.S. GILTI results in a 13% effective rate on the CFC's income, the Pillar Two top-up would be approximately 2% (15% − 13%). However, the interaction between GILTI and Pillar Two is complex — the U.S. has not yet enacted Pillar Two domestically, but foreign jurisdictions may collect the top-up from U.S. multinationals under the UTPR (Undertaxed Profits Rule).",
  },
  {
    id: 291,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A taxpayer uses their personal car 60% for business and 40% personal use. The car was purchased for $50,000 and MACRS 5-year depreciation (200% DB) applies. However, §280F luxury auto limits restrict the annual depreciation deduction. For 2024, the first-year luxury auto limit for a car placed in service in 2024 without bonus depreciation is approximately:",
    choices: { A: "$3,160", B: "$12,400", C: "$20,400", D: "$12,400 × 60% business use" },
    answer: "B",
    explanation: "Under §280F, the luxury auto annual depreciation caps for passenger automobiles placed in service in 2024 are approximately $12,400 for Year 1 (without bonus depreciation), $19,800 for Year 2, $11,900 for Year 3, and $7,160 for Year 4+. The total depreciation is further reduced by the personal use percentage. With 60% business use, the deductible Year 1 amount would be $12,400 × 60% = $7,440 — but the base cap is $12,400.",
  },
  {
    id: 292,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A consolidated group has a parent with $500,000 of income and a subsidiary with a $700,000 NOL. The subsidiary's NOL may offset the consolidated group's income under the consolidated return NOL rules. However, if the group later sells the subsidiary (causing it to leave the group), what happens to the subsidiary's remaining NOL?",
    choices: {
      A: "The parent retains all NOLs since they were used to reduce consolidated tax",
      B: "The NOL goes with the subsidiary (SRLY limitations may apply to subsequent use)",
      C: "The NOL is permanently forfeited upon leaving the group",
      D: "The NOL splits proportionally between parent and subsidiary",
    },
    answer: "B",
    explanation: "Under consolidated return regulations (Reg. §1.1502-21), an NOL follows the member that generated it when that member leaves the consolidated group. However, separate return limitation year (SRLY) rules may limit how the former subsidiary can use NOLs generated during its SRLY years (pre-consolidation). The §382 limitation also applies if there was an ownership change. The NOL is NOT permanently forfeited.",
  },
  {
    id: 293,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A taxpayer owns rental real estate and a hotel business. Under §469 grouping rules, can these two activities be grouped as a single activity for passive activity purposes?",
    choices: {
      A: "Yes, if the taxpayer materially participates in both",
      B: "No — rental activities (§469(c)(2)) and non-rental activities cannot be grouped together",
      C: "Yes, with IRS consent filed on Form 8582",
      D: "Yes, as long as both activities are located in the same state",
    },
    answer: "B",
    explanation: "Reg. §1.469-4(d)(1) prohibits grouping a rental activity with a non-rental activity. Rental activities are per se passive (§469(c)(2)) and cannot be grouped with trade or business activities. However, certain rental activities may be grouped with non-rental activities when the rental is incidental to the non-rental (e.g., hotel rooms). The hotel may qualify as a non-rental activity if average rental period is 7 days or less.",
  },
  {
    id: 294,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "An S corporation shareholder has a suspended loss of $30,000 from prior years (due to basis limitation under §1366(d)) and a current-year loss of $20,000. The shareholder contributes $25,000 of capital, bringing their basis to $25,000 before the current year loss. How much total loss can the shareholder deduct in the current year?",
    choices: { A: "$20,000 (current year only)", B: "$25,000 (limited to new basis)", C: "$45,000 (suspended + current year, limited to $25,000 basis)", D: "$50,000 (total of suspended and current)" },
    answer: "B",
    explanation: "The shareholder's basis is $25,000 after the contribution. Total losses available: $30,000 suspended + $20,000 current = $50,000. However, losses are limited to the shareholder's basis at year-end. Basis = $25,000, so only $25,000 of losses may be deducted. The remaining $25,000 ($50,000 − $25,000) is again suspended under §1366(d) for future years.",
  },
  {
    id: 295,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A foreign corporation with a U.S. branch has $800,000 of ECI and $200,000 of branch interest paid to its foreign home office. Under §884, the branch profits tax rate on the dividend equivalent amount is:",
    choices: { A: "21%", B: "30%", C: "15%", D: "The same rate as dividends under the applicable tax treaty, typically 5% or 0%" },
    answer: "B",
    explanation: "§884 imposes a 30% branch profits tax (or lower treaty rate) on the 'dividend equivalent amount' — the portion of the branch's ECI that is not reinvested in U.S. assets (analogous to a dividend paid by a U.S. subsidiary to its foreign parent). Without a treaty, the rate is 30%. Many U.S. tax treaties reduce this to 5% or 0% (e.g., U.S.-Netherlands treaty). The branch interest tax under §884(f) also applies to interest paid by the branch.",
  },
  {
    id: 296,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "Under §911, U.S. citizens and resident aliens living abroad may exclude foreign earned income up to an indexed limit. For 2024, the §911 foreign earned income exclusion (FEIE) is approximately:",
    choices: { A: "$107,600", B: "$112,000", C: "$120,000", D: "$126,500" },
    answer: "D",
    explanation: "The §911 FEIE is indexed for inflation. For 2024, the exclusion is $126,500 (up from $120,000 in 2023). To qualify, the taxpayer must have foreign earned income, a tax home in a foreign country, and meet either the bona fide residence test (foreign resident for an entire tax year) or the physical presence test (330 full days in a 12-month period). The housing exclusion/deduction is in addition to the FEIE.",
  },
  {
    id: 297,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A corporation elects S status effective January 1, 2024. At conversion, it has built-in gains of $300,000 in its assets. In 2026 (Year 3 of S status), it sells the appreciated asset for its full FMV, triggering $300,000 of built-in gain. What tax does the S corporation pay?",
    choices: {
      A: "No tax — the 5-year recognition period has not passed",
      B: "$63,000 BIG tax (21% corporate rate on $300,000)",
      C: "$63,000 BIG tax at the corporate level, plus shareholders pay tax on the pass-through",
      D: "Zero because the asset was not sold within Year 1",
    },
    answer: "C",
    explanation: "The §1374 BIG tax recognition period is 5 years. Year 3 is still within the 5-year window, so the S corporation owes BIG tax at the 21% corporate rate on $300,000 = $63,000. Additionally, shareholders receive a pass-through of the remaining net gain (reduced by the BIG tax) on their K-1s and owe individual income tax on that amount. Both levels of tax apply — corporate BIG tax plus shareholder-level tax on the pass-through.",
  },
  {
    id: 298,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "For the §199A QBI deduction, a taxpayer who is above the threshold and owns an interest in an S corporation must also consider the W-2 wage limitation. If the S corporation has $500,000 of QBI, $100,000 of W-2 wages, and $800,000 of UBIA of qualified property, the QBI deduction (assuming taxpayer is above the phase-out range) is limited to the greater of:",
    choices: {
      A: "$50,000 (50% of W-2 wages) or $66,000 (25% wages + 2.5% UBIA)",
      B: "$50,000 (50% of W-2 wages) or $70,000 (25% wages + 2.5% UBIA)",
      C: "20% of QBI = $100,000 (uncapped)",
      D: "$100,000 (50% of $200,000 wages)",
    },
    answer: "A",
    explanation: "§199A limitation for above-threshold taxpayers: the deduction is the LESSER of 20% × QBI ($100,000) OR the greater of (a) 50% of W-2 wages = 50% × $100,000 = $50,000, or (b) 25% of W-2 wages + 2.5% of UBIA = $25,000 + $20,000 = $45,000. The greater of $50,000 vs. $45,000 is $50,000. QBI deduction = lesser of $100,000 or $50,000 = $50,000. The wage limitation caps the deduction at $50,000.",
  },
  {
    id: 299,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A taxpayer has both §465 at-risk losses suspended from activity A ($20,000) and §469 passive losses suspended from activity A ($15,000). The taxpayer fully disposes of activity A in a taxable transaction. In what order are the suspended losses released?",
    choices: {
      A: "§469 passive losses first, then §465 at-risk losses",
      B: "§465 at-risk losses first (increase basis), then §469 passive losses are released",
      C: "Both are released simultaneously and netted against income from disposition",
      D: "§465 losses are released only if at-risk amount becomes positive; §469 losses are released on disposition",
    },
    answer: "B",
    explanation: "The §465 at-risk and §469 passive activity rules apply in sequence. §465 at-risk limitations apply first — a loss cannot be deducted under §469 if it is first disallowed by §465. Upon full disposition, §465 at-risk losses are released first (they increase the amount at-risk, which then allows §469 suspended losses to be recognized). The §469(g) disposition rule then releases all suspended passive losses. The correct order: §465 first, then §469.",
  },
  {
    id: 300,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A multi-state corporation apportions income using the UDITPA three-factor formula (sales, property, payroll). The state of destination (market state) uses a single-sales-factor formula. If the corporation has $1,000,000 of total income, $800,000 of in-state sales (out of $2,000,000 total sales), $500,000 of in-state property (out of $1,000,000 total property), and $200,000 of in-state payroll (out of $500,000 total payroll), what is the single-sales-factor apportionment percentage?",
    choices: { A: "40%", B: "50%", C: "55%", D: "65%" },
    answer: "A",
    explanation: "Single-sales-factor apportionment = In-state sales ÷ Total sales = $800,000 ÷ $2,000,000 = 40%. Under the traditional UDITPA three-factor formula, the rate would be: Sales 40% + Property 50% + Payroll 40% = 130% ÷ 3 = 43.33%. Most states have moved to single-sales-factor (destination sourcing) to attract businesses with in-state property/payroll but out-of-state sales. 'Throwback rules' attribute sales to the seller's state when the destination state cannot tax the seller.",
  },
];
