import type { Question } from "./questions";

export const questions6: Question[] = [
  // ── DOMAIN 1: BUSINESS TAXATION ─────────────────────────────────────────────
  {
    id: 501,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §199A, which type of trade or business is a 'specified service trade or business' (SSTB) subject to the phase-out of the QBI deduction?",
    choices: {
      A: "Engineering services",
      B: "Architecture services",
      C: "Consulting services",
      D: "Real estate brokerage",
    },
    answer: "C",
    explanation: "§199A(d)(1)(B) defines SSTBs as trades or businesses involving services in fields of health, law, accounting, actuarial science, performing arts, consulting, athletics, financial services, brokerage services, or where the principal asset is the reputation/skill of one or more employees. Engineering and architecture were explicitly excluded from SSTB status. Real estate brokerage (investment) is not specifically listed. Consulting is specifically listed.",
  },
  {
    id: 502,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A married couple filing jointly has QBI of $200,000, W-2 wages from the business of $50,000, and taxable income of $450,000 in 2024 (fully above the MFJ phase-out range). The §199A QBI deduction is limited to the lesser of 20% of QBI or 50% of W-2 wages. What is their QBI deduction?",
    choices: {
      A: "$25,000",
      B: "$40,000",
      C: "$56,000",
      D: "$50,000",
    },
    answer: "A",
    explanation: "Above the 2024 MFJ phase-out ceiling ($483,900), the W-2/UBIA wage limitation applies in full. The deduction is the lesser of: (1) 20% × $200,000 QBI = $40,000, or (2) 50% × $50,000 W-2 wages = $25,000 (alternative: 25% of W-2 wages + 2.5% of UBIA of qualified property, but with no UBIA here, this is $12,500, which is less than the W-2-only limit). The lesser of $40,000 and $25,000 is $25,000. The QBI deduction is $25,000.",
  },
  {
    id: 503,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §163(j), business interest expense deduction is generally limited to the sum of business interest income plus what percentage of adjusted taxable income (ATI)?",
    choices: {
      A: "50%",
      B: "30%",
      C: "25%",
      D: "40%",
    },
    answer: "B",
    explanation: "§163(j)(1) limits the deduction for business interest expense to the sum of: (1) business interest income, (2) 30% of adjusted taxable income (ATI), and (3) floor plan financing interest. Prior to 2022, ATI included depreciation/amortization add-backs (EBITDA-based); from 2022 forward, it is EBIT-based (no add-back for D&A).",
  },
  {
    id: 504,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §382, when a corporation undergoes an ownership change, the annual §382 limitation equals the value of the loss corporation immediately before the ownership change multiplied by what rate?",
    choices: {
      A: "The applicable federal rate (AFR)",
      B: "The long-term tax-exempt rate",
      C: "The federal short-term rate",
      D: "The prime rate",
    },
    answer: "B",
    explanation: "§382(b)(1) provides that the §382 limitation equals the value of the loss corporation (immediately before the ownership change) multiplied by the long-term tax-exempt rate. This rate is published monthly by the IRS. The limitation caps the amount of pre-change NOLs (and certain built-in losses) that can be used each year after an ownership change.",
  },
  {
    id: 505,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A §338(h)(10) election allows a qualified stock purchase to be treated as an asset acquisition for tax purposes. Which of the following is a requirement for making a §338(h)(10) election?",
    choices: {
      A: "The target must be a C corporation",
      B: "The target must be an S corporation or a member of a consolidated group",
      C: "The purchaser must be an individual",
      D: "The target must have been in existence for at least 5 years",
    },
    answer: "B",
    explanation: "A §338(h)(10) election is available when the target corporation is either (1) a member of a consolidated group (C corporation), with the election made jointly by the purchasing corporation and the selling consolidated group, or (2) an S corporation, with the election made jointly by the purchaser and all S corporation shareholders. The election allows the deemed asset sale to be taxed only once at the corporate level (for consolidated targets) or only at the shareholder level (for S corps).",
  },
  {
    id: 506,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Corporation X has a §988 transaction loss of $60,000 from a foreign currency forward contract used to hedge a business receivable. How is this loss treated?",
    choices: {
      A: "Capital loss, limited to capital gains",
      B: "Ordinary loss, deductible in full",
      C: "Section 1231 loss",
      D: "Subject to the passive activity loss rules",
    },
    answer: "B",
    explanation: "§988(a)(1)(A) provides that §988 transaction gains and losses from foreign currency transactions are treated as ordinary income or loss. They are not capital gains/losses (unless a §988(a)(1)(B) election is made for certain capital asset transactions). A loss from a foreign currency forward contract used to hedge a business receivable generates an ordinary loss fully deductible against ordinary income.",
  },
  {
    id: 507,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §1060, when assets of a trade or business are acquired, the purchase price must be allocated among the acquired assets using the residual method. Which class of assets receives the allocation last under this method?",
    choices: {
      A: "Class IV — accounts receivable",
      B: "Class V — tangible personal property",
      C: "Class VI — §197 intangibles",
      D: "Class VII — goodwill and going concern value",
    },
    answer: "D",
    explanation: "The residual method under §1060 and Reg. §1.338-6 allocates purchase price among asset classes in order (I through VII), with goodwill and going concern value (Class VII) receiving any remaining residual amount after all other classes are fully allocated. This ensures goodwill captures the economic excess of purchase price over identifiable assets.",
  },
  {
    id: 508,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Partnership AB has a §754 election in effect. Partner A sells her 50% interest to Partner C for $300,000 when the partnership's adjusted basis in all assets is $400,000. The fair market value of all assets is $600,000. What is the amount of the §743(b) step-up allocated to Partner C?",
    choices: {
      A: "$100,000",
      B: "$200,000",
      C: "$150,000",
      D: "$50,000",
    },
    answer: "A",
    explanation: "Under §743(b), the transferee partner gets a special basis adjustment equal to the difference between the transferee's outside basis and the transferee's share of the partnership's inside basis. C paid $300,000 (outside basis). C's share of inside basis = 50% × $400,000 = $200,000. §743(b) adjustment = $300,000 − $200,000 = $100,000. This $100,000 step-up is allocated among partnership assets under §755.",
  },
  {
    id: 509,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §704(c), when property is contributed to a partnership with a built-in gain, how must the partnership allocate the built-in gain when the property is sold?",
    choices: {
      A: "Equally among all partners",
      B: "To the contributing partner",
      C: "To the non-contributing partners",
      D: "In proportion to each partner's interest",
    },
    answer: "B",
    explanation: "§704(c)(1)(A) requires that income, gain, loss, and deduction with respect to property contributed to a partnership be shared among the partners so as to take into account the variation between the adjusted basis of the property and its FMV at the time of contribution. This means the built-in gain (or loss) must be allocated to the contributing partner when the property is eventually sold, preventing the contributing partner from shifting pre-contribution gains to other partners.",
  },
  {
    id: 510,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Partnership CD allocates a $500,000 nonrecourse liability under §752. How is this liability allocated among partners for purposes of outside basis?",
    choices: {
      A: "Entirely to the managing partner",
      B: "Based on each partner's profit-sharing ratio",
      C: "Equally among all partners",
      D: "First to partners with deficit restoration obligations",
    },
    answer: "B",
    explanation: "Under Reg. §1.752-3, nonrecourse liabilities are allocated in three tiers: (1) minimum gain (§704(b)), (2) §704(c) minimum gain, and (3) excess nonrecourse liabilities allocated in any reasonable manner, which typically defaults to each partner's share of partnership profits. Absent specific minimum gain or §704(c) minimum gain, excess nonrecourse liabilities are allocated based on profit-sharing ratios.",
  },
  {
    id: 511,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Which of the following corporate transactions qualifies as a 'Type B' reorganization under §368(a)(1)(B)?",
    choices: {
      A: "Acquiring corporation acquires target's assets solely in exchange for the acquirer's voting stock",
      B: "Acquiring corporation acquires control of target solely in exchange for the acquirer's voting stock",
      C: "Target merges into acquirer under state law",
      D: "Target transfers assets to a newly created subsidiary of the acquirer",
    },
    answer: "B",
    explanation: "A Type B reorganization under §368(a)(1)(B) is a stock-for-stock acquisition in which the acquiring corporation acquires stock of the target corporation, using solely voting stock of the acquiring corporation (or its parent), resulting in the acquiring corporation controlling the target (80% of voting power and value). The 'solely' requirement is strict — any boot disqualifies the B reorganization.",
  },
  {
    id: 512,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §453A, a taxpayer with an installment obligation with a face amount exceeding $5 million must pay interest on the deferred tax. The interest is computed on the product of the applicable percentage of the deferred tax and what rate?",
    choices: {
      A: "The prime rate",
      B: "The underpayment rate under §6621",
      C: "The applicable federal rate",
      D: "The federal funds rate",
    },
    answer: "B",
    explanation: "§453A(c)(2) provides that the interest charge on large installment obligations (face amount > $5 million) is computed using the underpayment rate under §6621 (generally federal short-term rate + 3%). The interest is calculated on the applicable percentage of the deferred tax liability and is an addition to the regular income tax for the year.",
  },
  {
    id: 513,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "For purposes of the §461(l) excess business loss limitation, what is the threshold for excess business losses for a single taxpayer in 2024?",
    choices: {
      A: "$250,000",
      B: "$305,000",
      C: "$610,000",
      D: "$500,000",
    },
    answer: "B",
    explanation: "§461(l) disallows excess business losses for non-corporate taxpayers. The threshold for 2024 is $305,000 for single filers ($610,000 for MFJ — doubled). These amounts are inflation-adjusted annually. Losses exceeding the threshold are treated as NOL carryovers under §172 to the next year. The provision was made permanent by the Inflation Reduction Act.",
  },
  {
    id: 514,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "The Corporate Alternative Minimum Tax (CAMT) under the Inflation Reduction Act imposes a 15% minimum tax on what base?",
    choices: {
      A: "Regular taxable income",
      B: "Adjusted Financial Statement Income (AFSI)",
      C: "Alternative Minimum Taxable Income (AMTI) as under pre-2018 law",
      D: "Economic income per GAAP net income",
    },
    answer: "B",
    explanation: "The Inflation Reduction Act (2022) imposed a 15% Corporate Alternative Minimum Tax (CAMT) on Adjusted Financial Statement Income (AFSI) for 'applicable corporations' with average annual AFSI exceeding $1 billion over a 3-year period. AFSI is based on the corporation's financial statement net income, with certain adjustments. This replaced the prior AMT that was repealed by the TCJA.",
  },
  {
    id: 515,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §267, which related-party relationship triggers the loss disallowance rule?",
    choices: {
      A: "A sale between a corporation and a 10%-or-more shareholder",
      B: "A sale between an individual and a corporation where the individual owns more than 50% in value",
      C: "A sale between two corporations in the same affiliated group",
      D: "A sale between a partnership and a 20%-or-more partner",
    },
    answer: "B",
    explanation: "§267(a)(1) disallows losses on sales or exchanges between related persons. Under §267(b)(2), a corporation and a person who owns (directly or constructively) more than 50% in value of the corporation's stock are related. The >50% ownership threshold (not 10% or 20%) triggers the loss disallowance. Constructive ownership rules under §267(c) apply.",
  },
  {
    id: 516,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §1239, when a person sells depreciable property to a related person (e.g., >50% owned corporation), any gain on the sale is treated as:",
    choices: {
      A: "Long-term capital gain",
      B: "§1231 gain",
      C: "Ordinary income",
      D: "§1250 recapture",
    },
    answer: "C",
    explanation: "§1239(a) provides that if a taxpayer sells or exchanges depreciable property to a related person (as defined in §1239(b), which includes a corporation in which the taxpayer owns >50% in value), any gain recognized is treated as ordinary income — not capital gain or §1231 gain. This prevents taxpayers from converting ordinary depreciation deductions into preferentially-taxed capital gains through related-party transactions.",
  },
  {
    id: 517,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A C corporation elects S corporation status effective January 1 of the current year. It has a built-in gain of $500,000 at conversion. The S corporation sells appreciated assets within 5 years and recognizes $300,000 of built-in gain. The corporate-level tax on this built-in gain is imposed at what rate?",
    choices: {
      A: "21%",
      B: "35%",
      C: "20%",
      D: "The highest individual rate",
    },
    answer: "A",
    explanation: "Under §1374, when an S corporation sells assets during the 5-year recognition period following conversion from C corporation status, built-in gains are taxed at the highest corporate rate, which is 21% under current law (post-TCJA). The tax is imposed at the corporate level and then passed through to shareholders (who may get a deduction for the tax paid). The pre-TCJA rate was 35%.",
  },
  {
    id: 518,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under the FDII (Foreign-Derived Intangible Income) rules of §250, a domestic corporation deducts 37.5% of FDII. FDII is computed as the corporation's deemed intangible income attributable to what?",
    choices: {
      A: "Foreign sales and services",
      B: "Domestic sales only",
      C: "Exports to controlled foreign corporations",
      D: "Royalty income from foreign licensees",
    },
    answer: "A",
    explanation: "§250(b) defines FDII as the amount of deemed intangible income (deduction eligible income × deemed intangible income ratio) attributable to foreign-derived deduction eligible income (FDDEI) — i.e., income from sales of property for foreign use and services provided to foreign persons. The §250 deduction (37.5% of FDII, reduced to 21.875% after 2025) incentivizes domestic corporations to serve foreign markets rather than using offshore affiliates.",
  },
  {
    id: 519,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under the BEAT (Base Erosion and Anti-Abuse Tax) of §59A, a corporation is subject to BEAT if its base erosion percentage is at least 3% and its average annual gross receipts for the prior 3 years exceed:",
    choices: {
      A: "$50 million",
      B: "$100 million",
      C: "$500 million",
      D: "$1 billion",
    },
    answer: "C",
    explanation: "§59A imposes the BEAT on 'applicable taxpayers' — corporations (other than S corps, RICs, and REITs) with average annual gross receipts of at least $500 million for the 3 preceding tax years AND a base erosion percentage of 3% or more (2% for banks and securities dealers). The BEAT rate is 10% (rising to 12.5% after 2025) of the modified taxable income (taxable income plus base erosion payments).",
  },
  {
    id: 520,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A taxpayer purchases a $1,000,000 face-value bond for $900,000 in the secondary market (market discount bond). Under §1276, gain on disposition attributable to market discount is treated as:",
    choices: {
      A: "Capital gain",
      B: "Ordinary income",
      C: "§1231 gain",
      D: "Tax-exempt income",
    },
    answer: "B",
    explanation: "§1276(a) provides that any gain recognized on the disposition of a market discount bond is treated as ordinary income to the extent of the accrued market discount. Market discount is the difference between the face amount (or revised issue price) and the price paid in the secondary market. The ordinary income treatment prevents conversion of interest income into preferentially-taxed capital gains by purchasing bonds at a discount.",
  },
  // ── DOMAIN 2: INDIVIDUALS ──────────────────────────────────────────────────
  {
    id: 521,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §1202, non-corporate taxpayers may exclude from gross income 100% of gain from the sale of qualified small business stock (QSBS) held for more than 5 years. The maximum gain excludable per issuer is limited to the greater of $10 million or:",
    choices: {
      A: "10 times the taxpayer's adjusted basis in the stock at the time of issuance",
      B: "5 times the taxpayer's original cost",
      C: "The FMV of the stock at issuance",
      D: "20 times the taxpayer's basis",
    },
    answer: "A",
    explanation: "§1202(b)(1) limits the excludable gain to the greater of: (1) $10 million ($5 million for married individuals filing separately), or (2) 10 times the taxpayer's adjusted basis in the qualified stock as of the date of sale (generally 10× what was paid for the stock at original issuance). The 10× cap allows high-growth startups to yield very large exclusions.",
  },
  {
    id: 522,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "For §1202 QSBS to qualify, the issuing C corporation's aggregate gross assets must not exceed what amount at the time of issuance?",
    choices: {
      A: "$5 million",
      B: "$50 million",
      C: "$100 million",
      D: "$250 million",
    },
    answer: "B",
    explanation: "§1202(d)(1) requires that the issuing corporation's aggregate gross assets must not exceed $50 million at the time of or immediately after the stock issuance (and immediately thereafter) to qualify as qualified small business stock. The corporation must be a domestic C corporation, the stock must be acquired at original issuance, and the corporation must be an active qualified trade or business (SSTBs and certain financial, hospitality, and professional service businesses are excluded).",
  },
  {
    id: 523,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §1411, the Net Investment Income Tax (NIIT) is imposed at 3.8% on the lesser of (1) net investment income or (2) the excess of modified adjusted gross income over the threshold. For married filing jointly taxpayers in 2024, the MAGI threshold is:",
    choices: {
      A: "$125,000",
      B: "$200,000",
      C: "$250,000",
      D: "$300,000",
    },
    answer: "C",
    explanation: "§1411(b)(2) sets the MAGI threshold for the NIIT at $250,000 for married filing jointly taxpayers ($200,000 for single/head of household, $125,000 for married filing separately). These thresholds are not inflation-adjusted. The 3.8% NIIT applies to the lesser of NII or the MAGI excess above the threshold.",
  },
  {
    id: 524,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "An individual taxpayer exercises an Incentive Stock Option (ISO) and purchases 1,000 shares at the exercise price of $10/share (FMV = $50/share). The taxpayer holds the shares for 2 years and then sells for $70/share. What is the tax treatment of the $60,000 gain ($70K - $10K)?",
    choices: {
      A: "All ordinary income",
      B: "All long-term capital gain",
      C: "$40,000 ordinary income, $20,000 long-term capital gain",
      D: "All short-term capital gain",
    },
    answer: "B",
    explanation: "ISOs qualifying under §422 require: (1) holding the stock >2 years from grant date AND >1 year from exercise date. If both holding periods are met, the entire gain on disposition qualifies as long-term capital gain — no ordinary income on exercise or sale (though the §83 spread at exercise is an AMT preference item). The taxpayer held 2 years from grant and presumably >1 year from exercise, so $60,000 is all LTCG.",
  },
  {
    id: 525,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer exercises an ISO and acquires shares with a spread (FMV over exercise price) of $80,000. For Alternative Minimum Tax (AMT) purposes, this spread is:",
    choices: {
      A: "Excluded from AMT entirely",
      B: "An AMT preference item added to AMTI",
      C: "Deductible for AMT",
      D: "Taxed at the regular tax rate immediately",
    },
    answer: "B",
    explanation: "Under §56(b)(3), the exercise of an ISO creates an AMT adjustment equal to the spread (FMV minus exercise price) at the time of exercise. This spread is included in Alternative Minimum Taxable Income (AMTI) as a preference item, even though no regular tax is owed on the ISO exercise. This is a significant AMT trap for taxpayers who exercise ISOs in high-value startup scenarios.",
  },
  {
    id: 526,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §83(b), a taxpayer who receives property subject to a substantial risk of forfeiture may elect to include the value of the property in gross income in the year of receipt rather than waiting until vesting. The election must be made within:",
    choices: {
      A: "30 days of transfer",
      B: "60 days of transfer",
      C: "The due date of the tax return",
      D: "90 days of transfer",
    },
    answer: "A",
    explanation: "§83(b) allows an election to include the fair market value of restricted property in gross income in the year received (rather than at vesting). Under Reg. §1.83-2(b), the election must be made no later than 30 days after the date the property was transferred to the taxpayer. The election must be filed with the IRS and a copy provided to the employer.",
  },
  {
    id: 527,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §409A, a nonqualified deferred compensation arrangement that fails to comply results in:",
    choices: {
      A: "The deferred amount being included in income only when paid",
      B: "Immediate inclusion of the deferred amount, plus a 20% additional tax, plus interest",
      C: "A 10% early withdrawal penalty similar to IRAs",
      D: "No consequences if the plan is corrected within 60 days",
    },
    answer: "B",
    explanation: "§409A(a)(1)(B) provides that if a nonqualified deferred compensation plan fails to meet the §409A requirements (relating to timing of deferrals and distributions), all amounts deferred under the plan for the taxable year and all preceding taxable years are immediately included in gross income, subject to a 20% additional tax (on top of regular income tax), plus an underpayment interest charge from the date of deferral. §409A is extremely punitive for non-compliance.",
  },
  {
    id: 528,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "A taxpayer contributes property with a FMV of $200,000 and a basis of $50,000 to a Charitable Remainder Unitrust (CRUT). The CRUT sells the property and pays a 5% annuity to the taxpayer for 20 years. The charitable deduction is based on:",
    choices: {
      A: "The FMV of the property contributed ($200,000)",
      B: "The taxpayer's basis in the property ($50,000)",
      C: "The present value of the remainder interest passing to charity",
      D: "The total of all unitrust payments to be received",
    },
    answer: "C",
    explanation: "A Charitable Remainder Trust (CRT) under §664 allows a deduction only for the present value of the remainder interest that will eventually pass to charity. This is computed using IRS actuarial tables (7520 rate) based on the payout rate, term, and §7520 rate. The taxpayer cannot deduct the full FMV of the contributed property — only the actuarially-determined present value of the charitable remainder.",
  },
  {
    id: 529,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer participates in a Grantor Retained Annuity Trust (GRAT). If the trust assets appreciate at a rate exceeding the §7520 rate, what is the estate/gift tax outcome?",
    choices: {
      A: "The excess appreciation is included in the grantor's estate",
      B: "The excess appreciation passes to remaindermen gift-tax free",
      C: "The entire trust is included in the taxable estate",
      D: "Gift tax is owed on the excess appreciation annually",
    },
    answer: "B",
    explanation: "A GRAT (§2702) is structured so that the grantor retains an annuity for a fixed term and the remainder passes to heirs. The taxable gift at creation is the FMV of trust assets minus the present value of retained annuity (using §7520 rate). If assets outperform the §7520 rate, all excess appreciation passes to remaindermen completely transfer-tax free. This 'zeroed-out' GRAT technique is a powerful estate planning tool.",
  },
  {
    id: 530,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §2503(c), a gift to a trust for a minor qualifies for the annual gift tax exclusion if the trust property and income may be used for the minor's benefit before age 21, and any unexpended property must pass to the minor at what age?",
    choices: {
      A: "18",
      B: "21",
      C: "25",
      D: "30",
    },
    answer: "B",
    explanation: "§2503(c) allows gifts to trusts for minors to qualify for the annual gift tax exclusion (present interest requirement) if: (1) the trust corpus and income may be expended by or for the minor before age 21, and (2) any unexpended trust property passes to the minor upon reaching age 21 (or to the minor's estate/appointees if the minor dies before 21). The age-21 threshold is statutory.",
  },
  {
    id: 531,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A surviving spouse inherits an IRA from a deceased spouse who was age 75 at death. The surviving spouse (age 68) elects to treat the inherited IRA as their own IRA. The surviving spouse's required beginning date for RMDs will be based on:",
    choices: {
      A: "April 1 of the year after the deceased spouse turned 73",
      B: "April 1 of the year the surviving spouse turns 73",
      C: "Immediately upon inheriting",
      D: "10 years after the deceased spouse's death",
    },
    answer: "B",
    explanation: "When a surviving spouse elects to treat an inherited IRA as their own IRA (spousal rollover/assumption), the IRA is treated as if it were always the surviving spouse's own IRA. The surviving spouse's RMD rules apply: the required beginning date is April 1 of the year following the year the surviving spouse turns 73 (under SECURE 2.0). This is the primary advantage of the spousal IRA assumption — the younger spouse can defer RMDs longer.",
  },
  {
    id: 532,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §72(t), a 10% additional tax applies to early distributions from a qualified retirement plan. Which of the following is NOT an exception to the 10% penalty?",
    choices: {
      A: "Distributions upon separation from service at age 55 or later",
      B: "Distributions to pay for higher education expenses",
      C: "Substantially equal periodic payments under §72(t)(2)(A)(iv)",
      D: "Distributions made after the participant becomes disabled",
    },
    answer: "B",
    explanation: "The higher education expense exception under §72(t)(2)(E) applies only to IRAs, not to qualified employer plans (401(k), 403(b), etc.). For qualified employer plan distributions, the exceptions include: separation from service at age 55+, QDRO distributions, disability, death, medical expenses, SEPP (substantially equal periodic payments), and others — but NOT higher education expenses. That exception is IRA-specific.",
  },
  {
    id: 533,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under the SECURE 2.0 Act (2022), a Roth SEP IRA was authorized. For a 2024 Roth SEP IRA contribution, what is the maximum contribution limit (employer contribution) as a percentage of compensation?",
    choices: {
      A: "15%",
      B: "20%",
      C: "25%",
      D: "15% for employees, 20% for self-employed",
    },
    answer: "C",
    explanation: "SECURE 2.0 authorized Roth contributions to SEP IRAs (§408A(f)). The contribution limits for Roth SEP IRAs are the same as regular SEP IRAs: up to 25% of compensation (20% for self-employed after deducting the employer's self-employment tax deduction), capped at $69,000 for 2024. This allows high-income self-employed individuals and business owners to make Roth contributions at the SEP IRA level.",
  },
  {
    id: 534,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §415(c), the annual additions limit for a defined contribution plan in 2024 is:",
    choices: {
      A: "$23,000",
      B: "$46,000",
      C: "$69,000",
      D: "$76,500",
    },
    answer: "C",
    explanation: "§415(c) limits annual additions to a participant's defined contribution plan account to the lesser of 100% of compensation or $69,000 for 2024 (plus $7,500 catch-up for those age 50+, bringing the total to $76,500 with catch-up). The $23,000 is the 2024 elective deferral limit for §401(k) plans. The §415(c) limit covers all employer and employee contributions combined.",
  },
  {
    id: 535,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §416 top-heavy plan rules, a defined contribution plan is top-heavy if the present value of accrued benefits for 'key employees' exceeds what percentage of the total present value of all accrued benefits?",
    choices: {
      A: "50%",
      B: "60%",
      C: "70%",
      D: "80%",
    },
    answer: "B",
    explanation: "§416(g)(1)(A) defines a defined contribution plan as top-heavy if the aggregate account balances of key employees exceed 60% of the aggregate account balances of all employees (including former employees). If a plan is top-heavy, minimum contributions of 3% of compensation must be made for all non-key employees, even if they make no elective deferrals themselves.",
  },
  {
    id: 536,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "A taxpayer age 52 contributes $7,000 to a traditional IRA for 2024. The taxpayer is also covered by an employer-sponsored retirement plan. The 2024 MAGI phase-out range for deductible traditional IRA contributions for a single taxpayer covered by a workplace plan is:",
    choices: {
      A: "$73,000–$83,000",
      B: "$77,000–$87,000",
      C: "$87,000–$97,000",
      D: "$68,000–$78,000",
    },
    answer: "B",
    explanation: "For 2024, the MAGI phase-out range for deductible traditional IRA contributions for a single taxpayer (or head of household) who is an active participant in an employer-sponsored retirement plan is $77,000–$87,000. The deduction phases out ratably over this range and is completely eliminated above $87,000. These limits are adjusted annually for inflation.",
  },
  {
    id: 537,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer owns rental property worth $600,000 with a $200,000 mortgage. The property has accumulated $150,000 of suspended passive losses. The taxpayer sells the property for $600,000. What happens to the suspended passive losses?",
    choices: {
      A: "They are permanently lost",
      B: "They are allowed in full in the year of sale",
      C: "They can only offset passive income in future years",
      D: "They convert to capital losses",
    },
    answer: "B",
    explanation: "§469(g)(1) provides that when a taxpayer disposes of an entire interest in a passive activity in a fully taxable transaction (not to a related party), all suspended passive activity losses from that activity are allowed in full in the year of disposition. The suspended losses first offset any gain from the activity, then any remaining suspended losses can offset other income (active, portfolio, or other passive income) without limitation.",
  },
  {
    id: 538,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §469, the 'material participation' standard for real estate professionals requires that more than half of the taxpayer's personal services during the year are in real property trades or businesses, AND the taxpayer must perform more than how many hours of services in those businesses?",
    choices: {
      A: "500 hours",
      B: "750 hours",
      C: "1,000 hours",
      D: "1,500 hours",
    },
    answer: "B",
    explanation: "§469(c)(7)(B) provides that a taxpayer qualifies as a real estate professional (and thus rental activities are not per se passive) if: (1) more than one-half of the personal services performed during the year are in real property trades or businesses in which the taxpayer materially participates, AND (2) the taxpayer performs more than 750 hours of services during the year in those real property trades or businesses.",
  },
  {
    id: 539,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer has $10,000 of market discount on a bond purchased in the secondary market. The taxpayer elects under §1278 to include market discount in income currently (accrual method election). What is the tax character of this accrued market discount?",
    choices: {
      A: "Capital gain",
      B: "Ordinary income",
      C: "Investment income (but not NII for NIIT)",
      D: "Tax-exempt income",
    },
    answer: "B",
    explanation: "Under §1278(b), a taxpayer may elect to include market discount in gross income on a current basis as it accrues. The accrued market discount is treated as ordinary income (similar to interest income) rather than capital gain. Without the election, market discount is recognized as ordinary income only upon disposition (§1276). Making the election avoids a lump-sum ordinary income inclusion at sale but generates ordinary income each year.",
  },
  {
    id: 540,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "A taxpayer performs a Roth IRA conversion of $100,000 in 2024. The conversion amount is:",
    choices: {
      A: "Tax-free if the taxpayer is under age 59½",
      B: "Included in gross income as ordinary income, but not subject to the 10% early withdrawal penalty",
      C: "Subject to the 10% early withdrawal penalty on the full $100,000",
      D: "Deductible as a retirement contribution",
    },
    answer: "B",
    explanation: "A Roth conversion under §408A(d)(3) requires the converted amount to be included in gross income as ordinary income in the year of conversion (to the extent it represents pre-tax dollars). However, the 10% early withdrawal penalty under §72(t) does not apply to Roth conversions — the conversion is not treated as a distribution for penalty purposes. If the taxpayer later withdraws the converted amount within 5 years and is under 59½, the penalty may apply.",
  },
  // ── DOMAIN 3: REPRESENTATION, PRACTICES & PROCEDURES ──────────────────────
  {
    id: 541,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under Circular 230 §10.22, a practitioner must exercise due diligence in preparing tax returns. If a practitioner relies on work product prepared by another practitioner, the practitioner:",
    choices: {
      A: "Has no responsibility for errors in the work product",
      B: "Must independently verify all computations",
      C: "Must review the work product and not ignore errors",
      D: "Is fully liable for all errors in the other practitioner's work",
    },
    answer: "C",
    explanation: "Circular 230 §10.22(b) provides that a practitioner who relies on the work product of another person must use reasonable care with respect to that work product. The practitioner cannot 'knowingly' rely on false information and must not ignore evident errors. The practitioner does not need to independently verify every computation, but must exercise appropriate professional skepticism and not be willfully blind to obvious errors.",
  },
  {
    id: 542,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §6330, a taxpayer who receives a Final Notice of Intent to Levy has how many days to request a Collection Due Process (CDP) hearing?",
    choices: {
      A: "10 days",
      B: "30 days",
      C: "45 days",
      D: "60 days",
    },
    answer: "B",
    explanation: "§6330(a)(3)(B) requires the IRS to provide at least 30 days' notice before proceeding with a levy action. The taxpayer has 30 days from the date of the CDP notice to request a CDP hearing with Appeals. After the 30-day period, the taxpayer may still request an 'equivalent hearing,' but loses the right to judicial review in Tax Court.",
  },
  {
    id: 543,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A taxpayer owes $75,000 in taxes and wants to enter a payment plan. Which type of installment agreement allows the IRS to approve without reviewing the taxpayer's financial information if the taxpayer can pay within 72 months?",
    choices: {
      A: "Partial Pay Installment Agreement",
      B: "Streamlined Installment Agreement",
      C: "Guaranteed Installment Agreement",
      D: "In-Business Trust Fund Express Agreement",
    },
    answer: "B",
    explanation: "The Streamlined Installment Agreement allows taxpayers with up to $50,000 in combined tax, penalties, and interest to obtain an installment agreement without providing financial information (Form 433-A/B), as long as they can pay within 72 months. For balances between $50,000–$100,000, a longer streamlined IA (84 months) may be available. Guaranteed IAs are for balances under $10,000.",
  },
  {
    id: 544,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §7602, the IRS has authority to issue a summons to examine records. Which of the following is NOT a valid basis for a taxpayer to resist a §7602 summons?",
    choices: {
      A: "Attorney-client privilege",
      B: "Tax practitioner privilege under §7525",
      C: "Fourth Amendment unreasonable search protections",
      D: "The taxpayer's tax liability has already been fully paid",
    },
    answer: "D",
    explanation: "§7602(a) authorizes the IRS to summon records for 'ascertaining the correctness of any return, making a return where none has been made, determining the liability of any person, or collecting any tax.' Valid defenses include attorney-client privilege, §7525 practitioner-client privilege (for non-criminal tax advice), and Fifth Amendment protections. However, the fact that tax has already been paid does not preclude the IRS from examining whether the return was correct. The IRS can still audit fully-paid returns.",
  },
  {
    id: 545,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under §7491, the burden of proof shifts to the IRS in any court proceeding if the taxpayer introduces credible evidence with respect to any factual issue relevant to tax liability AND the taxpayer has:",
    choices: {
      A: "Filed all required tax returns and cooperated with IRS requests for information",
      B: "Paid the disputed tax in full before filing suit",
      C: "Hired a licensed CPA to represent them",
      D: "Filed a refund claim within 3 years of the return",
    },
    answer: "A",
    explanation: "§7491(a)(2) provides that the burden of proof shifts to the IRS if the taxpayer: (1) introduces credible evidence, (2) complied with all substantiation requirements, (3) maintained all required records, and (4) cooperated with reasonable requests from the IRS for information, witnesses, documents, meetings, and interviews. Merely introducing evidence isn't enough — the taxpayer must have fully cooperated. The IRS retains the burden with respect to penalties under §7491(c).",
  },
  {
    id: 546,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under Circular 230 §10.35, a 'covered opinion' is a written advice that includes a reliance opinion, a marketed opinion, or advice on a listed transaction. What percentage of the penalty for aiding and abetting understatement of tax (§6701) applies to the tax return preparer?",
    choices: {
      A: "25% of the understatement",
      B: "$1,000 for each document ($10,000 for corporation returns)",
      C: "The lesser of $1,000 or 50% of income from the activity",
      D: "$250 per return",
    },
    answer: "B",
    explanation: "§6701 imposes a penalty on any person who aids, assists in, or advises with respect to preparation of a tax document that understates tax liability. The penalty is $1,000 per document, except if the document relates to a corporation's tax liability, the penalty is $10,000. The penalty applies regardless of the amount of the understatement.",
  },
  {
    id: 547,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "A taxpayer files a joint return with their spouse and later discovers the spouse omitted $50,000 of income. The taxpayer may qualify for 'innocent spouse' relief under §6015(b) if the taxpayer can show they did not know and had no reason to know of the understatement AND it would be inequitable to hold them liable. This relief must generally be requested within:",
    choices: {
      A: "2 years of the date the IRS first began collection activity",
      B: "3 years of the return filing date",
      C: "The statute of limitations for assessment",
      D: "6 months of receiving an IRS notice",
    },
    answer: "A",
    explanation: "Under §6015(b)(1)(E) and Rev. Proc. 2013-34, a request for innocent spouse relief under §6015(b) must be filed no later than 2 years after the date the IRS first began collection activity against the requesting spouse. For equitable relief under §6015(f), the IRS extended the deadline to the period of limitations on collection (10 years from assessment). The 2-year rule applies specifically to traditional innocent spouse relief.",
  },
  {
    id: 548,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under the OIC (Offer in Compromise) program, the IRS generally rejects an offer if the taxpayer can pay the liability through an installment agreement or if the offer amount is less than the 'reasonable collection potential' (RCP). The RCP is generally calculated as:",
    choices: {
      A: "Annual income × 10",
      B: "Net realizable equity in assets plus future income",
      C: "Total assets at fair market value",
      D: "Gross income × 5",
    },
    answer: "B",
    explanation: "The Reasonable Collection Potential (RCP) = Net realizable equity in assets (FMV of assets minus 20% and allowable liabilities) + the present value of future income (monthly disposable income × the multiplier based on payment terms: 12 for lump sum, 24 for short-term deferred, or applicable months for periodic payment). This is the minimum the IRS will accept in an OIC. Offers below RCP are generally rejected.",
  },
  {
    id: 549,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "An enrolled agent representing a taxpayer before the IRS receives information during the representation that the taxpayer has committed tax fraud in prior years not related to the current matter. Under Circular 230, what must the enrolled agent do?",
    choices: {
      A: "Immediately report the fraud to the IRS",
      B: "Withdraw from representing the taxpayer and report the fraud",
      C: "Continue the representation but refuse to assist with new fraudulent returns",
      D: "Advise the taxpayer of the situation and consider withdrawal; do not volunteer information to the IRS",
    },
    answer: "D",
    explanation: "Under Circular 230 §10.20 and §10.21, an enrolled agent has no affirmative duty to report a client's past fraud to the IRS (unlike in some state bar rules for attorneys). The EA must advise the client of the potential legal consequences and the EA's obligation not to assist in further non-compliance. The EA should consider withdrawal if the client refuses to rectify the situation. Voluntarily reporting client information without client consent would violate §7216.",
  },
  {
    id: 550,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Form 8938 (FATCA) must be filed by specified individuals whose aggregate value of specified foreign financial assets exceeds the applicable threshold. For a U.S. resident single taxpayer, the filing threshold is:",
    choices: {
      A: "$10,000 at any time during the year",
      B: "$50,000 at year end or $75,000 at any time during the year",
      C: "$100,000 at year end",
      D: "$200,000 at year end or $300,000 at any time during the year",
    },
    answer: "B",
    explanation: "Under §6038D and Reg. §1.6038D-2, a specified individual who is a U.S. resident must file Form 8938 if the aggregate value of specified foreign financial assets exceeds $50,000 on the last day of the tax year OR $75,000 at any time during the tax year (for single or MFS filers). Higher thresholds apply for MFJ filers ($100,000/$150,000) and U.S. residents abroad ($200,000/$300,000 for single; $400,000/$600,000 for MFJ abroad).",
  },
  // ── DOMAIN 1 CONTINUED ──────────────────────────────────────────────────────
  {
    id: 551,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §1274, interest on a seller-financed obligation with a stated interest rate below the applicable federal rate (AFR) is subject to OID rules. The amount of OID equals:",
    choices: {
      A: "The total interest payments minus the AFR-based interest",
      B: "The excess of the principal amount over the present value of all payments, discounted at the AFR",
      C: "The difference between the purchase price and the FMV of the property",
      D: "15% of the annual interest payments",
    },
    answer: "B",
    explanation: "Under §1274, if a debt instrument issued for property has an unstated or below-market interest rate, the issue price is determined by discounting all payments using the AFR. OID = stated redemption price at maturity (sum of all payments) minus issue price (present value of all payments at AFR). This recharacterizes a portion of principal repayments as interest income to the lender and interest deduction to the borrower.",
  },
  {
    id: 552,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A U.S. corporation transfers appreciated property to a foreign subsidiary in an outbound transfer. Under §367(a), the gain recognized on this outbound transfer is treated as:",
    choices: {
      A: "Capital gain at preferential rates",
      B: "Ordinary income",
      C: "§1231 gain",
      D: "Exempt from U.S. tax under the territorial system",
    },
    answer: "B",
    explanation: "§367(a)(1) provides that if a U.S. person transfers property to a foreign corporation in a §332, §351, §354, §355, or §356 exchange, the foreign corporation shall not be considered a corporation for purposes of determining the applicability of the non-recognition rules — meaning the transaction is fully taxable. Any gain recognized under §367(a) is treated as ordinary income (not capital gain), because the transfer is treated as a sale to a non-corporation.",
  },
  {
    id: 553,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §1248, when a U.S. shareholder sells stock of a controlled foreign corporation (CFC), gain on the sale is recharacterized as a dividend to the extent of:",
    choices: {
      A: "The CFC's current-year earnings and profits only",
      B: "The CFC's accumulated earnings and profits attributable to the selling shareholder's period of CFC ownership",
      C: "The CFC's total assets",
      D: "The entire gain regardless of E&P",
    },
    answer: "B",
    explanation: "§1248(a) provides that if a U.S. shareholder sells stock of a CFC, the gain is included in gross income as a dividend to the extent of accumulated E&P of the CFC attributable to the stock during the period the U.S. person held the stock while the corporation was a CFC. This prevents U.S. shareholders from converting ordinary dividend income (which would be Subpart F) into preferentially-taxed capital gain by selling the CFC stock.",
  },
  {
    id: 554,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A domestic corporation makes a §986(a) election to use the average exchange rate for translating foreign income taxes paid by its CFC. What exchange rate does §986(a) require for translating these taxes?",
    choices: {
      A: "The spot rate at the date the taxes were paid",
      B: "The average exchange rate for the taxable year",
      C: "The year-end exchange rate",
      D: "The rate at which the corresponding income was translated",
    },
    answer: "B",
    explanation: "§986(a)(1) provides that foreign income taxes paid or accrued by a CFC shall be translated into dollars using the average exchange rate for the taxable year to which the taxes relate. This contrasts with §986(b) for §902 deemed-paid credits, which uses the average rate for the year the earnings were accumulated. The average rate rule simplifies compliance compared to tracking spot rates for each tax payment.",
  },
  {
    id: 555,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §965 (the 'transition tax'), U.S. shareholders of specified foreign corporations were required to include in income their share of post-1986 accumulated foreign E&P as of November 2, 2017 or December 31, 2017. The reduced rate for E&P held in cash equivalents was:",
    choices: {
      A: "8%",
      B: "10%",
      C: "15.5%",
      D: "21%",
    },
    answer: "C",
    explanation: "§965 imposed a mandatory inclusion (deemed repatriation) of post-1986 accumulated foreign E&P with a mandatory deduction that effectively reduced the tax rate. Cash and cash equivalents were taxed at an effective rate of 15.5%, while illiquid assets (non-cash) were taxed at an effective rate of 8%. This one-time transition tax was paid over 8 years and was designed to transition to the TCJA's modified territorial system.",
  },
  {
    id: 556,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §168(k) bonus depreciation, what percentage of qualified property placed in service in calendar year 2024 can be immediately expensed?",
    choices: {
      A: "100%",
      B: "80%",
      C: "60%",
      D: "40%",
    },
    answer: "C",
    explanation: "Under the TCJA phase-down schedule, §168(k) bonus depreciation is: 100% for 2018–2022, 80% for 2023, 60% for 2024, 40% for 2025, and 20% for 2026. Property placed in service in 2024 qualifies for 60% bonus depreciation. The phase-down applies to the depreciable cost of qualifying property, with the remaining 40% depreciated using regular MACRS schedules.",
  },
  {
    id: 557,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A partnership distributes property to a partner in a liquidating distribution. Under §731(a), gain is recognized by the distributee partner only if:",
    choices: {
      A: "The FMV of the distributed property exceeds the partner's outside basis",
      B: "The partner receives money (including deemed money) in excess of the partner's outside basis",
      C: "The distributed property has a built-in gain at the partnership level",
      D: "The partnership has current-year income exceeding the distribution",
    },
    answer: "B",
    explanation: "Under §731(a)(1), gain is recognized by a partner in a partnership distribution only to the extent money (including the partner's share of any reduction in partnership liabilities treated as money under §752) distributed exceeds the partner's adjusted outside basis in the partnership interest. Distributions of property other than money do not trigger gain recognition — the partner takes a carryover or substituted basis in the property.",
  },
  {
    id: 558,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Which type of §351 transfer to a controlled corporation results in the transferor recognizing gain?",
    choices: {
      A: "Transfer of appreciated property for stock only",
      B: "Transfer of property for stock plus boot (cash or other property)",
      C: "Transfer of property for stock by a controlling group of five transferors",
      D: "Transfer of services for stock",
    },
    answer: "B",
    explanation: "§351 provides non-recognition treatment for transfers to a controlled corporation (≥80% by vote and value) in exchange for stock. However, §351(b) provides that if the transferor also receives 'boot' (money or other property not qualifying as stock), gain is recognized to the extent of the boot received. Loss is never recognized under §351, even if boot is received. Transfers of services for stock are always taxable (§351 does not cover services).",
  },
  {
    id: 559,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "For purposes of §1031 like-kind exchange, which of the following does NOT qualify as like-kind exchange property?",
    choices: {
      A: "Office building exchanged for an industrial warehouse",
      B: "Farmland exchanged for commercial retail property",
      C: "Rental condominium exchanged for raw land",
      D: "Partnership interest exchanged for real property",
    },
    answer: "D",
    explanation: "Post-TCJA (effective 2018), §1031 like-kind exchanges are limited to real property. All real property held for investment or business use is generally 'like-kind' to other real property (office building, farmland, rental condo, raw land all qualify as like-kind to each other). However, §1031(a)(2)(D) explicitly excludes partnership interests from like-kind exchange treatment — a partnership interest exchanged for real property is a taxable transaction.",
  },
  {
    id: 560,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "In a §1031 exchange involving debt relief and boot received, a taxpayer exchanges property with a $500,000 FMV, $200,000 basis, and $100,000 mortgage for replacement property worth $450,000, assuming a $50,000 mortgage. What is the recognized gain?",
    choices: {
      A: "$0",
      B: "$50,000",
      C: "$100,000",
      D: "$300,000",
    },
    answer: "B",
    explanation: "Boot = net debt relief = $100,000 (debt given up) − $50,000 (debt assumed) = $50,000 net boot (plus no cash). The realized gain = $500,000 − $200,000 = $300,000. Recognized gain = lesser of boot ($50,000) or realized gain ($300,000) = $50,000. The remaining $250,000 of gain is deferred. Debt relief is treated as boot in §1031 exchanges under §1031(b).",
  },
  // ── DOMAIN 2 CONTINUED ──────────────────────────────────────────────────────
  {
    id: 561,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §1033, a taxpayer's investment real property is condemned. The taxpayer realizes $600,000 from the condemnation and has a $200,000 basis. To defer all gain under §1033(g), within what period must the taxpayer acquire like-kind replacement property?",
    choices: {
      A: "1 year from the date of condemnation",
      B: "2 years from the end of the first tax year in which gain is realized",
      C: "3 years from the end of the first tax year in which gain is realized",
      D: "4 years from the end of the first tax year in which gain is realized",
    },
    answer: "C",
    explanation: "§1033(g)(4) provides a special 3-year replacement period for real property held for productive use in a trade or business or for investment that is compulsorily or involuntarily converted. This is longer than the standard 2-year replacement period under §1033(a)(2)(B). The replacement property must be 'like-kind' real property. The period begins on the date of the conversion (or threat/imminence of conversion) and ends 3 years after the close of the first taxable year in which any part of the gain is realized.",
  },
  {
    id: 562,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer sells their primary residence after living there for 18 months. The taxpayer was forced to sell due to a change in place of employment. Under §121(c), what is the maximum exclusion available?",
    choices: {
      A: "$0 — the 2-year requirement was not met",
      B: "75% of $250,000 = $187,500",
      C: "$250,000 — full exclusion",
      D: "50% of $250,000 = $125,000",
    },
    answer: "B",
    explanation: "§121(c)(1) allows a reduced maximum exclusion when a taxpayer fails to meet the 2-year use/ownership test but the sale is due to: (1) change in employment, (2) health, or (3) unforeseen circumstances. The reduced exclusion = (months of use/24) × $250,000 (or $500,000 for MFJ). For 18 months of use: 18/24 × $250,000 = $187,500 for a single taxpayer.",
  },
  {
    id: 563,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §1045, a taxpayer who sells QSBS within the 5-year holding period may roll over the proceeds into new QSBS without recognizing gain. The rollover purchase must occur within:",
    choices: {
      A: "30 days before or after the sale",
      B: "45 days before or after the sale",
      C: "60 days after the sale",
      D: "180 days after the date of the sale",
    },
    answer: "C",
    explanation: "§1045 allows non-corporate taxpayers to roll over gain from the sale of QSBS (held for more than 6 months but less than 5 years) by reinvesting in new QSBS within 60 days after the date of sale. The gain is deferred, and the basis in the new QSBS is reduced by the deferred gain. This provision enables investors to maintain the QSBS exclusion timeline by transitioning between qualifying investments.",
  },
  {
    id: 564,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer has net long-term capital gains of $50,000 and is in the 22% ordinary income tax bracket (taxable income of $95,000, single filer). What is the federal tax rate applicable to the $50,000 LTCG in 2024?",
    choices: {
      A: "0%",
      B: "15%",
      C: "20%",
      D: "22%",
    },
    answer: "B",
    explanation: "For 2024, the 0% LTCG rate applies to taxable income up to $47,025 (single filers), the 15% rate applies from $47,025 to $518,900, and the 20% rate applies above $518,900. A single taxpayer with $95,000 taxable income is well within the 15% LTCG bracket, so all $50,000 of LTCG is taxed at 15% (regardless of being in the 22% ordinary income bracket).",
  },
  {
    id: 565,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §1(h), 'unrecaptured §1250 gain' from the sale of a depreciated real property is taxed at a maximum rate of:",
    choices: {
      A: "15%",
      B: "20%",
      C: "25%",
      D: "28%",
    },
    answer: "C",
    explanation: "§1(h)(1)(D) provides that unrecaptured §1250 gain (the portion of §1231 gain attributable to depreciation on real property that would have been §1250 recapture if all depreciation were subject to recapture, but isn't because real property uses straight-line depreciation) is taxed at a maximum rate of 25%. This is a special rate category between ordinary income rates and the preferential 0%/15%/20% LTCG rates.",
  },
  {
    id: 566,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer contributes $6,000 to a Roth IRA in 2024 but their MAGI exceeds the Roth IRA phase-out ceiling ($161,000 for single filers in 2024). The taxpayer makes a 'backdoor Roth IRA' contribution using a non-deductible traditional IRA contribution followed by a Roth conversion. What rule applies to determine the taxable portion of the conversion?",
    choices: {
      A: "Only the converted amount is taxable",
      B: "The pro-rata rule applies across all traditional IRAs including SEP and SIMPLE IRAs",
      C: "The conversion is entirely tax-free since the contribution was non-deductible",
      D: "The FIFO rule applies — contributions come out first",
    },
    answer: "B",
    explanation: "When a taxpayer converts a non-deductible traditional IRA contribution to Roth, the pro-rata rule under §72(e)(8) applies across ALL of the taxpayer's traditional, SEP, and SIMPLE IRA accounts combined. The taxable portion = (pre-tax IRA balances / total IRA balances) × conversion amount. If a taxpayer has other pre-tax IRA funds, the 'backdoor Roth' becomes partially taxable. Only if the taxpayer has no other pre-tax IRA funds is the conversion entirely tax-free.",
  },
  {
    id: 567,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §1014, the basis of property inherited from a decedent is generally the fair market value on the date of death. Which of the following is an exception to this 'stepped-up' basis rule?",
    choices: {
      A: "Property in an irrevocable trust established by the decedent",
      B: "IRD (Income in Respect of a Decedent) items such as a traditional IRA",
      C: "Real property held as tenants in common with a non-spouse",
      D: "Appreciated stock in a brokerage account",
    },
    answer: "B",
    explanation: "§1014(c) specifically provides that the stepped-up basis rule does NOT apply to property that constitutes a right to receive an item of income in respect of a decedent (IRD). IRD items include traditional IRA balances, deferred compensation, accounts receivable, installment obligations, and other income that the decedent had a right to receive but had not yet received before death. IRD maintains the decedent's carryover basis characteristics and is taxed as ordinary income when received by the beneficiary.",
  },
  {
    id: 568,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer makes a gift of stock worth $500,000 (basis $100,000) and pays gift tax of $200,000. The donee's basis in the stock for gain purposes is:",
    choices: {
      A: "$100,000",
      B: "$200,000",
      C: "$260,000",
      D: "$300,000",
    },
    answer: "C",
    explanation: "Under §1015(d)(6), when gift tax is paid on a gift of appreciated property, the donee's basis is increased by the portion of gift tax attributable to the net appreciation. Net appreciation = $500,000 FMV − $100,000 donor basis = $400,000. Gift tax on appreciation = $200,000 gift tax × ($400,000 / $500,000) = $160,000. Donee's basis = $100,000 (donor's basis) + $160,000 (gift tax on appreciation) = $260,000. This prevents double taxation — the appreciation that was subject to gift tax gets a corresponding basis increase.",
  },
  {
    id: 569,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "A married couple has MAGI of $290,000. One spouse earns $250,000 in wages; the other has $40,000 of self-employment income. They owe the Additional Medicare Tax (AMT) of 0.9% on wages and SECA income exceeding the $250,000 MFJ threshold. How much Additional Medicare Tax do they owe?",
    choices: {
      A: "$0",
      B: "$360",
      C: "$225",
      D: "$450",
    },
    answer: "B",
    explanation: "The 0.9% Additional Medicare Tax under §3101(b)(2) applies to wages/SECA income exceeding $250,000 (MFJ). The couple's combined wages + SE income = $250,000 + $40,000 = $290,000. Excess over threshold = $290,000 − $250,000 = $40,000. Additional Medicare Tax = 0.9% × $40,000 = $360. The employer is not required to withhold this amount unless the individual employee's wages alone exceed $200,000.",
  },
  {
    id: 570,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "Under §2642, a grantor's GST exemption must be allocated to generation-skipping transfers. What is the GST exemption amount in 2024?",
    choices: {
      A: "$5,000,000",
      B: "$11,580,000",
      C: "$13,610,000",
      D: "$12,920,000",
    },
    answer: "C",
    explanation: "The GST tax exemption under §2631 is the same as the basic exclusion amount for estate and gift tax under §2010(c). For 2024, the applicable exclusion amount is $13,610,000 per individual (inflation-adjusted from the $10 million base established by the TCJA). The GST exemption allows this amount to be transferred to skip persons (grandchildren, great-grandchildren, etc.) without GST tax. The exemption is scheduled to revert to approximately $7 million (inflation-adjusted) after 2025 unless Congress acts.",
  },
  // ── DOMAIN 3 CONTINUED ──────────────────────────────────────────────────────
  {
    id: 571,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "An enrolled agent is representing a taxpayer in an audit. The IRS agent requests documents that the taxpayer's attorney prepared in anticipation of litigation. Under Circular 230 and applicable law, these documents are likely protected by:",
    choices: {
      A: "§7525 practitioner-client privilege",
      B: "Attorney-client privilege and/or work product doctrine",
      C: "Fifth Amendment privilege against self-incrimination",
      D: "The enrolled agent's §7525 privilege",
    },
    answer: "B",
    explanation: "Documents prepared by an attorney in anticipation of litigation are protected by the attorney-client privilege (for communications) and the work product doctrine (for materials prepared in preparation for litigation). The §7525 privilege applies to enrolled agents, CPAs, and other §10.3 practitioners, but only for tax advice — not for documents related to criminal matters or tax shelters. Attorney work product doctrine provides broader protection for litigation preparation materials.",
  },
  {
    id: 572,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "Under §6501(e)(1), the statute of limitations for assessment is extended to 6 years if a taxpayer omits from gross income an amount in excess of what percentage of the gross income stated in the return?",
    choices: {
      A: "10%",
      B: "20%",
      C: "25%",
      D: "50%",
    },
    answer: "C",
    explanation: "§6501(e)(1)(A) extends the normal 3-year assessment statute of limitations to 6 years if a taxpayer omits from gross income an amount 'properly includible' that exceeds 25% of the gross income stated in the return. This '6-year rule' for substantial omissions applies to both income tax returns and gift tax returns (§6501(e)(2) — 25% of gross gifts stated). It does not apply to fraudulent returns (unlimited), which are governed by §6501(c)(1).",
  },
  {
    id: 573,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "An enrolled agent discovers that a client incorrectly deducted $15,000 in a prior year that is now closed by the statute of limitations. The current year return does not involve the same error. Under Circular 230, what should the enrolled agent do?",
    choices: {
      A: "File an amended return to correct the prior year error",
      B: "Report the error to the IRS immediately",
      C: "Advise the client of the error; since the year is closed, no amended return is required",
      D: "Refuse to prepare the current year return until the prior year is corrected",
    },
    answer: "C",
    explanation: "Under Circular 230 §10.21, a practitioner must promptly advise a client of any noncompliance, error, or omission in a return they know about. However, since the year is closed by the statute of limitations, the IRS cannot assess additional tax on that year, so there is no legal obligation to file an amended return (and no tax benefit to doing so). The EA should advise the client of the error and note that no amended return is legally required, while ensuring the current year return is correct.",
  },
  {
    id: 574,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "The IRS issues a 30-day letter to a taxpayer after an audit proposing additional taxes. If the taxpayer does not respond to the 30-day letter, the IRS will issue a notice of deficiency (90-day letter). The taxpayer must file a petition in the U.S. Tax Court within 90 days of the notice. What happens if the taxpayer misses the 90-day deadline?",
    choices: {
      A: "The taxpayer may still petition Tax Court within an additional 30 days",
      B: "The taxpayer may only seek refund by paying the tax and filing a refund claim in district court or Court of Federal Claims",
      C: "The Tax Court automatically grants an extension",
      D: "The deficiency is automatically waived",
    },
    answer: "B",
    explanation: "The 90-day (150 days for foreign taxpayers) period to petition Tax Court after a notice of deficiency is jurisdictional — it cannot be extended. If the taxpayer misses this deadline, the IRS assesses the deficiency. The taxpayer's only remedy is to pay the full tax assessed, file a claim for refund with the IRS, wait for rejection (or 6 months to pass), and then sue in the U.S. District Court or Court of Federal Claims for a refund. Tax Court jurisdiction is lost forever once the 90-day window closes.",
  },
  {
    id: 575,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under Circular 230 §10.34, a practitioner may not sign a tax return unless the practitioner has a reasonable basis for each position taken. The standard for avoiding the preparer penalty under §6694(a) for understatements due to unreasonable positions is:",
    choices: {
      A: "Substantial authority",
      B: "More likely than not to be sustained",
      C: "Reasonable basis",
      D: "Not frivolous",
    },
    answer: "A",
    explanation: "§6694(a) imposes a penalty on tax return preparers for understatements attributable to unreasonable positions. A position is not 'unreasonable' if there is 'substantial authority' for the position (approximately 40% likelihood of being sustained). For non-disclosed positions, the preparer must have substantial authority. If the position is disclosed on the return, the standard drops to 'reasonable basis' (approximately 20% likelihood). For tax shelter positions, the standard is 'more likely than not.'",
  },
  {
    id: 576,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "A practitioner prepares a return claiming a deduction that the practitioner believes has only a 15% chance of being sustained if challenged. To avoid the §6694(a) preparer penalty, the practitioner should:",
    choices: {
      A: "Not sign the return",
      B: "Disclose the position on the return using Form 8275",
      C: "Attach a legal brief explaining the position",
      D: "Obtain the client's written consent",
    },
    answer: "B",
    explanation: "If a position has only a 15% chance of being sustained, it may meet the 'reasonable basis' standard (approximately 20% or more) but not the 'substantial authority' standard (approximately 40%). For a disclosed non-tax-shelter position, §6694(a) requires only 'reasonable basis.' By disclosing the position on Form 8275 (or Form 8275-R for regulations contrary positions), the preparer reduces the standard from substantial authority to reasonable basis, potentially avoiding the penalty. However, with only 15%, it may be borderline even for reasonable basis.",
  },
  {
    id: 577,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under §6404(e), the IRS may abate interest that is attributable to unreasonable error or delay by the IRS in performing a ministerial or managerial act. This interest abatement is available:",
    choices: {
      A: "Automatically upon request",
      B: "Only for interest exceeding $100",
      C: "For interest accruing after the IRS is notified of the error",
      D: "For all interest on the taxpayer's account regardless of cause",
    },
    answer: "C",
    explanation: "§6404(e)(1) allows the IRS to abate interest on any deficiency or payment of any tax to the extent the interest is attributable to any unreasonable error or delay of the IRS in performing a 'ministerial act' (mechanical, non-discretionary task) or a 'managerial act' (exercise of judgment or discretion). The abatement applies only to interest that accrued after the IRS was put on notice (i.e., the taxpayer or the IRS was aware of the error), not retroactively for all accumulated interest.",
  },
  {
    id: 578,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "A taxpayer in bankruptcy files a petition under Chapter 7. Under §362 of the Bankruptcy Code, an automatic stay prevents most creditor actions. Under the Internal Revenue Code, the IRS's ability to assess and collect taxes is:",
    choices: {
      A: "Completely unaffected by the bankruptcy stay",
      B: "Stayed with respect to most assessment and collection actions",
      C: "Stayed for collection only; assessment can continue",
      D: "Stayed only for corporate bankruptcy filings",
    },
    answer: "B",
    explanation: "The automatic stay under §362 of the Bankruptcy Code stays most IRS collection actions against the debtor and the bankruptcy estate, including levies, seizures, and most assessment actions. The IRS must generally seek relief from the stay before proceeding with collection. However, certain IRS actions are exempt from the stay, including: (1) tax audits, (2) issuing notices of deficiency, (3) demanding tax returns, and (4) processing refunds. The IRS can still assess pre-petition taxes via notice of deficiency during bankruptcy, but collection must await stay relief.",
  },
  // ── CROSS-DOMAIN ──────────────────────────────────────────────────────────
  {
    id: 579,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A sole proprietor with a Schedule C business and significant personal income is concerned about self-employment taxes. Which entity structure change would MOST effectively reduce self-employment tax while maintaining single-layer taxation?",
    choices: {
      A: "Convert to a C corporation",
      B: "Convert to an S corporation and pay reasonable compensation",
      C: "Convert to a limited liability company (single-member)",
      D: "Convert to a general partnership",
    },
    answer: "B",
    explanation: "S corporations allow business owners to split income between W-2 wages (subject to FICA/SE tax) and S corp distributions (not subject to SE tax). By paying a reasonable salary and taking remaining profits as distributions, the S corp owner avoids SE tax on the distribution portion. A single-member LLC is disregarded and still subject to full SE tax. A C corporation creates double taxation. A general partnership subjects all income to SE tax. The S corp structure is the classic SE tax reduction strategy.",
  },
  {
    id: 580,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A tax practitioner's client is both a 60% partner in a partnership (which operates an active business) and a 40% shareholder in an S corporation (which generates rental income). The partnership allocates $200,000 of income to the client; the S corporation passes through $50,000 of rental income. How is each item classified for passive activity purposes?",
    choices: {
      A: "Both are passive income",
      B: "Partnership income is active; rental income is passive",
      C: "Both are active if the client materially participates in both",
      D: "Partnership income is portfolio income; rental income is passive",
    },
    answer: "B",
    explanation: "Under §469, rental income is passive per se — rental activity is presumed passive regardless of material participation (with limited exceptions for real estate professionals or $25,000 rental allowance for active participation). Partnership income from an active business may be active if the client materially participates in the partnership's activities. If the client materially participates in the partnership business (e.g., works >500 hours/year), the $200,000 partnership income is active/non-passive, while the $50,000 S corp rental income remains passive.",
  },
  {
    id: 581,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A taxpayer is both an employee and a sole proprietor. The employer withholds FICA taxes on the employee wages. For self-employment income, the taxpayer pays SECA taxes. The combined Social Security wage base for both purposes in 2024 is:",
    choices: {
      A: "$147,000",
      B: "$160,200",
      C: "$168,600",
      D: "$176,100",
    },
    answer: "C",
    explanation: "The Social Security wage base for 2024 is $168,600. For a taxpayer who is both an employee and self-employed, the FICA wages withheld by the employer and the net SE income are combined for purposes of the Social Security wage base. Once combined wages + SE income exceed $168,600, only the 2.9% Medicare portion (and additional 0.9% if applicable) continues — the 12.4% Social Security portion stops at the wage base.",
  },
  {
    id: 582,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A practitioner represents a taxpayer before the IRS in an audit involving an S corporation owned 100% by the taxpayer. The IRS agent discovers that the taxpayer failed to report $80,000 of S corporation income on their personal return due to an error by the taxpayer's prior accountant. Under §6664, reasonable cause and good faith reliance on a tax professional is a defense to which penalties?",
    choices: {
      A: "Only the failure-to-pay penalty under §6651(a)(2)",
      B: "The accuracy-related penalty under §6662 but not the fraud penalty under §6663",
      C: "Both §6662 and §6663 penalties",
      D: "No penalties — reliance on a professional is absolute defense",
    },
    answer: "B",
    explanation: "§6664(c)(1) provides that no penalty under §6662 (accuracy-related) shall be imposed for any portion of an underpayment if there was reasonable cause and the taxpayer acted in good faith. Reliance on a competent tax professional who had all relevant information is a classic reasonable cause defense. However, §6664(c)(1) explicitly states it does not apply to the §6663 fraud penalty. Fraud requires intentional wrongdoing — good faith reliance is inconsistent with fraud, so §6663 effectively requires proof that reliance was not genuine.",
  },
  {
    id: 583,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A foreign national (nonresident alien) invests in a U.S. partnership that operates a real estate business. Under the Foreign Investment in Real Property Tax Act (FIRPTA), when the partnership sells U.S. real property, the foreign partner's distributive share of gain is:",
    choices: {
      A: "Exempt from U.S. tax under treaty provisions",
      B: "Taxed as effectively connected income (ECI) subject to U.S. tax at graduated rates",
      C: "Subject to 30% flat rate withholding on gross proceeds",
      D: "Exempt if the property was held more than 1 year",
    },
    answer: "B",
    explanation: "Under §897 (FIRPTA), gain recognized by a nonresident alien on the disposition of a U.S. real property interest (USRPI) is treated as effectively connected income (ECI) from a trade or business within the United States, subject to U.S. income tax at graduated rates (not the 30% flat withholding rate that applies to FDAP income). When a partnership sells USRPI, the foreign partner's distributive share of gain is ECI taxable in the U.S., and the partnership must withhold §1446(f) amounts on distributions.",
  },
  {
    id: 584,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A C corporation converts to an S corporation effective January 1. During the C corporation period, the corporation had accumulated E&P of $500,000. The S corporation subsequently distributes $600,000 to shareholders who have sufficient stock basis. How is the distribution taxed?",
    choices: {
      A: "Entirely return of capital",
      B: "$600,000 qualified dividend",
      C: "First $100,000 from AAA (return of stock basis/capital gain), then $500,000 as a dividend from accumulated E&P",
      D: "First $500,000 from accumulated E&P as dividend, then $100,000 return of capital",
    },
    answer: "C",
    explanation: "When an S corporation that has accumulated E&P from prior C corporation years makes a distribution, §1368(c) provides a three-tier ordering rule: (1) distributions reduce the Accumulated Adjustments Account (AAA) — tax-free return of stock basis; (2) any excess reduces Accumulated E&P — taxable as a dividend; (3) any remaining balance reduces stock basis (return of capital) or is capital gain. So $100,000 comes from AAA (non-dividend), then $500,000 from accumulated E&P (dividend).",
  },
  {
    id: 585,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A taxpayer operates a home-based business and claims a home office deduction. The practitioner must ensure the space is used 'regularly and exclusively' for business. Which situation QUALIFIES for the home office deduction?",
    choices: {
      A: "A room used as a home office during work hours and as a guest room on weekends",
      B: "A dedicated room used only to meet clients as the taxpayer's principal place of business",
      C: "A laptop and desk in the living room",
      D: "A garage used for storing personal items and occasionally for business inventory",
    },
    answer: "B",
    explanation: "§280A(c)(1) allows a home office deduction only if the space is used regularly and exclusively as: (a) the taxpayer's principal place of business, (b) a place to meet clients/customers in the normal course of business, or (c) a separate structure. A dedicated room used solely to meet clients and as the principal place of business satisfies the 'regular and exclusive use' test. Any personal use (guest room, living area, personal storage) disqualifies the space.",
  },
  {
    id: 586,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "An S corporation shareholder has a $0 stock basis and $50,000 of debt basis (from a direct loan to the corporation). The S corporation passes through a $60,000 loss. How much loss can the shareholder deduct and what is the effect on the debt basis?",
    choices: {
      A: "No loss deductible; at-risk rules prevent any deduction",
      B: "$50,000 deductible; debt basis reduced to $0",
      C: "$60,000 deductible; the excess carries forward",
      D: "$50,000 deductible; $10,000 suspended; debt basis reduced to $0",
    },
    answer: "D",
    explanation: "Under §1366(d)(1), an S corp shareholder's deductible loss is limited to the sum of the adjusted basis in stock PLUS the adjusted basis in debt owed by the corporation to the shareholder. With $0 stock basis and $50,000 debt basis, the shareholder can deduct $50,000. The remaining $10,000 loss is suspended and carries forward under §1366(d)(2) until the shareholder restores basis. The debt basis is reduced from $50,000 to $0 (losses reduce debt basis after stock basis is exhausted under §1367(b)(2)).",
  },
  {
    id: 587,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A practitioner prepares both a corporation's Form 1120 and the sole shareholder's Form 1040. During the preparation, the practitioner discovers the corporation paid the shareholder's personal expenses, which were not reported as compensation. Under Circular 230, the practitioner should:",
    choices: {
      A: "Report the issue to the IRS immediately",
      B: "Advise the client to correct the treatment and reflect proper compensation on both returns",
      C: "Ignore the issue if the amounts are immaterial",
      D: "Resign from the engagement without explanation",
    },
    answer: "B",
    explanation: "Under Circular 230 §10.21, the practitioner must promptly inform the client of any error or omission in the return. The corporation should have reported the personal expense payments as compensation to the shareholder (deductible to the corp, taxable to the shareholder as wages subject to FICA). The practitioner should advise the client to correct this treatment — reflecting the amounts as taxable compensation on Form W-2 and including it in the shareholder's gross income on Form 1040, and deducting on the corporate return.",
  },
  {
    id: 588,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "An enrolled agent is asked to sign a tax return as the paid preparer, but the EA disagrees with a major position the client insists on taking. The position has substantial authority but the EA believes it is incorrect. Under Circular 230, may the EA sign the return?",
    choices: {
      A: "No — the EA must refuse to sign if they personally believe the position is wrong",
      B: "Yes — if there is substantial authority, the EA may sign even if they disagree",
      C: "Yes — the client's instructions override the EA's professional judgment",
      D: "No — the EA must obtain a second opinion from another EA before signing",
    },
    answer: "B",
    explanation: "Under Circular 230 §10.34(a) and the preparer penalty standards, a practitioner may sign a return if there is 'substantial authority' for the position taken (approximately 40% chance of being sustained). The practitioner is not required to agree that the position is correct — only that there is a reasonable legal basis for it meeting the applicable standard. If the position has substantial authority, the EA may sign without violating Circular 230 or risking a §6694 preparer penalty.",
  },
  {
    id: 589,
    domain: "Cross-Domain",
    difficulty: "Medium",
    question: "A taxpayer received a $50,000 settlement from a lawsuit for 'emotional distress' damages (not physical injury). Under §104, this amount is:",
    choices: {
      A: "Excluded from gross income as personal injury damages",
      B: "Included in gross income as ordinary income",
      C: "Excluded up to $20,000; excess included in income",
      D: "Excluded if the emotional distress resulted from physical injury",
    },
    answer: "B",
    explanation: "§104(a)(2) excludes from gross income damages received for personal physical injuries or physical sickness. Emotional distress damages are NOT excludable under §104 unless they are attributable to a physical injury or physical sickness. §104(a) specifically provides that emotional distress is not considered a physical injury or sickness, so payments for emotional distress are included in gross income as ordinary income. (If the emotional distress results from a physical injury, those damages may be excludable.)",
  },
  {
    id: 590,
    domain: "Cross-Domain",
    difficulty: "Hard",
    question: "A taxpayer operates an S corporation with accumulated E&P of $200,000 from prior C corp years. The S corporation's AAA is $0. The S corporation distributes $150,000 to the sole shareholder who has $80,000 of stock basis. Under the PTTP (post-termination transition period) rules, what election might the shareholder make?",
    choices: {
      A: "Elect to treat all distributions as coming from AAA before E&P",
      B: "Elect to treat distributions as coming from accumulated E&P before AAA",
      C: "Elect to have all distributions treated as return of basis only",
      D: "Elect out of the §1368(c) ordering rules entirely",
    },
    answer: "B",
    explanation: "Under §1368(e)(3), an S corporation (with the consent of all affected shareholders) may elect to have distributions treated as made from accumulated C corporation E&P before reducing AAA. This 'bypass election' causes distributions to be taxed as dividends (from E&P) rather than tax-free return of AAA. This election is sometimes used in restructuring to 'clear out' accumulated E&P to avoid the AAA bypass dividend issue in future years. Under normal ordering, distributions come from AAA first.",
  },
  // ── DOMAIN 1 — ADVANCED ──────────────────────────────────────────────────────
  {
    id: 591,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §1504(a), an affiliated group of corporations may file a consolidated return. A corporation is included in an affiliated group if the common parent owns at least what percentage of the total voting power AND total value of each subsidiary's stock?",
    choices: {
      A: "50%",
      B: "80%",
      C: "100%",
      D: "51%",
    },
    answer: "B",
    explanation: "§1504(a)(2) defines an affiliated group as corporations connected through stock ownership in which the common parent (and/or other includible corporations) own at least 80% of the total combined voting power of all classes of stock entitled to vote AND at least 80% of the total value of shares of all classes of stock of each includible corporation. The 80/80 test (voting power AND value) determines affiliated group membership for consolidated return purposes.",
  },
  {
    id: 592,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A corporation distributes appreciated property (FMV $300,000, basis $100,000) as a dividend to shareholders. Under §311(b), the corporation must recognize gain as if it sold the property at FMV. The amount of gain the corporation recognizes is:",
    choices: {
      A: "$0 — dividends are not sales",
      B: "$100,000",
      C: "$200,000",
      D: "$300,000",
    },
    answer: "C",
    explanation: "§311(b)(1) provides that if a corporation distributes appreciated property (FMV > adjusted basis), it recognizes gain as if the property were sold at its FMV at the time of distribution. The corporation's gain = FMV ($300,000) − basis ($100,000) = $200,000. The gain is taxable to the corporation. The shareholder receives the property at FMV ($300,000) and treats it as a dividend (to the extent of E&P). The corporation cannot recognize a loss on property distributions (§311(a)).",
  },
  {
    id: 593,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "Under §482, the IRS may reallocate income between related entities to clearly reflect income. The best method rule requires that the method used for determining arm's-length pricing must provide the most reliable measure of an arm's-length result. Which of the following is NOT a specified §482 method for tangible property transactions?",
    choices: {
      A: "Comparable Uncontrolled Price (CUP) method",
      B: "Resale Price method",
      C: "Cost Plus method",
      D: "Discounted Cash Flow method",
    },
    answer: "D",
    explanation: "The IRS regulations under §482 specify the following methods for tangible property: (1) Comparable Uncontrolled Price (CUP), (2) Resale Price, (3) Cost Plus, (4) Comparable Profits Method (CPM), and (5) Profit Split. The Discounted Cash Flow method is not among the specified §482 methods for tangible property transfer pricing, though it may be used for valuation purposes in other contexts (like intangibles valuation under §482(d) income method).",
  },
  {
    id: 594,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "Under §172, the net operating loss (NOL) deduction for losses arising in tax years beginning after December 31, 2017 (post-TCJA) is limited to what percentage of taxable income?",
    choices: {
      A: "80%",
      B: "100%",
      C: "90%",
      D: "50%",
    },
    answer: "A",
    explanation: "Post-TCJA (for NOLs arising in tax years beginning after 12/31/2017), §172(a)(2) limits the NOL deduction to 80% of taxable income (computed without the NOL deduction). This replaced the prior rule allowing 100% NOL deductions (with 2-year carryback and 20-year carryforward). Post-TCJA NOLs have no carryback (except for farming losses) but can carry forward indefinitely, subject to the 80% limitation.",
  },
  {
    id: 595,
    domain: "Domain 1",
    difficulty: "Hard",
    question: "A corporation has $1,000,000 in ordinary income and a $600,000 dividend from a 30%-owned domestic corporation (eligible for a dividends received deduction). Under post-TCJA §243 rates, the corporation's DRD is:",
    choices: {
      A: "$390,000 (65% of $600,000)",
      B: "$480,000 (80% of $600,000)",
      C: "$600,000 (100%)",
      D: "$300,000 (50% of $600,000)",
    },
    answer: "A",
    explanation: "Post-TCJA (2018), §243 DRD rates are: less than 20% ownership = 50%; 20%–79.9% ownership = 65%; 80%+ ownership (affiliated group) = 100%. With 30% ownership, the corporation qualifies for the 65% DRD: 65% × $600,000 = $390,000. Note the TCJA reduced the rates from prior law (which was 70%/80%/100%). The income limitation test (§246(b)) is then applied: the DRD cannot exceed 65% of taxable income computed without the DRD. With $1,000,000 of ordinary income, 65% × $1,600,000 = $1,040,000 — the income limitation doesn't reduce the DRD here.",
  },
  {
    id: 596,
    domain: "Domain 1",
    difficulty: "Medium",
    question: "A partnership has a 'hot asset' issue under §751. When a partner sells their partnership interest, ordinary income must be recognized for the partner's share of 'unrealized receivables' and 'inventory items.' Which of the following is considered an 'unrealized receivable' under §751(c)?",
    choices: {
      A: "Accounts receivable of a cash-basis partnership",
      B: "A capital asset held for investment",
      C: "Marketable securities",
      D: "Real estate held for investment",
    },
    answer: "A",
    explanation: "§751(c) defines 'unrealized receivables' to include: (1) rights to payment for goods delivered or to be delivered (to the extent not previously included in income) — most importantly, accounts receivable of a cash-basis partnership that have never been included in income; and (2) rights to payment for services rendered or to be rendered. The term also includes potential §1245 and §1250 recapture amounts. A sale of a partnership interest requires the selling partner to recognize ordinary income for their share of these unrealized receivables.",
  },
  {
    id: 597,
    domain: "Domain 2",
    difficulty: "Medium",
    question: "Under §2503(b), the annual gift tax exclusion for 2024 is $18,000 per donee. This exclusion is available only for gifts of a 'present interest.' Which of the following is a gift of a present interest qualifying for the annual exclusion?",
    choices: {
      A: "A contribution to a testamentary trust",
      B: "A gift to an irrevocable trust where the beneficiary cannot demand distribution until age 35",
      C: "A direct gift of cash to a grandchild",
      D: "A transfer to a sprinkle trust where the trustee has sole discretion over distributions",
    },
    answer: "C",
    explanation: "A 'present interest' under Reg. §25.2503-3(b) is an unrestricted right to immediate use, possession, or enjoyment of property. A direct cash gift to any donee (grandchild, child, friend) is the clearest example of a present interest qualifying for the $18,000 annual exclusion. Gifts to trusts where the beneficiary cannot immediately demand distribution are future interests and do not qualify — unless specific exceptions apply (§2503(b) Crummey powers, §2503(c) minor's trusts, or §529 5-year election).",
  },
  {
    id: 598,
    domain: "Domain 2",
    difficulty: "Hard",
    question: "A taxpayer inherits a traditional IRA from a non-spouse decedent who died in 2023. Under the SECURE Act's 10-year rule, when must the entire inherited IRA be distributed?",
    choices: {
      A: "By December 31 of the 5th year following the year of death",
      B: "By December 31 of the 10th year following the year of death",
      C: "Over the beneficiary's life expectancy",
      D: "By the end of the year the deceased would have turned 73",
    },
    answer: "B",
    explanation: "Under the SECURE Act (2019) and SECURE 2.0 (2022), most non-spouse beneficiaries of retirement accounts inherited after December 31, 2019 must distribute the entire account balance by December 31 of the 10th year following the year of the account owner's death. Annual RMDs during the 10-year period are required if the deceased had started RMDs (for 'eligible designated beneficiaries' like spouses, minor children, disabled individuals, and those within 10 years of the decedent's age, the stretch rule still applies).",
  },
  {
    id: 599,
    domain: "Domain 3",
    difficulty: "Hard",
    question: "An enrolled agent is suspended from practice before the IRS. Which of the following activities may the suspended EA continue to perform?",
    choices: {
      A: "Represent clients in IRS audits",
      B: "Prepare tax returns for compensation",
      C: "Appear before Appeals",
      D: "Sign Form 2848 Power of Attorney",
    },
    answer: "B",
    explanation: "Suspension from practice before the IRS under Circular 230 prohibits the suspended practitioner from representing taxpayers before the IRS — this includes audits, appeals, collections, and other IRS proceedings. However, suspension does not prevent the practitioner from preparing tax returns for compensation (unless separately prohibited by state law or court order). Tax return preparation is not 'practice before the IRS' under Circular 230 §10.2(a)(4) — representing a client IS practice, but merely preparing returns is not.",
  },
  {
    id: 600,
    domain: "Domain 3",
    difficulty: "Medium",
    question: "Under §6038, U.S. persons controlling a foreign corporation must file annual information returns (Form 5471). The penalty for failure to file Form 5471 for each annual accounting period is:",
    choices: {
      A: "$1,000 per violation",
      B: "$10,000 per annual accounting period",
      C: "$5,000 per annual accounting period",
      D: "$25,000 per Form",
    },
    answer: "B",
    explanation: "§6038(b)(1) imposes a penalty of $10,000 for each annual accounting period for which a person fails to furnish the required information (Form 5471) on foreign corporations. If the failure continues for more than 90 days after IRS notice, additional penalties of $10,000 per 30-day period (capped at $50,000) apply under §6038(b)(2). The IRS may also reduce foreign tax credits (§6038(c)) if Form 5471 is not filed. These penalties make Form 5471 compliance critically important for international tax practitioners.",
  },
];
